// Code generated by bebopc-gen-swift. DO NOT EDIT.
// source: /Users/andrew/projects/bebop-vnext/plugins/swift/Tests/SwiftBebopTests/test_service.bop
// bebopc 2026.0.0-alpha.3
// edition 2026
//
// This file requires the Bebop runtime library.
// https://github.com/6over3/bebop
//
// The Bebop compiler and runtime are licensed under the Apache License,
// Version 2.0. You may obtain a copy of the License at:
// https://www.apache.org/licenses/LICENSE-2.0
//
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 6OVER3 INSTITUTE
// swiftlint:disable all

import SwiftBebop
// @@bebop_insertion_point(imports)

public struct EchoRequest: BebopRecord, BebopReflectable {
    public let value: String

    enum CodingKeys: String, CodingKey {
        case value
    }

    public init(value: String) {
        self.value = value
    }

    public static func decode(from reader: inout BebopReader) throws -> EchoRequest {
        // @@bebop_insertion_point(decode_start:EchoRequest)
        let value = try reader.readString()
        // @@bebop_insertion_point(decode_end:EchoRequest)
        return EchoRequest(value: value)
    }

    public func encode(to writer: inout BebopWriter) {
        // @@bebop_insertion_point(encode_start:EchoRequest)
        writer.writeString(value)
        // @@bebop_insertion_point(encode_end:EchoRequest)
    }

    public var encodedSize: Int {
        var size = 0
        size += (4 + value.utf8.count + 1)
        return size
    }

    public struct View: BebopRecordView {
        public let encoded: BebopView

        private let _decodeLimits: BebopDecodeLimits

        public let value: BebopStringView

        public init(_ bytes: [UInt8], limits: BebopDecodeLimits = .default) throws { try self.init(BebopView(bytes), limits: limits) }

        public init(_ encoded: BebopView, limits: BebopDecodeLimits = .default) throws {
            var reader = BebopViewReader(encoded, limits: limits)
            self = try EchoRequest.readView(from: &reader)
            try reader.finish()
        }

        fileprivate init(validated encoded: BebopView, limits: BebopDecodeLimits, value: BebopStringView) {
            self.encoded = encoded
            self._decodeLimits = limits
            self.value = value
        }

        public func decoded() throws -> EchoRequest {
            try encoded.withUnsafeBytes { bytes in
                var reader = BebopReader(data: bytes, limits: _decodeLimits)
                return try EchoRequest.decode(from: &reader)
            }
        }
    }

    public static func readView(from reader: inout BebopViewReader) throws -> View {
        let start = reader.position
        let value = try reader.readStringView()
        return View(validated: reader.view(from: start), limits: reader.limits, value: value)
    }

    public static let bebopReflection = BebopTypeReflection(
        name: "EchoRequest",
        fqn: "EchoRequest",
        kind: .struct,
        detail: .struct(
            StructReflection(fields: [
                BebopFieldReflection(
                    name: "value",
                    index: 0,
                    typeName: "String"
                )
            ])
        )
    )

    // @@bebop_insertion_point(struct_scope:EchoRequest)
}

public struct EchoResponse: BebopRecord, BebopReflectable {
    public let value: String

    enum CodingKeys: String, CodingKey {
        case value
    }

    public init(value: String) {
        self.value = value
    }

    public static func decode(from reader: inout BebopReader) throws -> EchoResponse {
        // @@bebop_insertion_point(decode_start:EchoResponse)
        let value = try reader.readString()
        // @@bebop_insertion_point(decode_end:EchoResponse)
        return EchoResponse(value: value)
    }

    public func encode(to writer: inout BebopWriter) {
        // @@bebop_insertion_point(encode_start:EchoResponse)
        writer.writeString(value)
        // @@bebop_insertion_point(encode_end:EchoResponse)
    }

    public var encodedSize: Int {
        var size = 0
        size += (4 + value.utf8.count + 1)
        return size
    }

    public struct View: BebopRecordView {
        public let encoded: BebopView

        private let _decodeLimits: BebopDecodeLimits

        public let value: BebopStringView

        public init(_ bytes: [UInt8], limits: BebopDecodeLimits = .default) throws { try self.init(BebopView(bytes), limits: limits) }

        public init(_ encoded: BebopView, limits: BebopDecodeLimits = .default) throws {
            var reader = BebopViewReader(encoded, limits: limits)
            self = try EchoResponse.readView(from: &reader)
            try reader.finish()
        }

        fileprivate init(validated encoded: BebopView, limits: BebopDecodeLimits, value: BebopStringView) {
            self.encoded = encoded
            self._decodeLimits = limits
            self.value = value
        }

        public func decoded() throws -> EchoResponse {
            try encoded.withUnsafeBytes { bytes in
                var reader = BebopReader(data: bytes, limits: _decodeLimits)
                return try EchoResponse.decode(from: &reader)
            }
        }
    }

    public static func readView(from reader: inout BebopViewReader) throws -> View {
        let start = reader.position
        let value = try reader.readStringView()
        return View(validated: reader.view(from: start), limits: reader.limits, value: value)
    }

    public static let bebopReflection = BebopTypeReflection(
        name: "EchoResponse",
        fqn: "EchoResponse",
        kind: .struct,
        detail: .struct(
            StructReflection(fields: [
                BebopFieldReflection(
                    name: "value",
                    index: 0,
                    typeName: "String"
                )
            ])
        )
    )

    // @@bebop_insertion_point(struct_scope:EchoResponse)
}

public struct CountRequest: BebopRecord, BebopReflectable {
    public let n: UInt32

    enum CodingKeys: String, CodingKey {
        case n
    }

    public init(n: UInt32) {
        self.n = n
    }

    public static func decode(from reader: inout BebopReader) throws -> CountRequest {
        // @@bebop_insertion_point(decode_start:CountRequest)
        let n = try reader.readUInt32()
        // @@bebop_insertion_point(decode_end:CountRequest)
        return CountRequest(n: n)
    }

    public func encode(to writer: inout BebopWriter) {
        // @@bebop_insertion_point(encode_start:CountRequest)
        writer.writeUInt32(n)
        // @@bebop_insertion_point(encode_end:CountRequest)
    }

    public var encodedSize: Int { 4 }

    public struct View: BebopRecordView {
        public let encoded: BebopView

        private let _decodeLimits: BebopDecodeLimits

        public let n: UInt32

        public init(_ bytes: [UInt8], limits: BebopDecodeLimits = .default) throws { try self.init(BebopView(bytes), limits: limits) }

        public init(_ encoded: BebopView, limits: BebopDecodeLimits = .default) throws {
            var reader = BebopViewReader(encoded, limits: limits)
            self = try CountRequest.readView(from: &reader)
            try reader.finish()
        }

        fileprivate init(validated encoded: BebopView, limits: BebopDecodeLimits, n: UInt32) {
            self.encoded = encoded
            self._decodeLimits = limits
            self.n = n
        }

        public func decoded() throws -> CountRequest {
            try encoded.withUnsafeBytes { bytes in
                var reader = BebopReader(data: bytes, limits: _decodeLimits)
                return try CountRequest.decode(from: &reader)
            }
        }
    }

    public static func readView(from reader: inout BebopViewReader) throws -> View {
        let start = reader.position
        let n = try reader.readUInt32()
        return View(validated: reader.view(from: start), limits: reader.limits, n: n)
    }

    public static let bebopReflection = BebopTypeReflection(
        name: "CountRequest",
        fqn: "CountRequest",
        kind: .struct,
        detail: .struct(
            StructReflection(fields: [
                BebopFieldReflection(
                    name: "n",
                    index: 0,
                    typeName: "UInt32"
                )
            ])
        )
    )

    // @@bebop_insertion_point(struct_scope:CountRequest)
}

public struct CountResponse: BebopRecord, BebopReflectable {
    public let i: UInt32

    enum CodingKeys: String, CodingKey {
        case i
    }

    public init(i: UInt32) {
        self.i = i
    }

    public static func decode(from reader: inout BebopReader) throws -> CountResponse {
        // @@bebop_insertion_point(decode_start:CountResponse)
        let i = try reader.readUInt32()
        // @@bebop_insertion_point(decode_end:CountResponse)
        return CountResponse(i: i)
    }

    public func encode(to writer: inout BebopWriter) {
        // @@bebop_insertion_point(encode_start:CountResponse)
        writer.writeUInt32(i)
        // @@bebop_insertion_point(encode_end:CountResponse)
    }

    public var encodedSize: Int { 4 }

    public struct View: BebopRecordView {
        public let encoded: BebopView

        private let _decodeLimits: BebopDecodeLimits

        public let i: UInt32

        public init(_ bytes: [UInt8], limits: BebopDecodeLimits = .default) throws { try self.init(BebopView(bytes), limits: limits) }

        public init(_ encoded: BebopView, limits: BebopDecodeLimits = .default) throws {
            var reader = BebopViewReader(encoded, limits: limits)
            self = try CountResponse.readView(from: &reader)
            try reader.finish()
        }

        fileprivate init(validated encoded: BebopView, limits: BebopDecodeLimits, i: UInt32) {
            self.encoded = encoded
            self._decodeLimits = limits
            self.i = i
        }

        public func decoded() throws -> CountResponse {
            try encoded.withUnsafeBytes { bytes in
                var reader = BebopReader(data: bytes, limits: _decodeLimits)
                return try CountResponse.decode(from: &reader)
            }
        }
    }

    public static func readView(from reader: inout BebopViewReader) throws -> View {
        let start = reader.position
        let i = try reader.readUInt32()
        return View(validated: reader.view(from: start), limits: reader.limits, i: i)
    }

    public static let bebopReflection = BebopTypeReflection(
        name: "CountResponse",
        fqn: "CountResponse",
        kind: .struct,
        detail: .struct(
            StructReflection(fields: [
                BebopFieldReflection(
                    name: "i",
                    index: 0,
                    typeName: "UInt32"
                )
            ])
        )
    )

    // @@bebop_insertion_point(struct_scope:CountResponse)
}

/// Widget inventory service.
public enum WidgetService: BebopServiceDefinition {
    public enum Method: UInt32, BebopServiceMethod, CaseIterable {
        case getWidget = 0xA3F73AA7
        case listWidgets = 0xBB7F3698
        case uploadWidgets = 0xC1A30C3B
        case syncWidgets = 0x317F5C17

        public var name: String {
            switch self {
                case .getWidget: return "GetWidget"
                case .listWidgets: return "ListWidgets"
                case .uploadWidgets: return "UploadWidgets"
                case .syncWidgets: return "SyncWidgets"
            }
        }

        public var methodType: MethodType {
            switch self {
                case .getWidget: return .unary
                case .listWidgets: return .serverStream
                case .uploadWidgets: return .clientStream
                case .syncWidgets: return .duplexStream
            }
        }

        public var requestTypeUrl: String {
            switch self {
                case .getWidget: return "type.bebop.sh/EchoRequest"
                case .listWidgets: return "type.bebop.sh/CountRequest"
                case .uploadWidgets: return "type.bebop.sh/EchoRequest"
                case .syncWidgets: return "type.bebop.sh/EchoRequest"
            }
        }

        public var responseTypeUrl: String {
            switch self {
                case .getWidget: return "type.bebop.sh/EchoResponse"
                case .listWidgets: return "type.bebop.sh/CountResponse"
                case .uploadWidgets: return "type.bebop.sh/EchoResponse"
                case .syncWidgets: return "type.bebop.sh/EchoResponse"
            }
        }
    }

    public static let serviceName = "WidgetService"
    public static let serviceInfo = ServiceInfo(
        name: "WidgetService",
        methods: [
            MethodInfo(
                name: "GetWidget",
                methodId: 0xA3F73AA7,
                methodType: .unary,
                requestTypeUrl: "type.bebop.sh/EchoRequest",
                responseTypeUrl: "type.bebop.sh/EchoResponse"
            ),
            MethodInfo(
                name: "ListWidgets",
                methodId: 0xBB7F3698,
                methodType: .serverStream,
                requestTypeUrl: "type.bebop.sh/CountRequest",
                responseTypeUrl: "type.bebop.sh/CountResponse"
            ),
            MethodInfo(
                name: "UploadWidgets",
                methodId: 0xC1A30C3B,
                methodType: .clientStream,
                requestTypeUrl: "type.bebop.sh/EchoRequest",
                responseTypeUrl: "type.bebop.sh/EchoResponse"
            ),
            MethodInfo(
                name: "SyncWidgets",
                methodId: 0x317F5C17,
                methodType: .duplexStream,
                requestTypeUrl: "type.bebop.sh/EchoRequest",
                responseTypeUrl: "type.bebop.sh/EchoResponse"
            )
        ]
    )
    public static func method(for id: UInt32) -> Method? { Method(rawValue: id) }
    // @@bebop_insertion_point(service_scope:WidgetService)
}

public protocol WidgetServiceHandler: BebopHandler {
    /// Echo back the input.
    func getWidget(
        _ request: EchoRequest.View,
        context: RpcContext
    ) async throws -> EchoResponse

    /// Stream count responses.
    func listWidgets(
        _ request: CountRequest.View,
        context: RpcContext
    ) async throws -> AsyncThrowingStream<CountResponse, Error>

    func uploadWidgets(
        _ requests: AsyncThrowingStream<EchoRequest.View, Error>,
        context: RpcContext
    ) async throws -> EchoResponse

    /// Bidirectional echo.
    func syncWidgets(
        _ requests: AsyncThrowingStream<EchoRequest.View, Error>,
        context: RpcContext
    ) async throws -> AsyncThrowingStream<EchoResponse, Error>
}

extension BebopRouterBuilder {
    public func register(widgetService handler: some WidgetServiceHandler) {
        register(WidgetService.self, unary: { method, context, payload in
            switch method {
                case .getWidget:
                    let req = try EchoRequest.View(payload, limits: context.decodeLimits)
                    let res = try await handler.getWidget(req, context: context)
                    return res.encode()
                default: throw BebopRpcError(code: .unimplemented)
            }
        }, serverStream: { method, context, payload in
            switch method {
                case .listWidgets:
                    let req = try CountRequest.View(payload, limits: context.decodeLimits)
                    let typed = try await handler.listWidgets(req, context: context)
                    return BebopStreams.map(typed) { item in
                        try Task.checkCancellation()
                        if let d = context.deadline, d.isPast {
                            throw BebopRpcError(code: .deadlineExceeded)
                        }
                        return StreamElement(bytes: item.encode(), cursor: context.dequeueCursor())
                    }
                default: throw BebopRpcError(code: .unimplemented)
            }
        }, clientStream: { method, context in
            switch method {
                case .uploadWidgets:
                    let inbound = RpcInboundStream<EchoRequest.View>()
                    let task = Task {
                        do {
                            let response = try await handler.uploadWidgets(inbound.stream, context: context)
                            await inbound.finish()
                            return response
                        } catch {
                            await inbound.finish(throwing: error)
                            throw error
                        }
                    }
                    return (
                        send: { bytes in
                            try Task.checkCancellation()
                            if let d = context.deadline, d.isPast {
                                throw BebopRpcError(code: .deadlineExceeded)
                            }
                            let req = try EchoRequest.View(bytes, limits: context.decodeLimits)
                            try await inbound.send(req)
                        },
                        finish: {
                            await inbound.finish()
                            return try await task.value.encode()
                        }
                    )
                default: throw BebopRpcError(code: .unimplemented)
            }
        }, duplexStream: { method, context in
            switch method {
                case .syncWidgets:
                    let inbound = RpcInboundStream<EchoRequest.View>()
                    let rawResponses = BebopStreams.map(
                        { try await handler.syncWidgets(inbound.stream, context: context) },
                        onCancel: { await inbound.finish() }
                    ) { item in
                        try Task.checkCancellation()
                        if let d = context.deadline, d.isPast {
                            throw BebopRpcError(code: .deadlineExceeded)
                        }
                        return StreamElement(bytes: item.encode(), cursor: context.dequeueCursor())
                    }
                    return (
                        send: { bytes in
                            try Task.checkCancellation()
                            if let d = context.deadline, d.isPast {
                                throw BebopRpcError(code: .deadlineExceeded)
                            }
                            let req = try EchoRequest.View(bytes, limits: context.decodeLimits)
                            try await inbound.send(req)
                        },
                        finish: { await inbound.finish() },
                        responses: rawResponses
                    )
                default: throw BebopRpcError(code: .unimplemented)
            }
        })
    }
}

public struct WidgetServiceClient<C: BebopChannel>: Sendable {
    public let channel: C

    public init(channel: C) { self.channel = channel }

    /// Echo back the input.
    public func getWidget(
        _ request: EchoRequest,
        context: RpcContext = RpcContext()
    ) async throws -> Response<EchoResponse, C.Metadata> {
        try await channel.unary(
            method: 0xA3F73AA7,
            request: request.encode(),
            context: context
        ).map { try EchoResponse.decode(from: $0) }
    }

    public func getWidget(
        value: String,
        context: RpcContext = RpcContext()
    ) async throws -> Response<EchoResponse, C.Metadata> {
        try await getWidget(EchoRequest(value: value), context: context)
    }

    /// Stream count responses.
    public func listWidgets(
        _ request: CountRequest,
        context: RpcContext = RpcContext()
    ) async throws -> StreamResponse<CountResponse, C.Metadata> {
        try await channel.serverStream(
            method: 0xBB7F3698,
            request: request.encode(),
            context: context
        ).map { try CountResponse.decode(from: $0) }
    }

    public func listWidgets(
        n: UInt32,
        context: RpcContext = RpcContext()
    ) async throws -> StreamResponse<CountResponse, C.Metadata> {
        try await listWidgets(CountRequest(n: n), context: context)
    }

    @available(*, deprecated, message: "use CollectV2")
    public func uploadWidgets(
        context: RpcContext = RpcContext()
    ) async throws -> ClientStream<EchoRequest, EchoResponse, C.Metadata> {
        try await channel.clientStream(
            method: 0xC1A30C3B,
            context: context
        ).map(
            request: { $0.encode() },
            response: { try EchoResponse.decode(from: $0) }
        )
    }

    /// Bidirectional echo.
    public func syncWidgets(
        context: RpcContext = RpcContext()
    ) async throws -> DuplexStream<EchoRequest, EchoResponse, C.Metadata> {
        try await channel.duplexStream(
            method: 0x317F5C17,
            context: context
        ).map(
            request: { $0.encode() },
            response: { try EchoResponse.decode(from: $0) }
        )
    }
}

public struct WidgetServiceBatch<C: BebopChannel> {
    public let batch: Batch<C>

    @discardableResult
    public func getWidget(_ request: EchoRequest) -> CallRef<EchoResponse> {
        batch.addUnary(methodId: 0xA3F73AA7, request: request)
    }

    @discardableResult
    public func getWidget(value: String) -> CallRef<EchoResponse> {
        getWidget(EchoRequest(value: value))
    }

    @discardableResult
    public func getWidget<T: BebopRecord>(forwarding ref: CallRef<T>) -> CallRef<EchoResponse> {
        batch.addUnary(methodId: 0xA3F73AA7, forwardingFrom: ref.callId)
    }

    @discardableResult
    public func listWidgets(_ request: CountRequest) -> StreamRef<CountResponse> {
        batch.addServerStream(methodId: 0xBB7F3698, request: request)
    }

    @discardableResult
    public func listWidgets(n: UInt32) -> StreamRef<CountResponse> {
        listWidgets(CountRequest(n: n))
    }

    @discardableResult
    public func listWidgets<T: BebopRecord>(forwarding ref: CallRef<T>) -> StreamRef<CountResponse> {
        batch.addServerStream(methodId: 0xBB7F3698, forwardingFrom: ref.callId)
    }
}

extension Batch {
    public var widgetService: WidgetServiceBatch<Channel> { WidgetServiceBatch(batch: self) }
}

public struct WidgetServiceDispatch<C: BebopChannel> {
    public let dispatcher: FutureDispatcher<C>

    public func getWidget(
        _ request: EchoRequest,
        options: DispatchOptions = .init(),
        context: RpcContext = RpcContext()
    ) async throws -> BebopFuture<EchoResponse> {
        try await dispatcher.dispatch(
            methodId: 0xA3F73AA7,
            request: request,
            options: options,
            context: context)
    }

    public func getWidget(
        value: String,
        options: DispatchOptions = .init(),
        context: RpcContext = RpcContext()
    ) async throws -> BebopFuture<EchoResponse> {
        try await getWidget(EchoRequest(value: value), options: options, context: context)
    }
}

extension FutureDispatcher {
    public var widgetService: WidgetServiceDispatch<Channel> { WidgetServiceDispatch(dispatcher: self) }
}

// @@bebop_insertion_point(eof)
