import BebopPlugin

enum ServiceGenMode: String {
    case none
    case client
    case server
    case both
}

struct GeneratorOptions {
    var visibility: String = "public "
    var services: ServiceGenMode = .both
}

struct SwiftGenerator {
    let options: GeneratorOptions
    let compilerVersion: Version?

    private static let wellKnownFQNs: Set<String> = [
        "bebop.Any", "bebop.Empty", "bebop.TYPE_URL_PREFIX",
    ]

    func generate(schema: SchemaDescriptor) throws -> String {
        var declarations = [
            "import SwiftBebop\n// @@bebop_insertion_point(imports)",
        ]

        if let definitions = schema.definitions {
            try validateDefinitionNames(definitions, scope: schema.path ?? "schema")
            for def in definitions {
                try declarations.append(contentsOf: generateDefinition(def))
            }
        }

        let body = declarations.joined(separator: "\n\n")
        return try generatedNotice(schema: schema) + body
            + "\n\n// @@bebop_insertion_point(eof)\n"
    }

    private func validateDefinitionNames(
        _ definitions: [DefinitionDescriptor],
        scope: String
    ) throws {
        var names: Set<String> = []
        for definition in definitions {
            guard let kind = definition.kind else {
                throw CodegenError.malformedDefinition("definition missing kind")
            }
            if let fqn = definition.fqn, Self.wellKnownFQNs.contains(fqn) {
                continue
            }
            if kind != .decorator, !(kind == .service && options.services == .none) {
                guard let sourceName = definition.name else {
                    throw CodegenError.malformedDefinition("definition missing name")
                }
                let generatedName =
                    kind == .const
                    ? NamingPolicy.fieldName(sourceName)
                    : NamingPolicy.typeName(sourceName)
                guard names.insert(generatedName).inserted else {
                    throw CodegenError.malformedDefinition(
                        "\(scope) contains multiple declarations named '\(generatedName)' after Swift name conversion"
                    )
                }
            }
            if let nested = definition.nested {
                try validateDefinitionNames(
                    nested,
                    scope: "\(scope).\(definition.name ?? "<unnamed>")"
                )
            }
        }
    }

    private func generatedNotice(schema: SchemaDescriptor) throws -> String {
        guard let source = schema.path else {
            throw CodegenError.malformedDefinition("schema missing source path")
        }
        var lines: [String] = []
        lines.append("// Code generated by bebopc-gen-swift. DO NOT EDIT.")
        lines.append("// source: \(source)")
        if let v = compilerVersion {
            if v.suffix.isEmpty {
                lines.append("// bebopc \(v.major).\(v.minor).\(v.patch)")
            } else {
                lines.append("// bebopc \(v.major).\(v.minor).\(v.patch)-\(v.suffix)")
            }
        }
        if let edition = schema.edition, edition == .edition2026 {
            lines.append("// edition 2026")
        }
        lines.append("//")
        lines.append("// This file requires the Bebop runtime library.")
        lines.append("// https://github.com/6over3/bebop")
        lines.append("//")
        lines.append("// The Bebop compiler and runtime are licensed under the Apache License,")
        lines.append("// Version 2.0. You may obtain a copy of the License at:")
        lines.append("// https://www.apache.org/licenses/LICENSE-2.0")
        lines.append("//")
        lines.append("// SPDX-License-Identifier: Apache-2.0")
        lines.append("// Copyright (c) 6OVER3 INSTITUTE")
        lines.append("// swiftlint:disable all")
        lines.append("")
        return lines.joined(separator: "\n") + "\n"
    }

    func generateDefinition(_ def: DefinitionDescriptor) throws -> [String] {
        if let fqn = def.fqn, Self.wellKnownFQNs.contains(fqn) { return [] }

        var shadowedNames = TypeMapper.shadowedNames
        if let children = def.nested {
            let nestedNames = Set(children.compactMap(\.name))
            shadowedNames.formUnion(
                nestedNames.intersection(TypeMapper.swiftPrimitiveNames)
            )
        }

        return try TypeMapper.$shadowedNames.withValue(shadowedNames) {
            var nested: [String] = []
            if let children = def.nested {
                for child in children {
                    try nested.append(contentsOf: generateDefinition(child))
                }
            }

            guard let kind = def.kind else {
                throw CodegenError.malformedDefinition("definition missing kind")
            }
            switch kind {
            case .enum: return try GenerateEnum.generate(def, options: options)
            case .struct:
                return try GenerateStruct.generate(def, nested: nested, options: options)
            case .message:
                return try GenerateMessage.generate(def, nested: nested, options: options)
            case .union:
                return try GenerateUnion.generate(def, nested: nested, options: options)
            case .const: return try GenerateConst.generate(def, options: options)
            case .service: return try GenerateService.generate(def, options: options)
            case .decorator: return []
            default:
                throw CodegenError.malformedDefinition("unknown definition kind \(kind.rawValue)")
            }
        }
    }
}

// MARK: - Codegen Helpers

func docComment(_ doc: String?) -> String {
    guard let doc, !doc.isEmpty else { return "" }
    return doc.split(separator: "\n", omittingEmptySubsequences: false)
        .map { "/// \($0)" }
        .joined(separator: "\n") + "\n"
}

func deprecatedAttribute(_ decorators: [DecoratorUsage]?) -> String? {
    guard let dep = decorators?.first(where: { $0.fqn == "deprecated" }) else {
        return nil
    }
    if let arg = dep.args?.first, arg.value.kind == .string,
       let msg = arg.value.stringValue, !msg.isEmpty
    {
        let escaped = msg.replacingOccurrences(of: "\"", with: "\\\"")
        return "@available(*, deprecated, message: \"\(escaped)\")"
    }
    return "@available(*, deprecated)"
}

func declPrefix(doc: String?, decorators: [DecoratorUsage]?) -> String {
    var prefix = docComment(doc)
    if let attr = deprecatedAttribute(decorators) {
        prefix += attr + "\n"
    }
    return prefix
}

func quoted(_ s: String) -> String {
    let escaped =
        s
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
    return "\"\(escaped)\""
}

func effectiveVisibility(for def: DefinitionDescriptor, options: GeneratorOptions) -> String {
    def.visibility == .local ? "internal " : options.visibility
}

func codingKeysDecl(_ fields: [(swiftName: String, originalName: String)]) -> String {
    let cases = fields.map { swift, original in
        swift == original ? "    case \(swift)" : "    case \(swift) = \(quoted(original))"
    }.joined(separator: "\n")
    let rawType = TypeMapper.unshadow("String")
    return "enum CodingKeys: \(rawType), CodingKey {\n\(cases)\n}"
}

func validateUniqueGeneratedNames(_ names: [String], in context: String) throws {
    var seen: Set<String> = []
    for name in names where !seen.insert(name).inserted {
        throw CodegenError.malformedDefinition(
            "\(context) contains multiple declarations named '\(name)' after Swift name conversion"
        )
    }
}

func fixedArrayEncodeLines(
    type: TypeDescriptor, container: String, value: String, depth: Int = 0
) throws -> [String] {
    guard let size = type.fixedArraySize, let elem = type.fixedArrayElement else {
        throw CodegenError.malformedType("fixed array missing size or element type")
    }
    let idx = "i\(depth)"

    if elem.kind == .fixedArray {
        let innerContainer = "c\(depth)"
        let innerLines = try fixedArrayEncodeLines(
            type: elem, container: innerContainer, value: "\(value)[\(idx)]", depth: depth + 1
        )
        return [
            "for \(idx) in 0..<\(size) {",
            "    var \(innerContainer) = \(container).nestedUnkeyedContainer()",
        ] + innerLines.map { "    " + $0 } + ["}"]
    }
    return ["for \(idx) in 0..<\(size) { try \(container).encode(\(value)[\(idx)]) }"]
}

func fixedArrayDecodeExpr(
    type: TypeDescriptor, container: String, depth: Int = 0
) throws -> String {
    guard let size = type.fixedArraySize, let elem = type.fixedArrayElement else {
        throw CodegenError.malformedType("fixed array missing size or element type")
    }
    let elemSwiftType = try TypeMapper.swiftType(for: elem)
    let fullType = "InlineArray<\(size), \(elemSwiftType)>"

    if elem.kind == .fixedArray {
        let innerContainer = "c\(depth)"
        let innerExpr = try fixedArrayDecodeExpr(
            type: elem, container: innerContainer, depth: depth + 1
        )
        return "\(fullType) { _ in var \(innerContainer) = try \(container).nestedUnkeyedContainer(); return try \(innerExpr) }"
    }
    return "\(fullType) { _ in try \(container).decode(\(elemSwiftType).self) }"
}

func fixedArrayEqualityLines(
    type: TypeDescriptor,
    lhs: String,
    rhs: String,
    depth: Int = 0
) throws -> [String] {
    guard let size = type.fixedArraySize, let element = type.fixedArrayElement else {
        throw CodegenError.malformedType("fixed array missing size or element type")
    }
    let index = "_i\(depth)"
    let left = "\(lhs)[\(index)]"
    let right = "\(rhs)[\(index)]"
    let body = if element.kind == .fixedArray {
        try fixedArrayEqualityLines(
            type: element,
            lhs: left,
            rhs: right,
            depth: depth + 1
        )
    } else {
        ["if \(left) != \(right) { return false }"]
    }
    return ["for \(index) in 0..<\(size) {"] + body.map { "    " + $0 } + ["}"]
}

func fixedArrayHashLines(
    type: TypeDescriptor,
    value: String,
    depth: Int = 0
) throws -> [String] {
    guard let size = type.fixedArraySize, let element = type.fixedArrayElement else {
        throw CodegenError.malformedType("fixed array missing size or element type")
    }
    let index = "_i\(depth)"
    let elementValue = "\(value)[\(index)]"
    let body = if element.kind == .fixedArray {
        try fixedArrayHashLines(type: element, value: elementValue, depth: depth + 1)
    } else {
        ["hasher.combine(\(elementValue))"]
    }
    return ["for \(index) in 0..<\(size) {"] + body.map { "    " + $0 } + ["}"]
}

func indent(_ text: String, _ level: Int = 1) -> String {
    let pad = String(repeating: "    ", count: level)
    return text.split(separator: "\n", omittingEmptySubsequences: false)
        .map { $0.isEmpty ? "" : pad + $0 }
        .joined(separator: "\n")
}
