// Code generated by bebopc-gen-swift. DO NOT EDIT.
// source: /Users/andrew/projects/bebop-vnext/bebop/schemas/bebop/json.bop
// bebopc 2026.0.0-alpha.4
// edition 2026
//
// This file requires the Bebop runtime library.
// https://github.com/6over3/bebop
//
// The Bebop compiler and runtime are licensed under the Apache License,
// Version 2.0. You may obtain a copy of the License at:
// https://www.apache.org/licenses/LICENSE-2.0
//
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 6OVER3 INSTITUTE
// swiftlint:disable all

// @@bebop_insertion_point(imports)

/// JSON null. Empty struct, zero bytes on wire.
public struct Null: BebopRecord, BebopReflectable {
    public init() {}

    public static func decode(from reader: inout BebopReader) throws -> Null {
        // @@bebop_insertion_point(decode_start:Null)
        // @@bebop_insertion_point(decode_end:Null)
        return Null()
    }

    public func encode(to writer: inout BebopWriter) {
        // @@bebop_insertion_point(encode_start:Null)
        // @@bebop_insertion_point(encode_end:Null)
    }

    public var encodedSize: Int { 0 }

    public struct View: Sendable {
        fileprivate let encoded: BebopView

        public init(_ bytes: [UInt8]) throws { try self.init(BebopView(bytes)) }

        public init(_ encoded: BebopView) throws {
            var reader = BebopViewReader(encoded)
            self = try Null.readView(from: &reader)
            try reader.finish()
        }

        fileprivate init(validated encoded: BebopView) {
            self.encoded = encoded
        }

        public func decoded() throws -> Null {
            try encoded.withUnsafeBytes { bytes in
                var reader = BebopReader(data: bytes)
                return try Null.decode(from: &reader)
            }
        }
    }

    public static func readView(from reader: inout BebopViewReader) throws -> View {
        let start = reader.position
        return View(validated: reader.view(from: start))
    }

    public static let bebopReflection = BebopTypeReflection(
        name: "Null",
        fqn: "bebop.Null",
        kind: .struct,
        detail: .struct(
            StructReflection(fields: [

            ])
        )
    )

    // @@bebop_insertion_point(struct_scope:Null)
}

/// Dynamic JSON value.
/// Represents any JSON value: null, boolean, number, string, array, or object.
/// Use for dynamic data when the schema is unknown at compile time.
/// ```bebop
/// message Event {
///   type(1): string;
///   payload(2): bebop.Value;  // arbitrary JSON
/// }
/// ```
public enum Value: BebopRecord, BebopReflectable, Codable {
    case unknown(discriminator: UInt8, data: [UInt8])

    /// JSON null.
    case null(Null)

    /// JSON boolean.
    case bool(Bool)

    /// JSON number. Stored as float64 (IEEE 754 double).
    /// Integers up to 2^53 are exact. Larger integers lose precision.
    case number(Number)

    /// JSON string. UTF-8 encoded.
    case string(String)

    /// JSON array. Ordered list of values.
    case list(List)

    /// JSON object. Unordered string-keyed map.
    case map(Map)

    public static func decode(from reader: inout BebopReader) throws -> Value {
        // @@bebop_insertion_point(decode_start:Value)
        let length = try reader.beginLengthPrefixedValue()
        let end = reader.position + Int(length)
        let disc = try reader.readByte()
        let result: Value
        switch disc {
        case 1:
            result = .null(try Null.decode(from: &reader))
        case 2:
            result = .bool(try Bool.decode(from: &reader))
        case 3:
            result = .number(try Number.decode(from: &reader))
        case 4:
            result = .string(try String.decode(from: &reader))
        case 5:
            result = .list(try List.decode(from: &reader))
        case 6:
            result = .map(try Map.decode(from: &reader))
        // @@bebop_insertion_point(decode_switch:Value)
        default:
            let remaining = end - reader.position
            let data = try reader.readBytes(remaining)
            result = .unknown(discriminator: disc, data: data)
        }
        guard reader.position == end else {
            throw BebopDecodingError.trailingData
        }
        // @@bebop_insertion_point(decode_end:Value)
        return result
    }

    public func encode(to writer: inout BebopWriter) {
        // @@bebop_insertion_point(encode_start:Value)
        let pos = writer.beginLengthPrefixedValue()
        switch self {
        case .null(let _v):
            writer.writeByte(1)
            _v.encode(to: &writer)
        case .bool(let _v):
            writer.writeByte(2)
            _v.encode(to: &writer)
        case .number(let _v):
            writer.writeByte(3)
            _v.encode(to: &writer)
        case .string(let _v):
            writer.writeByte(4)
            _v.encode(to: &writer)
        case .list(let _v):
            writer.writeByte(5)
            _v.encode(to: &writer)
        case .map(let _v):
            writer.writeByte(6)
            _v.encode(to: &writer)
        // @@bebop_insertion_point(encode_switch:Value)
        case .unknown(let disc, let data):
            writer.writeByte(disc)
            writer.writeBytes(data)
        }
        writer.endLengthPrefixedValue(at: pos)
        // @@bebop_insertion_point(encode_end:Value)
    }

    public var encodedSize: Int {
        switch self {
        case .null(let _v):
            return 4 + 1 + _v.encodedSize
        case .bool(let _v):
            return 4 + 1 + _v.encodedSize
        case .number(let _v):
            return 4 + 1 + _v.encodedSize
        case .string(let _v):
            return 4 + 1 + _v.encodedSize
        case .list(let _v):
            return 4 + 1 + _v.encodedSize
        case .map(let _v):
            return 4 + 1 + _v.encodedSize
        case .unknown(_, let data):
            return 4 + 1 + data.count
        }
    }

    public struct View: Sendable {
        fileprivate let encoded: BebopView

        public enum Content: Sendable {
            case unknown(discriminator: UInt8, data: BebopView)
            /// JSON null.
            case null(Null.View)
            /// JSON boolean.
            case bool(Bool.View)
            /// JSON number. Stored as float64 (IEEE 754 double).
            /// Integers up to 2^53 are exact. Larger integers lose precision.
            case number(Number.View)
            /// JSON string. UTF-8 encoded.
            case string(String.View)
            /// JSON array. Ordered list of values.
            case list(List.View)
            /// JSON object. Unordered string-keyed map.
            case map(Map.View)
        }

        public let discriminator: UInt8

        public let value: Content

        public init(_ bytes: [UInt8]) throws { try self.init(BebopView(bytes)) }

        public init(_ encoded: BebopView) throws {
            var reader = BebopViewReader(encoded)
            self = try Value.readView(from: &reader)
            try reader.finish()
        }

        fileprivate init(validated encoded: BebopView, discriminator: UInt8, value: Content) {
            self.encoded = encoded
            self.discriminator = discriminator
            self.value = value
        }

        public func decoded() throws -> Value {
            try encoded.withUnsafeBytes { bytes in
                var reader = BebopReader(data: bytes)
                return try Value.decode(from: &reader)
            }
        }
    }

    public static func readView(from reader: inout BebopViewReader) throws -> View {
        let encoded = try reader.readLengthPrefixedView()
        var body = BebopViewReader(encoded)
        _ = try body.readUInt32()
        let discriminator = try body.readByte()
        let value: View.Content
        switch discriminator {
        case 1: value = .null(try Null.readView(from: &body))
        case 2: value = .bool(try Bool.readView(from: &body))
        case 3: value = .number(try Number.readView(from: &body))
        case 4: value = .string(try String.readView(from: &body))
        case 5: value = .list(try List.readView(from: &body))
        case 6: value = .map(try Map.readView(from: &body))
        default: value = .unknown(discriminator: discriminator, data: try body.readBytesView(count: body.remaining))
        }
        try body.finish()
        return View(validated: encoded, discriminator: discriminator, value: value)
    }

    enum CodingKeys: Swift.String, CodingKey { case discriminator, value }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let disc = try container.decode(UInt8.self, forKey: .discriminator)
        switch disc {
        case 1:
            self = .null(try container.decode(Null.self, forKey: .value))
        case 2:
            self = .bool(try container.decode(Bool.self, forKey: .value))
        case 3:
            self = .number(try container.decode(Number.self, forKey: .value))
        case 4:
            self = .string(try container.decode(String.self, forKey: .value))
        case 5:
            self = .list(try container.decode(List.self, forKey: .value))
        case 6:
            self = .map(try container.decode(Map.self, forKey: .value))
        default:
            let data = try container.decode([UInt8].self, forKey: .value)
            self = .unknown(discriminator: disc, data: data)
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        switch self {
        case .null(let _v):
            try container.encode(UInt8(1), forKey: .discriminator)
            try container.encode(_v, forKey: .value)
        case .bool(let _v):
            try container.encode(UInt8(2), forKey: .discriminator)
            try container.encode(_v, forKey: .value)
        case .number(let _v):
            try container.encode(UInt8(3), forKey: .discriminator)
            try container.encode(_v, forKey: .value)
        case .string(let _v):
            try container.encode(UInt8(4), forKey: .discriminator)
            try container.encode(_v, forKey: .value)
        case .list(let _v):
            try container.encode(UInt8(5), forKey: .discriminator)
            try container.encode(_v, forKey: .value)
        case .map(let _v):
            try container.encode(UInt8(6), forKey: .discriminator)
            try container.encode(_v, forKey: .value)
        case .unknown(let disc, let data):
            try container.encode(disc, forKey: .discriminator)
            try container.encode(data, forKey: .value)
        }
    }

    public static let bebopReflection = BebopTypeReflection(
        name: "Value",
        fqn: "bebop.Value",
        kind: .union,
        detail: .union(
            UnionReflection(branches: [
                (discriminator: 1, name: "null", typeName: "Null"),
                (discriminator: 2, name: "bool", typeName: "Bool"),
                (discriminator: 3, name: "number", typeName: "Number"),
                (discriminator: 4, name: "string", typeName: "String"),
                (discriminator: 5, name: "list", typeName: "List"),
                (discriminator: 6, name: "map", typeName: "Map")
            ])
        )
    )

    /// JSON boolean.
    public final class Bool: BebopRecord, BebopReflectable, @unchecked Sendable {
        public var value: Swift.Bool?

        public init(value: Swift.Bool? = nil) {
            self.value = value
        }

        public static func == (lhs: Bool, rhs: Bool) -> Swift.Bool {
            return lhs.value == rhs.value
        }

        public func hash(into hasher: inout Hasher) {
            hasher.combine(value)
        }

        public static func decode(from reader: inout BebopReader) throws -> Bool {
            // @@bebop_insertion_point(decode_start:Bool)
            let message = try reader.readMessage()
            var value: Swift.Bool? = nil
            if let field = message.field(1) {
                var fieldReader = BebopReader(data: field)
                value = try fieldReader.readBool()
                guard fieldReader.position == field.count else {
                    throw BebopDecodingError.trailingData
                }
            }
            // @@bebop_insertion_point(decode_end:Bool)
            return Bool(value: value)
        }

        public func encode(to writer: inout BebopWriter) {
            // @@bebop_insertion_point(encode_start:Bool)
            let payloadStart = writer.beginMessage()
            var tags = InlineArray<1, UInt8> { _ in 0 }
            var offsets = InlineArray<1, UInt32> { _ in 0 }
            var fieldCount = 0
            if let _v = value {
                tags[fieldCount] = 1
                offsets[fieldCount] = UInt32(writer.position - payloadStart)
                fieldCount += 1
                writer.writeBool(_v)
            }
            writer.endMessage(payloadStart: payloadStart, tags: tags, offsets: offsets, count: fieldCount)
            // @@bebop_insertion_point(encode_end:Bool)
        }

        public var encodedSize: Int {
            var tags = InlineArray<1, UInt8> { _ in 0 }
            var fieldCount = 0
            var payloadSize = 0
            if value != nil { tags[fieldCount] = 1; fieldCount += 1; payloadSize += 1 }
            return BebopMessageLayout.encodedSize(payloadSize: payloadSize, tags: tags, count: fieldCount)
        }

        enum CodingKeys: Swift.String, CodingKey {
            case value
        }

        public final class View: Sendable {
            private let message: BebopMessageView

            public let value: Swift.Bool?

            public convenience init(_ bytes: [UInt8]) throws { try self.init(BebopView(bytes)) }

            public convenience init(_ encoded: BebopView) throws { try self.init(indexed: BebopMessageView(encoded)) }

            fileprivate init(indexed message: BebopMessageView) throws {
                self.message = message
                if let field = message.field(1) {
                    var fieldReader = BebopViewReader(field)
                    self.value = try fieldReader.readBool()
                    try fieldReader.finish()
                } else {
                    self.value = nil
                }
            }

            public func decoded() throws -> Bool {
                try message.encoded.withUnsafeBytes { bytes in
                    var reader = BebopReader(data: bytes)
                    return try Bool.decode(from: &reader)
                }
            }
        }

        public static func readView(from reader: inout BebopViewReader) throws -> View {
            try View(indexed: reader.readMessageView())
        }

        public static let bebopReflection = BebopTypeReflection(
            name: "Bool",
            fqn: "bebop.Value.Bool",
            kind: .message,
            detail: .message(
                MessageReflection(fields: [
                    BebopFieldReflection(
                        name: "value",
                        index: 1,
                        typeName: "Swift.Bool"
                    )
                ])
            )
        )

        // @@bebop_insertion_point(message_scope:Bool)
    }

    /// JSON number. Stored as float64 (IEEE 754 double).
    /// Integers up to 2^53 are exact. Larger integers lose precision.
    public final class Number: BebopRecord, BebopReflectable, @unchecked Sendable {
        public var value: Double?

        public init(value: Double? = nil) {
            self.value = value
        }

        public static func == (lhs: Number, rhs: Number) -> Swift.Bool {
            return lhs.value == rhs.value
        }

        public func hash(into hasher: inout Hasher) {
            hasher.combine(value)
        }

        public static func decode(from reader: inout BebopReader) throws -> Number {
            // @@bebop_insertion_point(decode_start:Number)
            let message = try reader.readMessage()
            var value: Double? = nil
            if let field = message.field(1) {
                var fieldReader = BebopReader(data: field)
                value = try fieldReader.readFloat64()
                guard fieldReader.position == field.count else {
                    throw BebopDecodingError.trailingData
                }
            }
            // @@bebop_insertion_point(decode_end:Number)
            return Number(value: value)
        }

        public func encode(to writer: inout BebopWriter) {
            // @@bebop_insertion_point(encode_start:Number)
            let payloadStart = writer.beginMessage()
            var tags = InlineArray<1, UInt8> { _ in 0 }
            var offsets = InlineArray<1, UInt32> { _ in 0 }
            var fieldCount = 0
            if let _v = value {
                tags[fieldCount] = 1
                offsets[fieldCount] = UInt32(writer.position - payloadStart)
                fieldCount += 1
                writer.writeFloat64(_v)
            }
            writer.endMessage(payloadStart: payloadStart, tags: tags, offsets: offsets, count: fieldCount)
            // @@bebop_insertion_point(encode_end:Number)
        }

        public var encodedSize: Int {
            var tags = InlineArray<1, UInt8> { _ in 0 }
            var fieldCount = 0
            var payloadSize = 0
            if value != nil { tags[fieldCount] = 1; fieldCount += 1; payloadSize += 8 }
            return BebopMessageLayout.encodedSize(payloadSize: payloadSize, tags: tags, count: fieldCount)
        }

        enum CodingKeys: Swift.String, CodingKey {
            case value
        }

        public final class View: Sendable {
            private let message: BebopMessageView

            public let value: Double?

            public convenience init(_ bytes: [UInt8]) throws { try self.init(BebopView(bytes)) }

            public convenience init(_ encoded: BebopView) throws { try self.init(indexed: BebopMessageView(encoded)) }

            fileprivate init(indexed message: BebopMessageView) throws {
                self.message = message
                if let field = message.field(1) {
                    var fieldReader = BebopViewReader(field)
                    self.value = try fieldReader.readFloat64()
                    try fieldReader.finish()
                } else {
                    self.value = nil
                }
            }

            public func decoded() throws -> Number {
                try message.encoded.withUnsafeBytes { bytes in
                    var reader = BebopReader(data: bytes)
                    return try Number.decode(from: &reader)
                }
            }
        }

        public static func readView(from reader: inout BebopViewReader) throws -> View {
            try View(indexed: reader.readMessageView())
        }

        public static let bebopReflection = BebopTypeReflection(
            name: "Number",
            fqn: "bebop.Value.Number",
            kind: .message,
            detail: .message(
                MessageReflection(fields: [
                    BebopFieldReflection(
                        name: "value",
                        index: 1,
                        typeName: "Double"
                    )
                ])
            )
        )

        // @@bebop_insertion_point(message_scope:Number)
    }

    /// JSON string. UTF-8 encoded.
    public final class String: BebopRecord, BebopReflectable, @unchecked Sendable {
        public var value: Swift.String?

        public init(value: Swift.String? = nil) {
            self.value = value
        }

        public static func == (lhs: String, rhs: String) -> Swift.Bool {
            return lhs.value == rhs.value
        }

        public func hash(into hasher: inout Hasher) {
            hasher.combine(value)
        }

        public static func decode(from reader: inout BebopReader) throws -> String {
            // @@bebop_insertion_point(decode_start:String)
            let message = try reader.readMessage()
            var value: Swift.String? = nil
            if let field = message.field(1) {
                var fieldReader = BebopReader(data: field)
                value = try fieldReader.readString()
                guard fieldReader.position == field.count else {
                    throw BebopDecodingError.trailingData
                }
            }
            // @@bebop_insertion_point(decode_end:String)
            return String(value: value)
        }

        public func encode(to writer: inout BebopWriter) {
            // @@bebop_insertion_point(encode_start:String)
            let payloadStart = writer.beginMessage()
            var tags = InlineArray<1, UInt8> { _ in 0 }
            var offsets = InlineArray<1, UInt32> { _ in 0 }
            var fieldCount = 0
            if let _v = value {
                tags[fieldCount] = 1
                offsets[fieldCount] = UInt32(writer.position - payloadStart)
                fieldCount += 1
                writer.writeString(_v)
            }
            writer.endMessage(payloadStart: payloadStart, tags: tags, offsets: offsets, count: fieldCount)
            // @@bebop_insertion_point(encode_end:String)
        }

        public var encodedSize: Int {
            var tags = InlineArray<1, UInt8> { _ in 0 }
            var fieldCount = 0
            var payloadSize = 0
            if let _v = value { tags[fieldCount] = 1; fieldCount += 1; payloadSize += (4 + _v.utf8.count + 1) }
            return BebopMessageLayout.encodedSize(payloadSize: payloadSize, tags: tags, count: fieldCount)
        }

        enum CodingKeys: Swift.String, CodingKey {
            case value
        }

        public final class View: Sendable {
            private let message: BebopMessageView

            public let value: BebopStringView?

            public convenience init(_ bytes: [UInt8]) throws { try self.init(BebopView(bytes)) }

            public convenience init(_ encoded: BebopView) throws { try self.init(indexed: BebopMessageView(encoded)) }

            fileprivate init(indexed message: BebopMessageView) throws {
                self.message = message
                if let field = message.field(1) {
                    var fieldReader = BebopViewReader(field)
                    self.value = try fieldReader.readStringView()
                    try fieldReader.finish()
                } else {
                    self.value = nil
                }
            }

            public func decoded() throws -> String {
                try message.encoded.withUnsafeBytes { bytes in
                    var reader = BebopReader(data: bytes)
                    return try String.decode(from: &reader)
                }
            }
        }

        public static func readView(from reader: inout BebopViewReader) throws -> View {
            try View(indexed: reader.readMessageView())
        }

        public static let bebopReflection = BebopTypeReflection(
            name: "String",
            fqn: "bebop.Value.String",
            kind: .message,
            detail: .message(
                MessageReflection(fields: [
                    BebopFieldReflection(
                        name: "value",
                        index: 1,
                        typeName: "Swift.String"
                    )
                ])
            )
        )

        // @@bebop_insertion_point(message_scope:String)
    }

    /// JSON array. Ordered list of values.
    public final class List: BebopRecord, BebopReflectable, @unchecked Sendable {
        public var values: [Value]?

        public init(values: [Value]? = nil) {
            self.values = values
        }

        public static func == (lhs: List, rhs: List) -> Swift.Bool {
            return lhs.values == rhs.values
        }

        public func hash(into hasher: inout Hasher) {
            hasher.combine(values)
        }

        public static func decode(from reader: inout BebopReader) throws -> List {
            // @@bebop_insertion_point(decode_start:List)
            let message = try reader.readMessage()
            var values: [Value]? = nil
            if let field = message.field(1) {
                var fieldReader = BebopReader(data: field)
                values = try fieldReader.readDynamicArray { _r in try Value.decode(from: &_r) }
                guard fieldReader.position == field.count else {
                    throw BebopDecodingError.trailingData
                }
            }
            // @@bebop_insertion_point(decode_end:List)
            return List(values: values)
        }

        public func encode(to writer: inout BebopWriter) {
            // @@bebop_insertion_point(encode_start:List)
            let payloadStart = writer.beginMessage()
            var tags = InlineArray<1, UInt8> { _ in 0 }
            var offsets = InlineArray<1, UInt32> { _ in 0 }
            var fieldCount = 0
            if let _v = values {
                tags[fieldCount] = 1
                offsets[fieldCount] = UInt32(writer.position - payloadStart)
                fieldCount += 1
                writer.writeDynamicArray(_v) { _w, _el in _el.encode(to: &_w) }
            }
            writer.endMessage(payloadStart: payloadStart, tags: tags, offsets: offsets, count: fieldCount)
            // @@bebop_insertion_point(encode_end:List)
        }

        public var encodedSize: Int {
            var tags = InlineArray<1, UInt8> { _ in 0 }
            var fieldCount = 0
            var payloadSize = 0
            if let _v = values { tags[fieldCount] = 1; fieldCount += 1; payloadSize += (4 + _v.reduce(0) { _acc, _el in _acc + _el.encodedSize }) }
            return BebopMessageLayout.encodedSize(payloadSize: payloadSize, tags: tags, count: fieldCount)
        }

        enum CodingKeys: Swift.String, CodingKey {
            case values
        }

        public final class View: Sendable {
            private let message: BebopMessageView

            public let values: BebopArrayView<Value.View>?

            public convenience init(_ bytes: [UInt8]) throws { try self.init(BebopView(bytes)) }

            public convenience init(_ encoded: BebopView) throws { try self.init(indexed: BebopMessageView(encoded)) }

            fileprivate init(indexed message: BebopMessageView) throws {
                self.message = message
                if let field = message.field(1) {
                    var fieldReader = BebopViewReader(field)
                    self.values = try fieldReader.readArrayView { _reader in try Value.readView(from: &_reader) }
                    try fieldReader.finish()
                } else {
                    self.values = nil
                }
            }

            public func decoded() throws -> List {
                try message.encoded.withUnsafeBytes { bytes in
                    var reader = BebopReader(data: bytes)
                    return try List.decode(from: &reader)
                }
            }
        }

        public static func readView(from reader: inout BebopViewReader) throws -> View {
            try View(indexed: reader.readMessageView())
        }

        public static let bebopReflection = BebopTypeReflection(
            name: "List",
            fqn: "bebop.Value.List",
            kind: .message,
            detail: .message(
                MessageReflection(fields: [
                    BebopFieldReflection(
                        name: "values",
                        index: 1,
                        typeName: "[Value]"
                    )
                ])
            )
        )

        // @@bebop_insertion_point(message_scope:List)
    }

    /// JSON object. Unordered string-keyed map.
    public final class Map: BebopRecord, BebopReflectable, @unchecked Sendable {
        public var fields: [Swift.String: Value]?

        public init(fields: [Swift.String: Value]? = nil) {
            self.fields = fields
        }

        public static func == (lhs: Map, rhs: Map) -> Swift.Bool {
            return lhs.fields == rhs.fields
        }

        public func hash(into hasher: inout Hasher) {
            hasher.combine(fields)
        }

        public static func decode(from reader: inout BebopReader) throws -> Map {
            // @@bebop_insertion_point(decode_start:Map)
            let message = try reader.readMessage()
            var fields: [Swift.String: Value]? = nil
            if let field = message.field(1) {
                var fieldReader = BebopReader(data: field)
                fields = try fieldReader.readDynamicMap { _r in (try _r.readString(), try Value.decode(from: &_r)) }
                guard fieldReader.position == field.count else {
                    throw BebopDecodingError.trailingData
                }
            }
            // @@bebop_insertion_point(decode_end:Map)
            return Map(fields: fields)
        }

        public func encode(to writer: inout BebopWriter) {
            // @@bebop_insertion_point(encode_start:Map)
            let payloadStart = writer.beginMessage()
            var tags = InlineArray<1, UInt8> { _ in 0 }
            var offsets = InlineArray<1, UInt32> { _ in 0 }
            var fieldCount = 0
            if let _v = fields {
                tags[fieldCount] = 1
                offsets[fieldCount] = UInt32(writer.position - payloadStart)
                fieldCount += 1
                writer.writeDynamicMap(_v) { _w, _k, _v in _w.writeString(_k)
            _v.encode(to: &_w) }
            }
            writer.endMessage(payloadStart: payloadStart, tags: tags, offsets: offsets, count: fieldCount)
            // @@bebop_insertion_point(encode_end:Map)
        }

        public var encodedSize: Int {
            var tags = InlineArray<1, UInt8> { _ in 0 }
            var fieldCount = 0
            var payloadSize = 0
            if let _v = fields { tags[fieldCount] = 1; fieldCount += 1; payloadSize += (4 + _v.reduce(0) { _acc, _kv in let (_k, _v) = _kv; return _acc + (4 + _k.utf8.count + 1) + _v.encodedSize }) }
            return BebopMessageLayout.encodedSize(payloadSize: payloadSize, tags: tags, count: fieldCount)
        }

        enum CodingKeys: Swift.String, CodingKey {
            case fields
        }

        public final class View: Sendable {
            private let message: BebopMessageView

            public let fields: BebopMapView<BebopStringView, Value.View>?

            public convenience init(_ bytes: [UInt8]) throws { try self.init(BebopView(bytes)) }

            public convenience init(_ encoded: BebopView) throws { try self.init(indexed: BebopMessageView(encoded)) }

            fileprivate init(indexed message: BebopMessageView) throws {
                self.message = message
                if let field = message.field(1) {
                    var fieldReader = BebopViewReader(field)
                    self.fields = try fieldReader.readMapView(key: { _reader in try _reader.readStringView() }, value: { _reader in try Value.readView(from: &_reader) })
                    try fieldReader.finish()
                } else {
                    self.fields = nil
                }
            }

            public func decoded() throws -> Map {
                try message.encoded.withUnsafeBytes { bytes in
                    var reader = BebopReader(data: bytes)
                    return try Map.decode(from: &reader)
                }
            }
        }

        public static func readView(from reader: inout BebopViewReader) throws -> View {
            try View(indexed: reader.readMessageView())
        }

        public static let bebopReflection = BebopTypeReflection(
            name: "Map",
            fqn: "bebop.Value.Map",
            kind: .message,
            detail: .message(
                MessageReflection(fields: [
                    BebopFieldReflection(
                        name: "fields",
                        index: 1,
                        typeName: "[Swift.String: Value]"
                    )
                ])
            )
        )

        // @@bebop_insertion_point(message_scope:Map)
    }

    // @@bebop_insertion_point(union_scope:Value)
}

/// JSON object. Unordered map of string keys to dynamic values.
/// Equivalent to `Value.Map` but as a standalone type. Use when you know
/// the value is an object (not null, bool, number, string, or list).
/// ```bebop
/// message Request {
///   headers(1): bebop.Object;  // {"Content-Type": "application/json", ...}
/// }
/// ```
public final class Object: BebopRecord, BebopReflectable, @unchecked Sendable {
    public var fields: [String: Value]?

    public init(fields: [String: Value]? = nil) {
        self.fields = fields
    }

    public static func == (lhs: Object, rhs: Object) -> Bool {
        return lhs.fields == rhs.fields
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(fields)
    }

    public static func decode(from reader: inout BebopReader) throws -> Object {
        // @@bebop_insertion_point(decode_start:Object)
        let message = try reader.readMessage()
        var fields: [String: Value]? = nil
        if let field = message.field(1) {
            var fieldReader = BebopReader(data: field)
            fields = try fieldReader.readDynamicMap { _r in (try _r.readString(), try Value.decode(from: &_r)) }
            guard fieldReader.position == field.count else {
                throw BebopDecodingError.trailingData
            }
        }
        // @@bebop_insertion_point(decode_end:Object)
        return Object(fields: fields)
    }

    public func encode(to writer: inout BebopWriter) {
        // @@bebop_insertion_point(encode_start:Object)
        let payloadStart = writer.beginMessage()
        var tags = InlineArray<1, UInt8> { _ in 0 }
        var offsets = InlineArray<1, UInt32> { _ in 0 }
        var fieldCount = 0
        if let _v = fields {
            tags[fieldCount] = 1
            offsets[fieldCount] = UInt32(writer.position - payloadStart)
            fieldCount += 1
            writer.writeDynamicMap(_v) { _w, _k, _v in _w.writeString(_k)
        _v.encode(to: &_w) }
        }
        writer.endMessage(payloadStart: payloadStart, tags: tags, offsets: offsets, count: fieldCount)
        // @@bebop_insertion_point(encode_end:Object)
    }

    public var encodedSize: Int {
        var tags = InlineArray<1, UInt8> { _ in 0 }
        var fieldCount = 0
        var payloadSize = 0
        if let _v = fields { tags[fieldCount] = 1; fieldCount += 1; payloadSize += (4 + _v.reduce(0) { _acc, _kv in let (_k, _v) = _kv; return _acc + (4 + _k.utf8.count + 1) + _v.encodedSize }) }
        return BebopMessageLayout.encodedSize(payloadSize: payloadSize, tags: tags, count: fieldCount)
    }

    enum CodingKeys: String, CodingKey {
        case fields
    }

    public final class View: Sendable {
        private let message: BebopMessageView

        public let fields: BebopMapView<BebopStringView, Value.View>?

        public convenience init(_ bytes: [UInt8]) throws { try self.init(BebopView(bytes)) }

        public convenience init(_ encoded: BebopView) throws { try self.init(indexed: BebopMessageView(encoded)) }

        fileprivate init(indexed message: BebopMessageView) throws {
            self.message = message
            if let field = message.field(1) {
                var fieldReader = BebopViewReader(field)
                self.fields = try fieldReader.readMapView(key: { _reader in try _reader.readStringView() }, value: { _reader in try Value.readView(from: &_reader) })
                try fieldReader.finish()
            } else {
                self.fields = nil
            }
        }

        public func decoded() throws -> Object {
            try message.encoded.withUnsafeBytes { bytes in
                var reader = BebopReader(data: bytes)
                return try Object.decode(from: &reader)
            }
        }
    }

    public static func readView(from reader: inout BebopViewReader) throws -> View {
        try View(indexed: reader.readMessageView())
    }

    public static let bebopReflection = BebopTypeReflection(
        name: "Object",
        fqn: "bebop.Object",
        kind: .message,
        detail: .message(
            MessageReflection(fields: [
                BebopFieldReflection(
                    name: "fields",
                    index: 1,
                    typeName: "[String: Value]"
                )
            ])
        )
    )

    // @@bebop_insertion_point(message_scope:Object)
}

/// JSON array. Ordered list of dynamic values.
/// Equivalent to `Value.List` but as a standalone type. Use when you know
/// the value is an array.
public final class List: BebopRecord, BebopReflectable, @unchecked Sendable {
    public var values: [Value]?

    public init(values: [Value]? = nil) {
        self.values = values
    }

    public static func == (lhs: List, rhs: List) -> Bool {
        return lhs.values == rhs.values
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(values)
    }

    public static func decode(from reader: inout BebopReader) throws -> List {
        // @@bebop_insertion_point(decode_start:List)
        let message = try reader.readMessage()
        var values: [Value]? = nil
        if let field = message.field(1) {
            var fieldReader = BebopReader(data: field)
            values = try fieldReader.readDynamicArray { _r in try Value.decode(from: &_r) }
            guard fieldReader.position == field.count else {
                throw BebopDecodingError.trailingData
            }
        }
        // @@bebop_insertion_point(decode_end:List)
        return List(values: values)
    }

    public func encode(to writer: inout BebopWriter) {
        // @@bebop_insertion_point(encode_start:List)
        let payloadStart = writer.beginMessage()
        var tags = InlineArray<1, UInt8> { _ in 0 }
        var offsets = InlineArray<1, UInt32> { _ in 0 }
        var fieldCount = 0
        if let _v = values {
            tags[fieldCount] = 1
            offsets[fieldCount] = UInt32(writer.position - payloadStart)
            fieldCount += 1
            writer.writeDynamicArray(_v) { _w, _el in _el.encode(to: &_w) }
        }
        writer.endMessage(payloadStart: payloadStart, tags: tags, offsets: offsets, count: fieldCount)
        // @@bebop_insertion_point(encode_end:List)
    }

    public var encodedSize: Int {
        var tags = InlineArray<1, UInt8> { _ in 0 }
        var fieldCount = 0
        var payloadSize = 0
        if let _v = values { tags[fieldCount] = 1; fieldCount += 1; payloadSize += (4 + _v.reduce(0) { _acc, _el in _acc + _el.encodedSize }) }
        return BebopMessageLayout.encodedSize(payloadSize: payloadSize, tags: tags, count: fieldCount)
    }

    enum CodingKeys: String, CodingKey {
        case values
    }

    public final class View: Sendable {
        private let message: BebopMessageView

        public let values: BebopArrayView<Value.View>?

        public convenience init(_ bytes: [UInt8]) throws { try self.init(BebopView(bytes)) }

        public convenience init(_ encoded: BebopView) throws { try self.init(indexed: BebopMessageView(encoded)) }

        fileprivate init(indexed message: BebopMessageView) throws {
            self.message = message
            if let field = message.field(1) {
                var fieldReader = BebopViewReader(field)
                self.values = try fieldReader.readArrayView { _reader in try Value.readView(from: &_reader) }
                try fieldReader.finish()
            } else {
                self.values = nil
            }
        }

        public func decoded() throws -> List {
            try message.encoded.withUnsafeBytes { bytes in
                var reader = BebopReader(data: bytes)
                return try List.decode(from: &reader)
            }
        }
    }

    public static func readView(from reader: inout BebopViewReader) throws -> View {
        try View(indexed: reader.readMessageView())
    }

    public static let bebopReflection = BebopTypeReflection(
        name: "List",
        fqn: "bebop.List",
        kind: .message,
        detail: .message(
            MessageReflection(fields: [
                BebopFieldReflection(
                    name: "values",
                    index: 1,
                    typeName: "[Value]"
                )
            ])
        )
    )

    // @@bebop_insertion_point(message_scope:List)
}

// @@bebop_insertion_point(eof)
