// Code generated by bebopc-gen-swift. DO NOT EDIT.
// source: /Users/andrew/projects/bebop-vnext/bebop/schemas/bebop/json.bop
// bebopc 2026.0.0-alpha.3
// edition 2026
//
// This file requires the Bebop runtime library.
// https://github.com/6over3/bebop
//
// The Bebop compiler and runtime are licensed under the Apache License,
// Version 2.0. You may obtain a copy of the License at:
// https://www.apache.org/licenses/LICENSE-2.0
//
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 6OVER3 INSTITUTE
// swiftlint:disable all

// @@bebop_insertion_point(imports)

/// JSON null. Empty struct, zero bytes on wire.
public struct Null: BebopRecord, BebopReflectable {
    public init() {}

    public static func decode(from reader: inout BebopReader) throws -> Null {
        // @@bebop_insertion_point(decode_start:Null)
        // @@bebop_insertion_point(decode_end:Null)
        return Null()
    }

    public func encode(to writer: inout BebopWriter) {
        // @@bebop_insertion_point(encode_start:Null)
        // @@bebop_insertion_point(encode_end:Null)
    }

    public var encodedSize: Int { 0 }

    public struct View: BebopRecordView {
        public let encoded: BebopView

        private let _decodeLimits: BebopDecodeLimits

        public init(_ bytes: [UInt8], limits: BebopDecodeLimits = .default) throws { try self.init(BebopView(bytes), limits: limits) }

        public init(_ encoded: BebopView, limits: BebopDecodeLimits = .default) throws {
            var reader = BebopViewReader(encoded, limits: limits)
            self = try Null.readView(from: &reader)
            try reader.finish()
        }

        fileprivate init(validated encoded: BebopView, limits: BebopDecodeLimits) {
            self.encoded = encoded
            self._decodeLimits = limits
        }

        public func decoded() throws -> Null {
            try encoded.withUnsafeBytes { bytes in
                var reader = BebopReader(data: bytes, limits: _decodeLimits)
                return try Null.decode(from: &reader)
            }
        }
    }

    public static func readView(from reader: inout BebopViewReader) throws -> View {
        let start = reader.position
        return View(validated: reader.view(from: start), limits: reader.limits)
    }

    public static let bebopReflection = BebopTypeReflection(
        name: "Null",
        fqn: "bebop.Null",
        kind: .struct,
        detail: .struct(
            StructReflection(fields: [

            ])
        )
    )

    // @@bebop_insertion_point(struct_scope:Null)
}

/// Dynamic JSON value.
/// Represents any JSON value: null, boolean, number, string, array, or object.
/// Use for dynamic data when the schema is unknown at compile time.
/// ```bebop
/// message Event {
///   type(1): string;
///   payload(2): bebop.Value;  // arbitrary JSON
/// }
/// ```
public enum Value: BebopRecord, BebopReflectable, Codable {
    case unknown(discriminator: UInt8, data: [UInt8])

    /// JSON null.
    case null(Null)

    /// JSON boolean.
    case bool(Bool)

    /// JSON number. Stored as float64 (IEEE 754 double).
    /// Integers up to 2^53 are exact. Larger integers lose precision.
    case number(Number)

    /// JSON string. UTF-8 encoded.
    case string(String)

    /// JSON array. Ordered list of values.
    case list(List)

    /// JSON object. Unordered string-keyed map.
    case map(Map)

    public static func decode(from reader: inout BebopReader) throws -> Value {
        // @@bebop_insertion_point(decode_start:Value)
        let length = try reader.beginLengthPrefixedValue()
        let end = reader.position + Int(length)
        let disc = try reader.readByte()
        let result: Value
        switch disc {
        case 1:
            result = .null(try reader.readNested { nested in try Null.decode(from: &nested) })
        case 2:
            result = .bool(try reader.readNested { nested in try Bool.decode(from: &nested) })
        case 3:
            result = .number(try reader.readNested { nested in try Number.decode(from: &nested) })
        case 4:
            result = .string(try reader.readNested { nested in try String.decode(from: &nested) })
        case 5:
            result = .list(try reader.readNested { nested in try List.decode(from: &nested) })
        case 6:
            result = .map(try reader.readNested { nested in try Map.decode(from: &nested) })
        // @@bebop_insertion_point(decode_switch:Value)
        default:
            let remaining = end - reader.position
            let data = try reader.readBytes(remaining)
            result = .unknown(discriminator: disc, data: data)
        }
        guard reader.position == end else {
            throw BebopDecodingError.trailingData
        }
        // @@bebop_insertion_point(decode_end:Value)
        return result
    }

    public func encode(to writer: inout BebopWriter) {
        // @@bebop_insertion_point(encode_start:Value)
        let pos = writer.beginLengthPrefixedValue()
        switch self {
        case .null(let _v):
            writer.writeByte(1)
            _v.encode(to: &writer)
        case .bool(let _v):
            writer.writeByte(2)
            _v.encode(to: &writer)
        case .number(let _v):
            writer.writeByte(3)
            _v.encode(to: &writer)
        case .string(let _v):
            writer.writeByte(4)
            _v.encode(to: &writer)
        case .list(let _v):
            writer.writeByte(5)
            _v.encode(to: &writer)
        case .map(let _v):
            writer.writeByte(6)
            _v.encode(to: &writer)
        // @@bebop_insertion_point(encode_switch:Value)
        case .unknown(let disc, let data):
            writer.writeByte(disc)
            writer.writeBytes(data)
        }
        writer.endLengthPrefixedValue(at: pos)
        // @@bebop_insertion_point(encode_end:Value)
    }

    public var encodedSize: Int {
        switch self {
        case .null(let _v):
            return 4 + 1 + _v.encodedSize
        case .bool(let _v):
            return 4 + 1 + _v.encodedSize
        case .number(let _v):
            return 4 + 1 + _v.encodedSize
        case .string(let _v):
            return 4 + 1 + _v.encodedSize
        case .list(let _v):
            return 4 + 1 + _v.encodedSize
        case .map(let _v):
            return 4 + 1 + _v.encodedSize
        case .unknown(_, let data):
            return 4 + 1 + data.count
        }
    }

    public struct View: BebopRecordView {
        public let encoded: BebopView

        private let _decodeLimits: BebopDecodeLimits

        public enum Content: Sendable {
            case unknown(discriminator: UInt8, data: BebopView)
            /// JSON null.
            case null(Null.View)
            /// JSON boolean.
            case bool(Bool.View)
            /// JSON number. Stored as float64 (IEEE 754 double).
            /// Integers up to 2^53 are exact. Larger integers lose precision.
            case number(Number.View)
            /// JSON string. UTF-8 encoded.
            case string(String.View)
            /// JSON array. Ordered list of values.
            case list(List.View)
            /// JSON object. Unordered string-keyed map.
            case map(Map.View)
        }

        public let discriminator: UInt8

        public let value: Content

        public init(_ bytes: [UInt8], limits: BebopDecodeLimits = .default) throws { try self.init(BebopView(bytes), limits: limits) }

        public init(_ encoded: BebopView, limits: BebopDecodeLimits = .default) throws {
            var reader = BebopViewReader(encoded, limits: limits)
            self = try Value.readView(from: &reader)
            try reader.finish()
        }

        fileprivate init(validated encoded: BebopView, limits: BebopDecodeLimits, discriminator: UInt8, value: Content) {
            self.encoded = encoded
            self._decodeLimits = limits
            self.discriminator = discriminator
            self.value = value
        }

        public func decoded() throws -> Value {
            try encoded.withUnsafeBytes { bytes in
                var reader = BebopReader(data: bytes, limits: _decodeLimits)
                return try Value.decode(from: &reader)
            }
        }
    }

    public static func readView(from reader: inout BebopViewReader) throws -> View {
        let result = try reader.readLengthPrefixedValue { body in
            let discriminator = try body.readByte()
            let value: View.Content
            switch discriminator {
            case 1: value = .null(try body.readNested { nested in try Null.readView(from: &nested) })
            case 2: value = .bool(try body.readNested { nested in try Bool.readView(from: &nested) })
            case 3: value = .number(try body.readNested { nested in try Number.readView(from: &nested) })
            case 4: value = .string(try body.readNested { nested in try String.readView(from: &nested) })
            case 5: value = .list(try body.readNested { nested in try List.readView(from: &nested) })
            case 6: value = .map(try body.readNested { nested in try Map.readView(from: &nested) })
            default: value = .unknown(discriminator: discriminator, data: try body.readBytesView(count: body.remaining))
            }
            return (discriminator, value)
        }
        return View(validated: result.encoded, limits: reader.limits, discriminator: result.value.0, value: result.value.1)
    }

    enum CodingKeys: Swift.String, CodingKey { case discriminator, value }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let disc = try container.decode(UInt8.self, forKey: .discriminator)
        switch disc {
        case 1:
            self = .null(try container.decode(Null.self, forKey: .value))
        case 2:
            self = .bool(try container.decode(Bool.self, forKey: .value))
        case 3:
            self = .number(try container.decode(Number.self, forKey: .value))
        case 4:
            self = .string(try container.decode(String.self, forKey: .value))
        case 5:
            self = .list(try container.decode(List.self, forKey: .value))
        case 6:
            self = .map(try container.decode(Map.self, forKey: .value))
        default:
            let data = try container.decode([UInt8].self, forKey: .value)
            self = .unknown(discriminator: disc, data: data)
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        switch self {
        case .null(let _v):
            try container.encode(UInt8(1), forKey: .discriminator)
            try container.encode(_v, forKey: .value)
        case .bool(let _v):
            try container.encode(UInt8(2), forKey: .discriminator)
            try container.encode(_v, forKey: .value)
        case .number(let _v):
            try container.encode(UInt8(3), forKey: .discriminator)
            try container.encode(_v, forKey: .value)
        case .string(let _v):
            try container.encode(UInt8(4), forKey: .discriminator)
            try container.encode(_v, forKey: .value)
        case .list(let _v):
            try container.encode(UInt8(5), forKey: .discriminator)
            try container.encode(_v, forKey: .value)
        case .map(let _v):
            try container.encode(UInt8(6), forKey: .discriminator)
            try container.encode(_v, forKey: .value)
        case .unknown(let disc, let data):
            try container.encode(disc, forKey: .discriminator)
            try container.encode(data, forKey: .value)
        }
    }

    public static let bebopReflection = BebopTypeReflection(
        name: "Value",
        fqn: "bebop.Value",
        kind: .union,
        detail: .union(
            UnionReflection(branches: [
                (discriminator: 1, name: "null", typeName: "Null"),
                (discriminator: 2, name: "bool", typeName: "Bool"),
                (discriminator: 3, name: "number", typeName: "Number"),
                (discriminator: 4, name: "string", typeName: "String"),
                (discriminator: 5, name: "list", typeName: "List"),
                (discriminator: 6, name: "map", typeName: "Map")
            ])
        )
    )

    /// JSON boolean.
    public struct Bool: BebopRecord, BebopReflectable {
        private final class Storage: @unchecked Sendable {
            var value: Swift.Bool?
            init(value: Swift.Bool? = nil) {
                self.value = value
            }
            func copy() -> Storage { Storage(value: value) }
        }

        private var storage: Storage

        public var value: Swift.Bool? {
            get { storage.value }
            set {
                if !isKnownUniquelyReferenced(&storage) { storage = storage.copy() }
                storage.value = newValue
            }
        }

        public init(value: Swift.Bool? = nil) { storage = Storage(value: value) }

        public static func == (lhs: Bool, rhs: Bool) -> Swift.Bool {
            if lhs.value != rhs.value { return false }
            return true
        }

        public func hash(into hasher: inout Hasher) {
            hasher.combine(value)
        }

        public static func decode(from reader: inout BebopReader) throws -> Bool {
            return try reader.readMessage { withField in
                // @@bebop_insertion_point(decode_start:Bool)
                var value: Swift.Bool? = nil
                try withField(1) { fieldReader in
                    value = try fieldReader.readBool()
                }
                // @@bebop_insertion_point(decode_end:Bool)
                return Bool(value: value)
            }
        }

        public func encode(to writer: inout BebopWriter) {
            // @@bebop_insertion_point(encode_start:Bool)
            let payloadStart = writer.beginMessage()
            var tags = InlineArray<1, UInt8> { _ in 0 }
            var offsets = InlineArray<1, UInt32> { _ in 0 }
            var fieldCount = 0
            if let _v = value {
                tags[fieldCount] = 1
                offsets[fieldCount] = UInt32(writer.position - payloadStart)
                fieldCount += 1
                writer.writeBool(_v)
            }
            writer.endMessage(payloadStart: payloadStart, tags: tags, offsets: offsets, count: fieldCount)
            // @@bebop_insertion_point(encode_end:Bool)
        }

        public var encodedSize: Int {
            var tags = InlineArray<1, UInt8> { _ in 0 }
            var fieldCount = 0
            var payloadSize = 0
            if value != nil { tags[fieldCount] = 1; fieldCount += 1; payloadSize += 1 }
            return BebopMessageLayout.encodedSize(payloadSize: payloadSize, tags: tags, count: fieldCount)
        }

        enum CodingKeys: Swift.String, CodingKey {
            case value
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(value, forKey: .value)
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.init()
            value = try container.decodeIfPresent(Swift.Bool.self, forKey: .value)
        }

        public struct View: BebopRecordView {
            private let message: BebopMessageView

            public var value: Swift.Bool? {
                get throws {
                    try message.decodeField(1) { fieldReader in
                        try fieldReader.readBool()
                    }
                }
            }

            public var encoded: BebopView { message.encoded }

            public func field(_ tag: UInt8) -> BebopView? { message.field(tag) }

            public init(_ bytes: [UInt8], limits: BebopDecodeLimits = .default) throws { try self.init(BebopView(bytes), limits: limits) }

            public init(_ encoded: BebopView, limits: BebopDecodeLimits = .default) throws { try self.init(indexed: BebopMessageView(encoded, limits: limits)) }

            fileprivate init(indexed message: BebopMessageView) {
                self.message = message
            }

            public func decoded() throws -> Bool {
                try message.encoded.withUnsafeBytes { bytes in
                    var reader = BebopReader(data: bytes, limits: message.limits)
                    return try Bool.decode(from: &reader)
                }
            }
        }

        public static func readView(from reader: inout BebopViewReader) throws -> View {
            try View(indexed: reader.readMessageView())
        }

        public static let bebopReflection = BebopTypeReflection(
            name: "Bool",
            fqn: "bebop.Value.Bool",
            kind: .message,
            detail: .message(
                MessageReflection(fields: [
                    BebopFieldReflection(
                        name: "value",
                        index: 1,
                        typeName: "Swift.Bool"
                    )
                ])
            )
        )

        // @@bebop_insertion_point(message_scope:Bool)
    }

    /// JSON number. Stored as float64 (IEEE 754 double).
    /// Integers up to 2^53 are exact. Larger integers lose precision.
    public struct Number: BebopRecord, BebopReflectable {
        private final class Storage: @unchecked Sendable {
            var value: Double?
            init(value: Double? = nil) {
                self.value = value
            }
            func copy() -> Storage { Storage(value: value) }
        }

        private var storage: Storage

        public var value: Double? {
            get { storage.value }
            set {
                if !isKnownUniquelyReferenced(&storage) { storage = storage.copy() }
                storage.value = newValue
            }
        }

        public init(value: Double? = nil) { storage = Storage(value: value) }

        public static func == (lhs: Number, rhs: Number) -> Swift.Bool {
            if lhs.value != rhs.value { return false }
            return true
        }

        public func hash(into hasher: inout Hasher) {
            hasher.combine(value)
        }

        public static func decode(from reader: inout BebopReader) throws -> Number {
            return try reader.readMessage { withField in
                // @@bebop_insertion_point(decode_start:Number)
                var value: Double? = nil
                try withField(1) { fieldReader in
                    value = try fieldReader.readFloat64()
                }
                // @@bebop_insertion_point(decode_end:Number)
                return Number(value: value)
            }
        }

        public func encode(to writer: inout BebopWriter) {
            // @@bebop_insertion_point(encode_start:Number)
            let payloadStart = writer.beginMessage()
            var tags = InlineArray<1, UInt8> { _ in 0 }
            var offsets = InlineArray<1, UInt32> { _ in 0 }
            var fieldCount = 0
            if let _v = value {
                tags[fieldCount] = 1
                offsets[fieldCount] = UInt32(writer.position - payloadStart)
                fieldCount += 1
                writer.writeFloat64(_v)
            }
            writer.endMessage(payloadStart: payloadStart, tags: tags, offsets: offsets, count: fieldCount)
            // @@bebop_insertion_point(encode_end:Number)
        }

        public var encodedSize: Int {
            var tags = InlineArray<1, UInt8> { _ in 0 }
            var fieldCount = 0
            var payloadSize = 0
            if value != nil { tags[fieldCount] = 1; fieldCount += 1; payloadSize += 8 }
            return BebopMessageLayout.encodedSize(payloadSize: payloadSize, tags: tags, count: fieldCount)
        }

        enum CodingKeys: Swift.String, CodingKey {
            case value
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(value, forKey: .value)
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.init()
            value = try container.decodeIfPresent(Double.self, forKey: .value)
        }

        public struct View: BebopRecordView {
            private let message: BebopMessageView

            public var value: Double? {
                get throws {
                    try message.decodeField(1) { fieldReader in
                        try fieldReader.readFloat64()
                    }
                }
            }

            public var encoded: BebopView { message.encoded }

            public func field(_ tag: UInt8) -> BebopView? { message.field(tag) }

            public init(_ bytes: [UInt8], limits: BebopDecodeLimits = .default) throws { try self.init(BebopView(bytes), limits: limits) }

            public init(_ encoded: BebopView, limits: BebopDecodeLimits = .default) throws { try self.init(indexed: BebopMessageView(encoded, limits: limits)) }

            fileprivate init(indexed message: BebopMessageView) {
                self.message = message
            }

            public func decoded() throws -> Number {
                try message.encoded.withUnsafeBytes { bytes in
                    var reader = BebopReader(data: bytes, limits: message.limits)
                    return try Number.decode(from: &reader)
                }
            }
        }

        public static func readView(from reader: inout BebopViewReader) throws -> View {
            try View(indexed: reader.readMessageView())
        }

        public static let bebopReflection = BebopTypeReflection(
            name: "Number",
            fqn: "bebop.Value.Number",
            kind: .message,
            detail: .message(
                MessageReflection(fields: [
                    BebopFieldReflection(
                        name: "value",
                        index: 1,
                        typeName: "Double"
                    )
                ])
            )
        )

        // @@bebop_insertion_point(message_scope:Number)
    }

    /// JSON string. UTF-8 encoded.
    public struct String: BebopRecord, BebopReflectable {
        private final class Storage: @unchecked Sendable {
            var value: Swift.String?
            init(value: Swift.String? = nil) {
                self.value = value
            }
            func copy() -> Storage { Storage(value: value) }
        }

        private var storage: Storage

        public var value: Swift.String? {
            get { storage.value }
            set {
                if !isKnownUniquelyReferenced(&storage) { storage = storage.copy() }
                storage.value = newValue
            }
        }

        public init(value: Swift.String? = nil) { storage = Storage(value: value) }

        public static func == (lhs: String, rhs: String) -> Swift.Bool {
            if lhs.value != rhs.value { return false }
            return true
        }

        public func hash(into hasher: inout Hasher) {
            hasher.combine(value)
        }

        public static func decode(from reader: inout BebopReader) throws -> String {
            return try reader.readMessage { withField in
                // @@bebop_insertion_point(decode_start:String)
                var value: Swift.String? = nil
                try withField(1) { fieldReader in
                    value = try fieldReader.readString()
                }
                // @@bebop_insertion_point(decode_end:String)
                return String(value: value)
            }
        }

        public func encode(to writer: inout BebopWriter) {
            // @@bebop_insertion_point(encode_start:String)
            let payloadStart = writer.beginMessage()
            var tags = InlineArray<1, UInt8> { _ in 0 }
            var offsets = InlineArray<1, UInt32> { _ in 0 }
            var fieldCount = 0
            if let _v = value {
                tags[fieldCount] = 1
                offsets[fieldCount] = UInt32(writer.position - payloadStart)
                fieldCount += 1
                writer.writeString(_v)
            }
            writer.endMessage(payloadStart: payloadStart, tags: tags, offsets: offsets, count: fieldCount)
            // @@bebop_insertion_point(encode_end:String)
        }

        public var encodedSize: Int {
            var tags = InlineArray<1, UInt8> { _ in 0 }
            var fieldCount = 0
            var payloadSize = 0
            if let _v = value { tags[fieldCount] = 1; fieldCount += 1; payloadSize += (4 + _v.utf8.count + 1) }
            return BebopMessageLayout.encodedSize(payloadSize: payloadSize, tags: tags, count: fieldCount)
        }

        enum CodingKeys: Swift.String, CodingKey {
            case value
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(value, forKey: .value)
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.init()
            value = try container.decodeIfPresent(Swift.String.self, forKey: .value)
        }

        public struct View: BebopRecordView {
            private let message: BebopMessageView

            public var value: BebopStringView? {
                get throws {
                    try message.decodeField(1) { fieldReader in
                        try fieldReader.readStringView()
                    }
                }
            }

            public var encoded: BebopView { message.encoded }

            public func field(_ tag: UInt8) -> BebopView? { message.field(tag) }

            public init(_ bytes: [UInt8], limits: BebopDecodeLimits = .default) throws { try self.init(BebopView(bytes), limits: limits) }

            public init(_ encoded: BebopView, limits: BebopDecodeLimits = .default) throws { try self.init(indexed: BebopMessageView(encoded, limits: limits)) }

            fileprivate init(indexed message: BebopMessageView) {
                self.message = message
            }

            public func decoded() throws -> String {
                try message.encoded.withUnsafeBytes { bytes in
                    var reader = BebopReader(data: bytes, limits: message.limits)
                    return try String.decode(from: &reader)
                }
            }
        }

        public static func readView(from reader: inout BebopViewReader) throws -> View {
            try View(indexed: reader.readMessageView())
        }

        public static let bebopReflection = BebopTypeReflection(
            name: "String",
            fqn: "bebop.Value.String",
            kind: .message,
            detail: .message(
                MessageReflection(fields: [
                    BebopFieldReflection(
                        name: "value",
                        index: 1,
                        typeName: "Swift.String"
                    )
                ])
            )
        )

        // @@bebop_insertion_point(message_scope:String)
    }

    /// JSON array. Ordered list of values.
    public struct List: BebopRecord, BebopReflectable {
        private final class Storage: @unchecked Sendable {
            var values: [Value]?
            init(values: [Value]? = nil) {
                self.values = values
            }
            func copy() -> Storage { Storage(values: values) }
        }

        private var storage: Storage

        public var values: [Value]? {
            get { storage.values }
            set {
                if !isKnownUniquelyReferenced(&storage) { storage = storage.copy() }
                storage.values = newValue
            }
        }

        public init(values: [Value]? = nil) { storage = Storage(values: values) }

        public static func == (lhs: List, rhs: List) -> Swift.Bool {
            if lhs.values != rhs.values { return false }
            return true
        }

        public func hash(into hasher: inout Hasher) {
            hasher.combine(values)
        }

        public static func decode(from reader: inout BebopReader) throws -> List {
            return try reader.readMessage { withField in
                // @@bebop_insertion_point(decode_start:List)
                var values: [Value]? = nil
                try withField(1) { fieldReader in
                    values = try fieldReader.readDynamicArray { _elementReader0 in
                        try _elementReader0.readNested { _nestedReader1 in try Value.decode(from: &_nestedReader1) }
                    }
                }
                // @@bebop_insertion_point(decode_end:List)
                return List(values: values)
            }
        }

        public func encode(to writer: inout BebopWriter) {
            // @@bebop_insertion_point(encode_start:List)
            let payloadStart = writer.beginMessage()
            var tags = InlineArray<1, UInt8> { _ in 0 }
            var offsets = InlineArray<1, UInt32> { _ in 0 }
            var fieldCount = 0
            if let _v = values {
                tags[fieldCount] = 1
                offsets[fieldCount] = UInt32(writer.position - payloadStart)
                fieldCount += 1
                writer.writeDynamicArray(_v) { _elementWriter0, _element0 in
                    _element0.encode(to: &_elementWriter0)
                }
            }
            writer.endMessage(payloadStart: payloadStart, tags: tags, offsets: offsets, count: fieldCount)
            // @@bebop_insertion_point(encode_end:List)
        }

        public var encodedSize: Int {
            var tags = InlineArray<1, UInt8> { _ in 0 }
            var fieldCount = 0
            var payloadSize = 0
            if let _v = values { tags[fieldCount] = 1; fieldCount += 1; payloadSize += (4 + _v.reduce(0) { _acc, _el in _acc + _el.encodedSize }) }
            return BebopMessageLayout.encodedSize(payloadSize: payloadSize, tags: tags, count: fieldCount)
        }

        enum CodingKeys: Swift.String, CodingKey {
            case values
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(values, forKey: .values)
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.init()
            values = try container.decodeIfPresent([Value].self, forKey: .values)
        }

        public struct View: BebopRecordView {
            private let message: BebopMessageView

            public var values: BebopArrayView<Value.View>? {
                get throws {
                    try message.decodeField(1) { fieldReader in
                        try fieldReader.readArrayView { _elementReader0 in
                            try _elementReader0.readNested { _nestedReader1 in try Value.readView(from: &_nestedReader1) }
                        }
                    }
                }
            }

            public var encoded: BebopView { message.encoded }

            public func field(_ tag: UInt8) -> BebopView? { message.field(tag) }

            public init(_ bytes: [UInt8], limits: BebopDecodeLimits = .default) throws { try self.init(BebopView(bytes), limits: limits) }

            public init(_ encoded: BebopView, limits: BebopDecodeLimits = .default) throws { try self.init(indexed: BebopMessageView(encoded, limits: limits)) }

            fileprivate init(indexed message: BebopMessageView) {
                self.message = message
            }

            public func decoded() throws -> List {
                try message.encoded.withUnsafeBytes { bytes in
                    var reader = BebopReader(data: bytes, limits: message.limits)
                    return try List.decode(from: &reader)
                }
            }
        }

        public static func readView(from reader: inout BebopViewReader) throws -> View {
            try View(indexed: reader.readMessageView())
        }

        public static let bebopReflection = BebopTypeReflection(
            name: "List",
            fqn: "bebop.Value.List",
            kind: .message,
            detail: .message(
                MessageReflection(fields: [
                    BebopFieldReflection(
                        name: "values",
                        index: 1,
                        typeName: "[Value]"
                    )
                ])
            )
        )

        // @@bebop_insertion_point(message_scope:List)
    }

    /// JSON object. Unordered string-keyed map.
    public struct Map: BebopRecord, BebopReflectable {
        private final class Storage: @unchecked Sendable {
            var fields: [Swift.String: Value]?
            init(fields: [Swift.String: Value]? = nil) {
                self.fields = fields
            }
            func copy() -> Storage { Storage(fields: fields) }
        }

        private var storage: Storage

        public var fields: [Swift.String: Value]? {
            get { storage.fields }
            set {
                if !isKnownUniquelyReferenced(&storage) { storage = storage.copy() }
                storage.fields = newValue
            }
        }

        public init(fields: [Swift.String: Value]? = nil) { storage = Storage(fields: fields) }

        public static func == (lhs: Map, rhs: Map) -> Swift.Bool {
            if lhs.fields != rhs.fields { return false }
            return true
        }

        public func hash(into hasher: inout Hasher) {
            hasher.combine(fields)
        }

        public static func decode(from reader: inout BebopReader) throws -> Map {
            return try reader.readMessage { withField in
                // @@bebop_insertion_point(decode_start:Map)
                var fields: [Swift.String: Value]? = nil
                try withField(1) { fieldReader in
                    fields = try fieldReader.readDynamicMap { _entryReader0 in
                        let key = try _entryReader0.readString()
                        let value = try _entryReader0.readNested { _nestedReader1 in try Value.decode(from: &_nestedReader1) }
                        return (key, value)
                    }
                }
                // @@bebop_insertion_point(decode_end:Map)
                return Map(fields: fields)
            }
        }

        public func encode(to writer: inout BebopWriter) {
            // @@bebop_insertion_point(encode_start:Map)
            let payloadStart = writer.beginMessage()
            var tags = InlineArray<1, UInt8> { _ in 0 }
            var offsets = InlineArray<1, UInt32> { _ in 0 }
            var fieldCount = 0
            if let _v = fields {
                tags[fieldCount] = 1
                offsets[fieldCount] = UInt32(writer.position - payloadStart)
                fieldCount += 1
                writer.writeDynamicMap(_v) { _entryWriter0, _key0, _value0 in
                    _entryWriter0.writeString(_key0)
                    _value0.encode(to: &_entryWriter0)
                }
            }
            writer.endMessage(payloadStart: payloadStart, tags: tags, offsets: offsets, count: fieldCount)
            // @@bebop_insertion_point(encode_end:Map)
        }

        public var encodedSize: Int {
            var tags = InlineArray<1, UInt8> { _ in 0 }
            var fieldCount = 0
            var payloadSize = 0
            if let _v = fields { tags[fieldCount] = 1; fieldCount += 1; payloadSize += (4 + _v.reduce(0) { _acc, _kv in let (_k, _v) = _kv; return _acc + (4 + _k.utf8.count + 1) + _v.encodedSize }) }
            return BebopMessageLayout.encodedSize(payloadSize: payloadSize, tags: tags, count: fieldCount)
        }

        enum CodingKeys: Swift.String, CodingKey {
            case fields
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(fields, forKey: .fields)
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.init()
            fields = try container.decodeIfPresent([Swift.String: Value].self, forKey: .fields)
        }

        public struct View: BebopRecordView {
            private let message: BebopMessageView

            public var fields: BebopMapView<BebopStringView, Value.View>? {
                get throws {
                    try message.decodeField(1) { fieldReader in
                        try fieldReader.readMapView(
                            key: { _keyReader0 in
                                try _keyReader0.readStringView()
                            },
                            value: { _valueReader0 in
                                try _valueReader0.readNested { _nestedReader1 in try Value.readView(from: &_nestedReader1) }
                            }
                        )
                    }
                }
            }

            public var encoded: BebopView { message.encoded }

            public func field(_ tag: UInt8) -> BebopView? { message.field(tag) }

            public init(_ bytes: [UInt8], limits: BebopDecodeLimits = .default) throws { try self.init(BebopView(bytes), limits: limits) }

            public init(_ encoded: BebopView, limits: BebopDecodeLimits = .default) throws { try self.init(indexed: BebopMessageView(encoded, limits: limits)) }

            fileprivate init(indexed message: BebopMessageView) {
                self.message = message
            }

            public func decoded() throws -> Map {
                try message.encoded.withUnsafeBytes { bytes in
                    var reader = BebopReader(data: bytes, limits: message.limits)
                    return try Map.decode(from: &reader)
                }
            }
        }

        public static func readView(from reader: inout BebopViewReader) throws -> View {
            try View(indexed: reader.readMessageView())
        }

        public static let bebopReflection = BebopTypeReflection(
            name: "Map",
            fqn: "bebop.Value.Map",
            kind: .message,
            detail: .message(
                MessageReflection(fields: [
                    BebopFieldReflection(
                        name: "fields",
                        index: 1,
                        typeName: "[Swift.String: Value]"
                    )
                ])
            )
        )

        // @@bebop_insertion_point(message_scope:Map)
    }

    // @@bebop_insertion_point(union_scope:Value)
}

/// JSON object. Unordered map of string keys to dynamic values.
/// Equivalent to `Value.Map` but as a standalone type. Use when you know
/// the value is an object (not null, bool, number, string, or list).
/// ```bebop
/// message Request {
///   headers(1): bebop.Object;  // {"Content-Type": "application/json", ...}
/// }
/// ```
public struct Object: BebopRecord, BebopReflectable {
    private final class Storage: @unchecked Sendable {
        var fields: [String: Value]?
        init(fields: [String: Value]? = nil) {
            self.fields = fields
        }
        func copy() -> Storage { Storage(fields: fields) }
    }

    private var storage: Storage

    public var fields: [String: Value]? {
        get { storage.fields }
        set {
            if !isKnownUniquelyReferenced(&storage) { storage = storage.copy() }
            storage.fields = newValue
        }
    }

    public init(fields: [String: Value]? = nil) { storage = Storage(fields: fields) }

    public static func == (lhs: Object, rhs: Object) -> Bool {
        if lhs.fields != rhs.fields { return false }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(fields)
    }

    public static func decode(from reader: inout BebopReader) throws -> Object {
        return try reader.readMessage { withField in
            // @@bebop_insertion_point(decode_start:Object)
            var fields: [String: Value]? = nil
            try withField(1) { fieldReader in
                fields = try fieldReader.readDynamicMap { _entryReader0 in
                    let key = try _entryReader0.readString()
                    let value = try _entryReader0.readNested { _nestedReader1 in try Value.decode(from: &_nestedReader1) }
                    return (key, value)
                }
            }
            // @@bebop_insertion_point(decode_end:Object)
            return Object(fields: fields)
        }
    }

    public func encode(to writer: inout BebopWriter) {
        // @@bebop_insertion_point(encode_start:Object)
        let payloadStart = writer.beginMessage()
        var tags = InlineArray<1, UInt8> { _ in 0 }
        var offsets = InlineArray<1, UInt32> { _ in 0 }
        var fieldCount = 0
        if let _v = fields {
            tags[fieldCount] = 1
            offsets[fieldCount] = UInt32(writer.position - payloadStart)
            fieldCount += 1
            writer.writeDynamicMap(_v) { _entryWriter0, _key0, _value0 in
                _entryWriter0.writeString(_key0)
                _value0.encode(to: &_entryWriter0)
            }
        }
        writer.endMessage(payloadStart: payloadStart, tags: tags, offsets: offsets, count: fieldCount)
        // @@bebop_insertion_point(encode_end:Object)
    }

    public var encodedSize: Int {
        var tags = InlineArray<1, UInt8> { _ in 0 }
        var fieldCount = 0
        var payloadSize = 0
        if let _v = fields { tags[fieldCount] = 1; fieldCount += 1; payloadSize += (4 + _v.reduce(0) { _acc, _kv in let (_k, _v) = _kv; return _acc + (4 + _k.utf8.count + 1) + _v.encodedSize }) }
        return BebopMessageLayout.encodedSize(payloadSize: payloadSize, tags: tags, count: fieldCount)
    }

    enum CodingKeys: String, CodingKey {
        case fields
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(fields, forKey: .fields)
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.init()
        fields = try container.decodeIfPresent([String: Value].self, forKey: .fields)
    }

    public struct View: BebopRecordView {
        private let message: BebopMessageView

        public var fields: BebopMapView<BebopStringView, Value.View>? {
            get throws {
                try message.decodeField(1) { fieldReader in
                    try fieldReader.readMapView(
                        key: { _keyReader0 in
                            try _keyReader0.readStringView()
                        },
                        value: { _valueReader0 in
                            try _valueReader0.readNested { _nestedReader1 in try Value.readView(from: &_nestedReader1) }
                        }
                    )
                }
            }
        }

        public var encoded: BebopView { message.encoded }

        public func field(_ tag: UInt8) -> BebopView? { message.field(tag) }

        public init(_ bytes: [UInt8], limits: BebopDecodeLimits = .default) throws { try self.init(BebopView(bytes), limits: limits) }

        public init(_ encoded: BebopView, limits: BebopDecodeLimits = .default) throws { try self.init(indexed: BebopMessageView(encoded, limits: limits)) }

        fileprivate init(indexed message: BebopMessageView) {
            self.message = message
        }

        public func decoded() throws -> Object {
            try message.encoded.withUnsafeBytes { bytes in
                var reader = BebopReader(data: bytes, limits: message.limits)
                return try Object.decode(from: &reader)
            }
        }
    }

    public static func readView(from reader: inout BebopViewReader) throws -> View {
        try View(indexed: reader.readMessageView())
    }

    public static let bebopReflection = BebopTypeReflection(
        name: "Object",
        fqn: "bebop.Object",
        kind: .message,
        detail: .message(
            MessageReflection(fields: [
                BebopFieldReflection(
                    name: "fields",
                    index: 1,
                    typeName: "[String: Value]"
                )
            ])
        )
    )

    // @@bebop_insertion_point(message_scope:Object)
}

/// JSON array. Ordered list of dynamic values.
/// Equivalent to `Value.List` but as a standalone type. Use when you know
/// the value is an array.
public struct List: BebopRecord, BebopReflectable {
    private final class Storage: @unchecked Sendable {
        var values: [Value]?
        init(values: [Value]? = nil) {
            self.values = values
        }
        func copy() -> Storage { Storage(values: values) }
    }

    private var storage: Storage

    public var values: [Value]? {
        get { storage.values }
        set {
            if !isKnownUniquelyReferenced(&storage) { storage = storage.copy() }
            storage.values = newValue
        }
    }

    public init(values: [Value]? = nil) { storage = Storage(values: values) }

    public static func == (lhs: List, rhs: List) -> Bool {
        if lhs.values != rhs.values { return false }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(values)
    }

    public static func decode(from reader: inout BebopReader) throws -> List {
        return try reader.readMessage { withField in
            // @@bebop_insertion_point(decode_start:List)
            var values: [Value]? = nil
            try withField(1) { fieldReader in
                values = try fieldReader.readDynamicArray { _elementReader0 in
                    try _elementReader0.readNested { _nestedReader1 in try Value.decode(from: &_nestedReader1) }
                }
            }
            // @@bebop_insertion_point(decode_end:List)
            return List(values: values)
        }
    }

    public func encode(to writer: inout BebopWriter) {
        // @@bebop_insertion_point(encode_start:List)
        let payloadStart = writer.beginMessage()
        var tags = InlineArray<1, UInt8> { _ in 0 }
        var offsets = InlineArray<1, UInt32> { _ in 0 }
        var fieldCount = 0
        if let _v = values {
            tags[fieldCount] = 1
            offsets[fieldCount] = UInt32(writer.position - payloadStart)
            fieldCount += 1
            writer.writeDynamicArray(_v) { _elementWriter0, _element0 in
                _element0.encode(to: &_elementWriter0)
            }
        }
        writer.endMessage(payloadStart: payloadStart, tags: tags, offsets: offsets, count: fieldCount)
        // @@bebop_insertion_point(encode_end:List)
    }

    public var encodedSize: Int {
        var tags = InlineArray<1, UInt8> { _ in 0 }
        var fieldCount = 0
        var payloadSize = 0
        if let _v = values { tags[fieldCount] = 1; fieldCount += 1; payloadSize += (4 + _v.reduce(0) { _acc, _el in _acc + _el.encodedSize }) }
        return BebopMessageLayout.encodedSize(payloadSize: payloadSize, tags: tags, count: fieldCount)
    }

    enum CodingKeys: String, CodingKey {
        case values
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(values, forKey: .values)
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.init()
        values = try container.decodeIfPresent([Value].self, forKey: .values)
    }

    public struct View: BebopRecordView {
        private let message: BebopMessageView

        public var values: BebopArrayView<Value.View>? {
            get throws {
                try message.decodeField(1) { fieldReader in
                    try fieldReader.readArrayView { _elementReader0 in
                        try _elementReader0.readNested { _nestedReader1 in try Value.readView(from: &_nestedReader1) }
                    }
                }
            }
        }

        public var encoded: BebopView { message.encoded }

        public func field(_ tag: UInt8) -> BebopView? { message.field(tag) }

        public init(_ bytes: [UInt8], limits: BebopDecodeLimits = .default) throws { try self.init(BebopView(bytes), limits: limits) }

        public init(_ encoded: BebopView, limits: BebopDecodeLimits = .default) throws { try self.init(indexed: BebopMessageView(encoded, limits: limits)) }

        fileprivate init(indexed message: BebopMessageView) {
            self.message = message
        }

        public func decoded() throws -> List {
            try message.encoded.withUnsafeBytes { bytes in
                var reader = BebopReader(data: bytes, limits: message.limits)
                return try List.decode(from: &reader)
            }
        }
    }

    public static func readView(from reader: inout BebopViewReader) throws -> View {
        try View(indexed: reader.readMessageView())
    }

    public static let bebopReflection = BebopTypeReflection(
        name: "List",
        fqn: "bebop.List",
        kind: .message,
        detail: .message(
            MessageReflection(fields: [
                BebopFieldReflection(
                    name: "values",
                    index: 1,
                    typeName: "[Value]"
                )
            ])
        )
    )

    // @@bebop_insertion_point(message_scope:List)
}

// @@bebop_insertion_point(eof)
