// Code generated by bebopc-gen-typescript. DO NOT EDIT.
// source: bebop/schemas/bebop/json.bop
// bebopc 2026.0.0-alpha.3

import { decode, encode } from "./codec.js";
import type { BebopGeneratedCodec } from "./reflection.js";
import { utf8ByteLength, type BebopReader, type BebopReaderOptions, type BebopWriter } from "./wire.js";


export type Null = {
};

export const Null = {
  encode(value: Null): Uint8Array {
    return encode(Null, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): Null {
    return decode(Null, bytes, options);
  },
  readFrom(_reader: BebopReader): Null {
    return {};
  },
  writeInto(_writer: BebopWriter, _value: Null): void {
  },
  encodedSize(_value: Null): number {
    return 0;
  },
  reflection: {
    name: "Null",
    fqn: "bebop.Null",
    kind: "struct",
    detail: {
      fields: [
      ],
    },
  },
} satisfies BebopGeneratedCodec<Null>;

export type Value_Bool = {
  readonly value?: boolean | undefined;
};

export const Value_Bool = {
  encode(value: Value_Bool): Uint8Array {
    return encode(Value_Bool, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): Value_Bool {
    return decode(Value_Bool, bytes, options);
  },
  readFrom(reader: BebopReader): Value_Bool {
    const end = reader.readMessageEnd();
    let valueValue: boolean | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: valueValue = reader.readBool(); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      value: valueValue,
    };
  },
  writeInto(writer: BebopWriter, value: Value_Bool): void {
    const pos = writer.reserveMessageLength();
    if (value.value !== undefined) {
      writer.writeTag(1);
      writer.writeBool(value.value);
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: Value_Bool): number {
    let size = 5;
    if (value.value !== undefined) {
      size += 1;
      size += 1;
    }
    return size;
  },
  reflection: {
    name: "Bool",
    fqn: "bebop.Value.Bool",
    kind: "message",
    detail: {
      fields: [
        { name: "value", index: 1, typeName: "boolean" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<Value_Bool>;

export type Value_Number = {
  readonly value?: number | undefined;
};

export const Value_Number = {
  encode(value: Value_Number): Uint8Array {
    return encode(Value_Number, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): Value_Number {
    return decode(Value_Number, bytes, options);
  },
  readFrom(reader: BebopReader): Value_Number {
    const end = reader.readMessageEnd();
    let valueValue: number | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: valueValue = reader.readFloat64(); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      value: valueValue,
    };
  },
  writeInto(writer: BebopWriter, value: Value_Number): void {
    const pos = writer.reserveMessageLength();
    if (value.value !== undefined) {
      writer.writeTag(1);
      writer.writeFloat64(value.value);
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: Value_Number): number {
    let size = 5;
    if (value.value !== undefined) {
      size += 1;
      size += 8;
    }
    return size;
  },
  reflection: {
    name: "Number",
    fqn: "bebop.Value.Number",
    kind: "message",
    detail: {
      fields: [
        { name: "value", index: 1, typeName: "number" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<Value_Number>;

export type Value_String = {
  readonly value?: string | undefined;
};

export const Value_String = {
  encode(value: Value_String): Uint8Array {
    return encode(Value_String, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): Value_String {
    return decode(Value_String, bytes, options);
  },
  readFrom(reader: BebopReader): Value_String {
    const end = reader.readMessageEnd();
    let valueValue: string | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: valueValue = reader.readString(); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      value: valueValue,
    };
  },
  writeInto(writer: BebopWriter, value: Value_String): void {
    const pos = writer.reserveMessageLength();
    if (value.value !== undefined) {
      writer.writeTag(1);
      writer.writeString(value.value);
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: Value_String): number {
    let size = 5;
    if (value.value !== undefined) {
      size += 1;
      size += 5 + utf8ByteLength(value.value);
    }
    return size;
  },
  reflection: {
    name: "String",
    fqn: "bebop.Value.String",
    kind: "message",
    detail: {
      fields: [
        { name: "value", index: 1, typeName: "string" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<Value_String>;

export type Value_List = {
  readonly values?: readonly Value[] | undefined;
};

export const Value_List = {
  encode(value: Value_List): Uint8Array {
    return encode(Value_List, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): Value_List {
    return decode(Value_List, bytes, options);
  },
  readFrom(reader: BebopReader): Value_List {
    const end = reader.readMessageEnd();
    let valuesValue: readonly Value[] | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: valuesValue = reader.readDynamicArray((_r) => Value.readFrom(_r)); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      values: valuesValue,
    };
  },
  writeInto(writer: BebopWriter, value: Value_List): void {
    const pos = writer.reserveMessageLength();
    if (value.values !== undefined) {
      writer.writeTag(1);
      writer.writeDynamicArray(value.values, (_w, _v) => {
        Value.writeInto(_w, _v);
      });
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: Value_List): number {
    let size = 5;
    if (value.values !== undefined) {
      size += 1;
      size += 4;
      for (let _i0 = 0; _i0 < value.values.length; _i0++) {
        const _item1 = value.values[_i0]!;
        size += Value.encodedSize(_item1);
      }
    }
    return size;
  },
  reflection: {
    name: "List",
    fqn: "bebop.Value.List",
    kind: "message",
    detail: {
      fields: [
        { name: "values", index: 1, typeName: "readonly Value[]" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<Value_List>;

export type Value_Map = {
  readonly fields?: ReadonlyMap<string, Value> | undefined;
};

export const Value_Map = {
  encode(value: Value_Map): Uint8Array {
    return encode(Value_Map, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): Value_Map {
    return decode(Value_Map, bytes, options);
  },
  readFrom(reader: BebopReader): Value_Map {
    const end = reader.readMessageEnd();
    let fieldsValue: ReadonlyMap<string, Value> | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: fieldsValue = reader.readDynamicMap((_r) => _r.readString(), (_r) => Value.readFrom(_r)); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      fields: fieldsValue,
    };
  },
  writeInto(writer: BebopWriter, value: Value_Map): void {
    const pos = writer.reserveMessageLength();
    if (value.fields !== undefined) {
      writer.writeTag(1);
      writer.writeDynamicMap(value.fields, (_w, _k, _v) => {
        _w.writeString(_k);
        Value.writeInto(_w, _v);
      });
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: Value_Map): number {
    let size = 5;
    if (value.fields !== undefined) {
      size += 1;
      size += 4;
      for (const [_k, _v] of value.fields) {
        size += 5 + utf8ByteLength(_k);
        size += Value.encodedSize(_v);
      }
    }
    return size;
  },
  reflection: {
    name: "Map",
    fqn: "bebop.Value.Map",
    kind: "message",
    detail: {
      fields: [
        { name: "fields", index: 1, typeName: "ReadonlyMap<string, Value>" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<Value_Map>;

export type Value =
  | { readonly kind: "unknown"; readonly discriminator: number; readonly data: Uint8Array }
  | { readonly kind: "null"; readonly value: Null }
  | { readonly kind: "bool"; readonly value: Value_Bool }
  | { readonly kind: "number"; readonly value: Value_Number }
  | { readonly kind: "string"; readonly value: Value_String }
  | { readonly kind: "list"; readonly value: Value_List }
  | { readonly kind: "map"; readonly value: Value_Map };

export const Value = {
  encode(value: Value): Uint8Array {
    return encode(Value, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): Value {
    return decode(Value, bytes, options);
  },
  readFrom(reader: BebopReader): Value {
    const end = reader.readMessageEnd();
    const discriminator = reader.readByte();
    switch (discriminator) {
      case 1: return { kind: "null", value: Null.readFrom(reader) };
      case 2: return { kind: "bool", value: Value_Bool.readFrom(reader) };
      case 3: return { kind: "number", value: Value_Number.readFrom(reader) };
      case 4: return { kind: "string", value: Value_String.readFrom(reader) };
      case 5: return { kind: "list", value: Value_List.readFrom(reader) };
      case 6: return { kind: "map", value: Value_Map.readFrom(reader) };
      default: return { kind: "unknown", discriminator, data: reader.readBytes(end - reader.index) };
    }
  },
  writeInto(writer: BebopWriter, value: Value): void {
    const pos = writer.reserveMessageLength();
    switch (value.kind) {
      case "null":
        writer.writeByte(1);
        Null.writeInto(writer, value.value);
        break;
      case "bool":
        writer.writeByte(2);
        Value_Bool.writeInto(writer, value.value);
        break;
      case "number":
        writer.writeByte(3);
        Value_Number.writeInto(writer, value.value);
        break;
      case "string":
        writer.writeByte(4);
        Value_String.writeInto(writer, value.value);
        break;
      case "list":
        writer.writeByte(5);
        Value_List.writeInto(writer, value.value);
        break;
      case "map":
        writer.writeByte(6);
        Value_Map.writeInto(writer, value.value);
        break;
      case "unknown":
        writer.writeByte(value.discriminator);
        writer.writeBytes(value.data);
        break;
    }
    writer.fillMessageLength(pos);
  },
  encodedSize(value: Value): number {
    switch (value.kind) {
      case "null": return 5 + Null.encodedSize(value.value);
      case "bool": return 5 + Value_Bool.encodedSize(value.value);
      case "number": return 5 + Value_Number.encodedSize(value.value);
      case "string": return 5 + Value_String.encodedSize(value.value);
      case "list": return 5 + Value_List.encodedSize(value.value);
      case "map": return 5 + Value_Map.encodedSize(value.value);
      case "unknown": return 5 + value.data.length;
    }
  },
  reflection: {
    name: "Value",
    fqn: "bebop.Value",
    kind: "union",
    detail: {
      branches: [
        { discriminator: 1, name: "Null", typeName: "Null" },
        { discriminator: 2, name: "Bool", typeName: "Value_Bool" },
        { discriminator: 3, name: "Number", typeName: "Value_Number" },
        { discriminator: 4, name: "String", typeName: "Value_String" },
        { discriminator: 5, name: "List", typeName: "Value_List" },
        { discriminator: 6, name: "Map", typeName: "Value_Map" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<Value>;

export type Object = {
  readonly fields?: ReadonlyMap<string, Value> | undefined;
};

export const Object = {
  encode(value: Object): Uint8Array {
    return encode(Object, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): Object {
    return decode(Object, bytes, options);
  },
  readFrom(reader: BebopReader): Object {
    const end = reader.readMessageEnd();
    let fieldsValue: ReadonlyMap<string, Value> | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: fieldsValue = reader.readDynamicMap((_r) => _r.readString(), (_r) => Value.readFrom(_r)); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      fields: fieldsValue,
    };
  },
  writeInto(writer: BebopWriter, value: Object): void {
    const pos = writer.reserveMessageLength();
    if (value.fields !== undefined) {
      writer.writeTag(1);
      writer.writeDynamicMap(value.fields, (_w, _k, _v) => {
        _w.writeString(_k);
        Value.writeInto(_w, _v);
      });
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: Object): number {
    let size = 5;
    if (value.fields !== undefined) {
      size += 1;
      size += 4;
      for (const [_k, _v] of value.fields) {
        size += 5 + utf8ByteLength(_k);
        size += Value.encodedSize(_v);
      }
    }
    return size;
  },
  reflection: {
    name: "Object",
    fqn: "bebop.Object",
    kind: "message",
    detail: {
      fields: [
        { name: "fields", index: 1, typeName: "ReadonlyMap<string, Value>" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<Object>;

export type List = {
  readonly values?: readonly Value[] | undefined;
};

export const List = {
  encode(value: List): Uint8Array {
    return encode(List, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): List {
    return decode(List, bytes, options);
  },
  readFrom(reader: BebopReader): List {
    const end = reader.readMessageEnd();
    let valuesValue: readonly Value[] | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: valuesValue = reader.readDynamicArray((_r) => Value.readFrom(_r)); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      values: valuesValue,
    };
  },
  writeInto(writer: BebopWriter, value: List): void {
    const pos = writer.reserveMessageLength();
    if (value.values !== undefined) {
      writer.writeTag(1);
      writer.writeDynamicArray(value.values, (_w, _v) => {
        Value.writeInto(_w, _v);
      });
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: List): number {
    let size = 5;
    if (value.values !== undefined) {
      size += 1;
      size += 4;
      for (let _i2 = 0; _i2 < value.values.length; _i2++) {
        const _item3 = value.values[_i2]!;
        size += Value.encodedSize(_item3);
      }
    }
    return size;
  },
  reflection: {
    name: "List",
    fqn: "bebop.List",
    kind: "message",
    detail: {
      fields: [
        { name: "values", index: 1, typeName: "readonly Value[]" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<List>;

