// Code generated by bebopc-gen-typescript. DO NOT EDIT.
// source: bebop/schemas/bebop/json.bop
// bebopc 2026.0.0-alpha.3

import { BebopDefinitionKind } from "./reflection";
import type { BebopReflectableCodec } from "./reflection";
import type { BebopReader, BebopWriter } from "./wire";


export type Null = {
};

export const Null = {
  readFrom(reader: BebopReader): Null {
    return {};
  },
  writeInto(writer: BebopWriter, value: Null): void {
  },
  encodedSize(value: Null): number {
    return 0;
  },
  reflection: {
    name: "Null",
    fqn: "bebop.Null",
    kind: BebopDefinitionKind.struct,
    detail: {
      fields: [
      ],
    },
  },
} satisfies BebopReflectableCodec<Null>;

export type Value_Bool = {
  readonly value?: boolean | undefined;
};

export const Value_Bool = {
  readFrom(reader: BebopReader): Value_Bool {
    const end = reader.readMessageEnd();
    let valueValue: boolean | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: valueValue = reader.readBool(); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      value: valueValue,
    };
  },
  writeInto(writer: BebopWriter, value: Value_Bool): void {
    const pos = writer.reserveMessageLength();
    if (value.value !== undefined) {
      writer.writeTag(1);
      writer.writeBool(value.value);
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: Value_Bool): number {
    let size = 5;
    if (value.value !== undefined) {
      size += 1;
      size += 1;
    }
    return size;
  },
  reflection: {
    name: "Bool",
    fqn: "bebop.Value.Bool",
    kind: BebopDefinitionKind.message,
    detail: {
      fields: [
        { name: "value", index: 1, typeName: "boolean" },
      ],
    },
  },
} satisfies BebopReflectableCodec<Value_Bool>;

export type Value_Number = {
  readonly value?: number | undefined;
};

export const Value_Number = {
  readFrom(reader: BebopReader): Value_Number {
    const end = reader.readMessageEnd();
    let valueValue: number | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: valueValue = reader.readFloat64(); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      value: valueValue,
    };
  },
  writeInto(writer: BebopWriter, value: Value_Number): void {
    const pos = writer.reserveMessageLength();
    if (value.value !== undefined) {
      writer.writeTag(1);
      writer.writeFloat64(value.value);
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: Value_Number): number {
    let size = 5;
    if (value.value !== undefined) {
      size += 1;
      size += 8;
    }
    return size;
  },
  reflection: {
    name: "Number",
    fqn: "bebop.Value.Number",
    kind: BebopDefinitionKind.message,
    detail: {
      fields: [
        { name: "value", index: 1, typeName: "number" },
      ],
    },
  },
} satisfies BebopReflectableCodec<Value_Number>;

export type Value_String = {
  readonly value?: string | undefined;
};

export const Value_String = {
  readFrom(reader: BebopReader): Value_String {
    const end = reader.readMessageEnd();
    let valueValue: string | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: valueValue = reader.readString(); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      value: valueValue,
    };
  },
  writeInto(writer: BebopWriter, value: Value_String): void {
    const pos = writer.reserveMessageLength();
    if (value.value !== undefined) {
      writer.writeTag(1);
      writer.writeString(value.value);
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: Value_String): number {
    let size = 5;
    if (value.value !== undefined) {
      size += 1;
      size += 4 + new TextEncoder().encode(value.value).length + 1;
    }
    return size;
  },
  reflection: {
    name: "String",
    fqn: "bebop.Value.String",
    kind: BebopDefinitionKind.message,
    detail: {
      fields: [
        { name: "value", index: 1, typeName: "string" },
      ],
    },
  },
} satisfies BebopReflectableCodec<Value_String>;

export type Value_List = {
  readonly values?: readonly Value[] | undefined;
};

export const Value_List = {
  readFrom(reader: BebopReader): Value_List {
    const end = reader.readMessageEnd();
    let valuesValue: readonly Value[] | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: valuesValue = reader.readDynamicArray((_r) => Value.readFrom(_r)); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      values: valuesValue,
    };
  },
  writeInto(writer: BebopWriter, value: Value_List): void {
    const pos = writer.reserveMessageLength();
    if (value.values !== undefined) {
      writer.writeTag(1);
      writer.writeDynamicArray(value.values, (_w, _v) => {
        Value.writeInto(_w, _v);
      });
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: Value_List): number {
    let size = 5;
    if (value.values !== undefined) {
      size += 1;
      size += 4;
      for (let i = 0; i < value.values.length; i++) {
        const item = value.values[i]!;
        size += Value.encodedSize(item);
      }
    }
    return size;
  },
  reflection: {
    name: "List",
    fqn: "bebop.Value.List",
    kind: BebopDefinitionKind.message,
    detail: {
      fields: [
        { name: "values", index: 1, typeName: "readonly Value[]" },
      ],
    },
  },
} satisfies BebopReflectableCodec<Value_List>;

export type Value_Map = {
  readonly fields?: ReadonlyMap<string, Value> | undefined;
};

export const Value_Map = {
  readFrom(reader: BebopReader): Value_Map {
    const end = reader.readMessageEnd();
    let fieldsValue: ReadonlyMap<string, Value> | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: fieldsValue = reader.readDynamicMap((_r) => _r.readString(), (_r) => Value.readFrom(_r)); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      fields: fieldsValue,
    };
  },
  writeInto(writer: BebopWriter, value: Value_Map): void {
    const pos = writer.reserveMessageLength();
    if (value.fields !== undefined) {
      writer.writeTag(1);
      writer.writeDynamicMap(value.fields, (_w, _k, _v) => {
        _w.writeString(_k);
        Value.writeInto(_w, _v);
      });
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: Value_Map): number {
    let size = 5;
    if (value.fields !== undefined) {
      size += 1;
      size += 4;
      value.fields.forEach((_v, _k) => {
        size += 4 + new TextEncoder().encode(_k).length + 1;
        size += Value.encodedSize(_v);
      });
    }
    return size;
  },
  reflection: {
    name: "Map",
    fqn: "bebop.Value.Map",
    kind: BebopDefinitionKind.message,
    detail: {
      fields: [
        { name: "fields", index: 1, typeName: "ReadonlyMap<string, Value>" },
      ],
    },
  },
} satisfies BebopReflectableCodec<Value_Map>;

export type Value =
  | { readonly kind: "unknown"; readonly discriminator: number; readonly data: Uint8Array }
  | { readonly kind: "Null"; readonly value: Null }
  | { readonly kind: "Bool"; readonly value: Value_Bool }
  | { readonly kind: "Number"; readonly value: Value_Number }
  | { readonly kind: "String"; readonly value: Value_String }
  | { readonly kind: "List"; readonly value: Value_List }
  | { readonly kind: "Map"; readonly value: Value_Map }
;

export const Value = {
  readFrom(reader: BebopReader): Value {
    const end = reader.readMessageEnd();
    const discriminator = reader.readByte();
    switch (discriminator) {
      case 1: return { kind: "Null", value: Null.readFrom(reader) };
      case 2: return { kind: "Bool", value: Value_Bool.readFrom(reader) };
      case 3: return { kind: "Number", value: Value_Number.readFrom(reader) };
      case 4: return { kind: "String", value: Value_String.readFrom(reader) };
      case 5: return { kind: "List", value: Value_List.readFrom(reader) };
      case 6: return { kind: "Map", value: Value_Map.readFrom(reader) };
      default: return { kind: "unknown", discriminator, data: reader.readBytes(end - reader.index) };
    }
  },
  writeInto(writer: BebopWriter, value: Value): void {
    const pos = writer.reserveMessageLength();
    switch (value.kind) {
      case "Null":
        writer.writeByte(1);
        Null.writeInto(writer, value.value);
        break;
      case "Bool":
        writer.writeByte(2);
        Value_Bool.writeInto(writer, value.value);
        break;
      case "Number":
        writer.writeByte(3);
        Value_Number.writeInto(writer, value.value);
        break;
      case "String":
        writer.writeByte(4);
        Value_String.writeInto(writer, value.value);
        break;
      case "List":
        writer.writeByte(5);
        Value_List.writeInto(writer, value.value);
        break;
      case "Map":
        writer.writeByte(6);
        Value_Map.writeInto(writer, value.value);
        break;
      case "unknown":
        writer.writeByte(value.discriminator);
        writer.writeBytes(value.data);
        break;
    }
    writer.fillMessageLength(pos);
  },
  encodedSize(value: Value): number {
    switch (value.kind) {
      case "Null": return 5 + Null.encodedSize(value.value);
      case "Bool": return 5 + Value_Bool.encodedSize(value.value);
      case "Number": return 5 + Value_Number.encodedSize(value.value);
      case "String": return 5 + Value_String.encodedSize(value.value);
      case "List": return 5 + Value_List.encodedSize(value.value);
      case "Map": return 5 + Value_Map.encodedSize(value.value);
      case "unknown": return 5 + value.data.length;
    }
  },
  reflection: {
    name: "Value",
    fqn: "bebop.Value",
    kind: BebopDefinitionKind.union,
    detail: {
      branches: [
        { discriminator: 1, name: "Null", typeName: "Null" },
        { discriminator: 2, name: "Bool", typeName: "Value_Bool" },
        { discriminator: 3, name: "Number", typeName: "Value_Number" },
        { discriminator: 4, name: "String", typeName: "Value_String" },
        { discriminator: 5, name: "List", typeName: "Value_List" },
        { discriminator: 6, name: "Map", typeName: "Value_Map" },
      ],
    },
  },
} satisfies BebopReflectableCodec<Value>;

export type Object = {
  readonly fields?: ReadonlyMap<string, Value> | undefined;
};

export const Object = {
  readFrom(reader: BebopReader): Object {
    const end = reader.readMessageEnd();
    let fieldsValue: ReadonlyMap<string, Value> | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: fieldsValue = reader.readDynamicMap((_r) => _r.readString(), (_r) => Value.readFrom(_r)); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      fields: fieldsValue,
    };
  },
  writeInto(writer: BebopWriter, value: Object): void {
    const pos = writer.reserveMessageLength();
    if (value.fields !== undefined) {
      writer.writeTag(1);
      writer.writeDynamicMap(value.fields, (_w, _k, _v) => {
        _w.writeString(_k);
        Value.writeInto(_w, _v);
      });
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: Object): number {
    let size = 5;
    if (value.fields !== undefined) {
      size += 1;
      size += 4;
      value.fields.forEach((_v, _k) => {
        size += 4 + new TextEncoder().encode(_k).length + 1;
        size += Value.encodedSize(_v);
      });
    }
    return size;
  },
  reflection: {
    name: "Object",
    fqn: "bebop.Object",
    kind: BebopDefinitionKind.message,
    detail: {
      fields: [
        { name: "fields", index: 1, typeName: "ReadonlyMap<string, Value>" },
      ],
    },
  },
} satisfies BebopReflectableCodec<Object>;

export type List = {
  readonly values?: readonly Value[] | undefined;
};

export const List = {
  readFrom(reader: BebopReader): List {
    const end = reader.readMessageEnd();
    let valuesValue: readonly Value[] | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: valuesValue = reader.readDynamicArray((_r) => Value.readFrom(_r)); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      values: valuesValue,
    };
  },
  writeInto(writer: BebopWriter, value: List): void {
    const pos = writer.reserveMessageLength();
    if (value.values !== undefined) {
      writer.writeTag(1);
      writer.writeDynamicArray(value.values, (_w, _v) => {
        Value.writeInto(_w, _v);
      });
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: List): number {
    let size = 5;
    if (value.values !== undefined) {
      size += 1;
      size += 4;
      for (let i = 0; i < value.values.length; i++) {
        const item = value.values[i]!;
        size += Value.encodedSize(item);
      }
    }
    return size;
  },
  reflection: {
    name: "List",
    fqn: "bebop.List",
    kind: BebopDefinitionKind.message,
    detail: {
      fields: [
        { name: "values", index: 1, typeName: "readonly Value[]" },
      ],
    },
  },
} satisfies BebopReflectableCodec<List>;

