// Code generated by bebopc-gen-typescript. DO NOT EDIT.
// source: ../../bebop/schemas/bebop/json.bop
// bebopc 2026.0.0-alpha.3

import { decode, encode } from "./codec.js";
import { messageEncodedSize, type BebopMessageView } from "./message.js";
import type { BebopGeneratedCodec } from "./reflection.js";
import { BebopStringView, BebopViewReader, readMessageField, type BebopArrayView, type BebopMapView } from "./view.js";
import { BebopReader, utf8ByteLength, type BebopReaderOptions, type BebopWriter } from "./wire.js";

export type Null = {
};

export class NullView {
  readonly encoded: Uint8Array;

  private constructor(encoded: Uint8Array) {
    this.encoded = encoded;
  }

  static readFrom(reader: BebopViewReader): NullView {
    const start = reader.position;
    return new NullView(reader.encodedFrom(start));
  }

  static skip(_reader: BebopViewReader): void {
  }

  decoded(options?: BebopReaderOptions): Null {
    return Null.decode(this.encoded, options);
  }
}

export const Null = {
  encode(value: Null): Uint8Array {
    return encode(Null, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): Null {
    return decode(Null, bytes, options);
  },
  view(bytes: Uint8Array, options?: BebopReaderOptions): NullView {
    const reader = new BebopViewReader(bytes, options);
    const view = NullView.readFrom(reader);
    reader.finish();
    return view;
  },
  readView(reader: BebopViewReader): NullView {
    return NullView.readFrom(reader);
  },
  readFrom(_reader: BebopReader): Null {
    return {};
  },
  writeInto(_writer: BebopWriter, _value: Null): void {
  },
  encodedSize(_value: Null): number {
    return 0;
  },
  reflection: {
    name: "Null",
    fqn: "bebop.Null",
    kind: "struct",
    detail: {
      fields: [
      ],
    },
  },
} satisfies BebopGeneratedCodec<Null, NullView>;

export type Value_Bool = {
  readonly value?: boolean | undefined;
};

export class Value_BoolView {
  private constructor(private readonly message: BebopMessageView) {}

  get encoded(): Uint8Array { return this.message.encoded; }

  field(tag: number): Uint8Array | undefined {
    return this.message.field(tag);
  }

  get value(): boolean | undefined {
    return readMessageField(this.message, 1, (_r) => _r.readBool());
  }

  static readFrom(reader: BebopViewReader): Value_BoolView {
    return new Value_BoolView(reader.readMessage());
  }

  static skip(reader: BebopViewReader): void {
    reader.skipMessage();
  }

  decoded(options?: BebopReaderOptions): Value_Bool {
    return Value_Bool.decode(this.encoded, options);
  }
}

export const Value_Bool = {
  encode(value: Value_Bool): Uint8Array {
    return encode(Value_Bool, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): Value_Bool {
    return decode(Value_Bool, bytes, options);
  },
  view(bytes: Uint8Array, options?: BebopReaderOptions): Value_BoolView {
    const reader = new BebopViewReader(bytes, options);
    const view = Value_BoolView.readFrom(reader);
    reader.finish();
    return view;
  },
  readView(reader: BebopViewReader): Value_BoolView {
    return Value_BoolView.readFrom(reader);
  },
  readFrom(reader: BebopReader): Value_Bool {
    const message = reader.readMessage();
    return {
      value: message.read(1, (_r) => _r.readBool()),
    };
  },
  writeInto(writer: BebopWriter, value: Value_Bool): void {
    const message = writer.beginMessage();
    if (value.value !== undefined) {
      writer.markMessageField(message, 1);
      writer.writeBool(value.value);
    }
    writer.endMessage(message);
  },
  encodedSize(value: Value_Bool): number {
    let size = 0;
    let fieldCount = 0;
    let maxTag = 0;
    let blockMask = 0;
    if (value.value !== undefined) {
      fieldCount++;
      maxTag = 1;
      blockMask |= 1;
      size += 1;
    }
    return messageEncodedSize(size, fieldCount, maxTag, blockMask);
  },
  reflection: {
    name: "Bool",
    fqn: "bebop.Value.Bool",
    kind: "message",
    detail: {
      fields: [
        { name: "value", index: 1, typeName: "boolean" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<Value_Bool, Value_BoolView>;

export type Value_Number = {
  readonly value?: number | undefined;
};

export class Value_NumberView {
  private constructor(private readonly message: BebopMessageView) {}

  get encoded(): Uint8Array { return this.message.encoded; }

  field(tag: number): Uint8Array | undefined {
    return this.message.field(tag);
  }

  get value(): number | undefined {
    return readMessageField(this.message, 1, (_r) => _r.readFloat64());
  }

  static readFrom(reader: BebopViewReader): Value_NumberView {
    return new Value_NumberView(reader.readMessage());
  }

  static skip(reader: BebopViewReader): void {
    reader.skipMessage();
  }

  decoded(options?: BebopReaderOptions): Value_Number {
    return Value_Number.decode(this.encoded, options);
  }
}

export const Value_Number = {
  encode(value: Value_Number): Uint8Array {
    return encode(Value_Number, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): Value_Number {
    return decode(Value_Number, bytes, options);
  },
  view(bytes: Uint8Array, options?: BebopReaderOptions): Value_NumberView {
    const reader = new BebopViewReader(bytes, options);
    const view = Value_NumberView.readFrom(reader);
    reader.finish();
    return view;
  },
  readView(reader: BebopViewReader): Value_NumberView {
    return Value_NumberView.readFrom(reader);
  },
  readFrom(reader: BebopReader): Value_Number {
    const message = reader.readMessage();
    return {
      value: message.read(1, (_r) => _r.readFloat64()),
    };
  },
  writeInto(writer: BebopWriter, value: Value_Number): void {
    const message = writer.beginMessage();
    if (value.value !== undefined) {
      writer.markMessageField(message, 1);
      writer.writeFloat64(value.value);
    }
    writer.endMessage(message);
  },
  encodedSize(value: Value_Number): number {
    let size = 0;
    let fieldCount = 0;
    let maxTag = 0;
    let blockMask = 0;
    if (value.value !== undefined) {
      fieldCount++;
      maxTag = 1;
      blockMask |= 1;
      size += 8;
    }
    return messageEncodedSize(size, fieldCount, maxTag, blockMask);
  },
  reflection: {
    name: "Number",
    fqn: "bebop.Value.Number",
    kind: "message",
    detail: {
      fields: [
        { name: "value", index: 1, typeName: "number" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<Value_Number, Value_NumberView>;

export type Value_String = {
  readonly value?: string | undefined;
};

export class Value_StringView {
  private constructor(private readonly message: BebopMessageView) {}

  get encoded(): Uint8Array { return this.message.encoded; }

  field(tag: number): Uint8Array | undefined {
    return this.message.field(tag);
  }

  get value(): BebopStringView | undefined {
    return readMessageField(this.message, 1, (_r) => _r.readStringView());
  }

  static readFrom(reader: BebopViewReader): Value_StringView {
    return new Value_StringView(reader.readMessage());
  }

  static skip(reader: BebopViewReader): void {
    reader.skipMessage();
  }

  decoded(options?: BebopReaderOptions): Value_String {
    return Value_String.decode(this.encoded, options);
  }
}

export const Value_String = {
  encode(value: Value_String): Uint8Array {
    return encode(Value_String, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): Value_String {
    return decode(Value_String, bytes, options);
  },
  view(bytes: Uint8Array, options?: BebopReaderOptions): Value_StringView {
    const reader = new BebopViewReader(bytes, options);
    const view = Value_StringView.readFrom(reader);
    reader.finish();
    return view;
  },
  readView(reader: BebopViewReader): Value_StringView {
    return Value_StringView.readFrom(reader);
  },
  readFrom(reader: BebopReader): Value_String {
    const message = reader.readMessage();
    return {
      value: message.read(1, (_r) => _r.readString()),
    };
  },
  writeInto(writer: BebopWriter, value: Value_String): void {
    const message = writer.beginMessage();
    if (value.value !== undefined) {
      writer.markMessageField(message, 1);
      writer.writeString(value.value);
    }
    writer.endMessage(message);
  },
  encodedSize(value: Value_String): number {
    let size = 0;
    let fieldCount = 0;
    let maxTag = 0;
    let blockMask = 0;
    if (value.value !== undefined) {
      fieldCount++;
      maxTag = 1;
      blockMask |= 1;
      size += 5 + utf8ByteLength(value.value);
    }
    return messageEncodedSize(size, fieldCount, maxTag, blockMask);
  },
  reflection: {
    name: "String",
    fqn: "bebop.Value.String",
    kind: "message",
    detail: {
      fields: [
        { name: "value", index: 1, typeName: "string" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<Value_String, Value_StringView>;

export type Value_List = {
  readonly values?: readonly Value[] | undefined;
};

export class Value_ListView {
  private constructor(private readonly message: BebopMessageView) {}

  get encoded(): Uint8Array { return this.message.encoded; }

  field(tag: number): Uint8Array | undefined {
    return this.message.field(tag);
  }

  get values(): BebopArrayView<ValueView> | undefined {
    return readMessageField(this.message, 1, (_r) => _r.readArrayView((_r) => _r.readNestedView(ValueView), undefined, (_r) => _r.skipNestedView(ValueView)));
  }

  static readFrom(reader: BebopViewReader): Value_ListView {
    return new Value_ListView(reader.readMessage());
  }

  static skip(reader: BebopViewReader): void {
    reader.skipMessage();
  }

  decoded(options?: BebopReaderOptions): Value_List {
    return Value_List.decode(this.encoded, options);
  }
}

export const Value_List = {
  encode(value: Value_List): Uint8Array {
    return encode(Value_List, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): Value_List {
    return decode(Value_List, bytes, options);
  },
  view(bytes: Uint8Array, options?: BebopReaderOptions): Value_ListView {
    const reader = new BebopViewReader(bytes, options);
    const view = Value_ListView.readFrom(reader);
    reader.finish();
    return view;
  },
  readView(reader: BebopViewReader): Value_ListView {
    return Value_ListView.readFrom(reader);
  },
  readFrom(reader: BebopReader): Value_List {
    const message = reader.readMessage();
    return {
      values: message.read(1, (_r) => _r.readDynamicArray((_r) => _r.readNested(Value))),
    };
  },
  writeInto(writer: BebopWriter, value: Value_List): void {
    const message = writer.beginMessage();
    if (value.values !== undefined) {
      writer.markMessageField(message, 1);
      writer.writeDynamicArray(value.values, (_w, _v) => {
        Value.writeInto(_w, _v);
      });
    }
    writer.endMessage(message);
  },
  encodedSize(value: Value_List): number {
    let size = 0;
    let fieldCount = 0;
    let maxTag = 0;
    let blockMask = 0;
    if (value.values !== undefined) {
      fieldCount++;
      maxTag = 1;
      blockMask |= 1;
      size += 4;
      for (let _i0 = 0; _i0 < value.values.length; _i0++) {
        const _item1 = value.values[_i0]!;
        size += Value.encodedSize(_item1);
      }
    }
    return messageEncodedSize(size, fieldCount, maxTag, blockMask);
  },
  reflection: {
    name: "List",
    fqn: "bebop.Value.List",
    kind: "message",
    detail: {
      fields: [
        { name: "values", index: 1, typeName: "readonly Value[]" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<Value_List, Value_ListView>;

export type Value_Map = {
  readonly fields?: ReadonlyMap<string, Value> | undefined;
};

export class Value_MapView {
  private constructor(private readonly message: BebopMessageView) {}

  get encoded(): Uint8Array { return this.message.encoded; }

  field(tag: number): Uint8Array | undefined {
    return this.message.field(tag);
  }

  get fields(): BebopMapView<BebopStringView, ValueView> | undefined {
    return readMessageField(this.message, 1, (_r) => _r.readMapView((_r) => _r.readStringView(), (_r) => _r.readNestedView(ValueView), (_r) => _r.skipString(), (_r) => _r.skipNestedView(ValueView)));
  }

  static readFrom(reader: BebopViewReader): Value_MapView {
    return new Value_MapView(reader.readMessage());
  }

  static skip(reader: BebopViewReader): void {
    reader.skipMessage();
  }

  decoded(options?: BebopReaderOptions): Value_Map {
    return Value_Map.decode(this.encoded, options);
  }
}

export const Value_Map = {
  encode(value: Value_Map): Uint8Array {
    return encode(Value_Map, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): Value_Map {
    return decode(Value_Map, bytes, options);
  },
  view(bytes: Uint8Array, options?: BebopReaderOptions): Value_MapView {
    const reader = new BebopViewReader(bytes, options);
    const view = Value_MapView.readFrom(reader);
    reader.finish();
    return view;
  },
  readView(reader: BebopViewReader): Value_MapView {
    return Value_MapView.readFrom(reader);
  },
  readFrom(reader: BebopReader): Value_Map {
    const message = reader.readMessage();
    return {
      fields: message.read(1, (_r) => _r.readDynamicMap((_r) => _r.readString(), (_r) => _r.readNested(Value))),
    };
  },
  writeInto(writer: BebopWriter, value: Value_Map): void {
    const message = writer.beginMessage();
    if (value.fields !== undefined) {
      writer.markMessageField(message, 1);
      writer.writeDynamicMap(value.fields, (_w, _k, _v) => {
        _w.writeString(_k);
        Value.writeInto(_w, _v);
      });
    }
    writer.endMessage(message);
  },
  encodedSize(value: Value_Map): number {
    let size = 0;
    let fieldCount = 0;
    let maxTag = 0;
    let blockMask = 0;
    if (value.fields !== undefined) {
      fieldCount++;
      maxTag = 1;
      blockMask |= 1;
      size += 4;
      for (const [_k, _v] of value.fields) {
        size += 5 + utf8ByteLength(_k);
        size += Value.encodedSize(_v);
      }
    }
    return messageEncodedSize(size, fieldCount, maxTag, blockMask);
  },
  reflection: {
    name: "Map",
    fqn: "bebop.Value.Map",
    kind: "message",
    detail: {
      fields: [
        { name: "fields", index: 1, typeName: "ReadonlyMap<string, Value>" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<Value_Map, Value_MapView>;

export type Value =
  | { readonly kind: "unknown"; readonly discriminator: number; readonly data: Uint8Array }
  | { readonly kind: "null"; readonly value: Null }
  | { readonly kind: "bool"; readonly value: Value_Bool }
  | { readonly kind: "number"; readonly value: Value_Number }
  | { readonly kind: "string"; readonly value: Value_String }
  | { readonly kind: "list"; readonly value: Value_List }
  | { readonly kind: "map"; readonly value: Value_Map };

export type ValueView =
  | {
    readonly encoded: Uint8Array;
    readonly kind: "unknown";
    readonly discriminator: number;
    readonly data: Uint8Array;
    decoded(options?: BebopReaderOptions): Value;
  }
  | {
    readonly encoded: Uint8Array;
    readonly kind: "null";
    readonly value: NullView;
    decoded(options?: BebopReaderOptions): Value;
  }
  | {
    readonly encoded: Uint8Array;
    readonly kind: "bool";
    readonly value: Value_BoolView;
    decoded(options?: BebopReaderOptions): Value;
  }
  | {
    readonly encoded: Uint8Array;
    readonly kind: "number";
    readonly value: Value_NumberView;
    decoded(options?: BebopReaderOptions): Value;
  }
  | {
    readonly encoded: Uint8Array;
    readonly kind: "string";
    readonly value: Value_StringView;
    decoded(options?: BebopReaderOptions): Value;
  }
  | {
    readonly encoded: Uint8Array;
    readonly kind: "list";
    readonly value: Value_ListView;
    decoded(options?: BebopReaderOptions): Value;
  }
  | {
    readonly encoded: Uint8Array;
    readonly kind: "map";
    readonly value: Value_MapView;
    decoded(options?: BebopReaderOptions): Value;
  };

export const ValueView = {
  readFrom(reader: BebopViewReader): ValueView {
    const result = reader.readLengthPrefixedValue((_r) => {
      const discriminator = _r.readByte();
      switch (discriminator) {
        case 1: return { kind: "null" as const, value: _r.readNestedView(NullView) };
        case 2: return { kind: "bool" as const, value: _r.readNestedView(Value_BoolView) };
        case 3: return { kind: "number" as const, value: _r.readNestedView(Value_NumberView) };
        case 4: return { kind: "string" as const, value: _r.readNestedView(Value_StringView) };
        case 5: return { kind: "list" as const, value: _r.readNestedView(Value_ListView) };
        case 6: return { kind: "map" as const, value: _r.readNestedView(Value_MapView) };
        default: return { kind: "unknown" as const, discriminator, data: _r.readView(_r.remaining) };
      }
    });
    return {
      encoded: result.encoded,
      ...result.value,
      decoded(options?: BebopReaderOptions): Value {
        return Value.decode(this.encoded, options);
      },
    };
  },
  skip(reader: BebopViewReader): void {
    reader.skipLengthPrefixed();
  },
} as const;

export const Value = {
  encode(value: Value): Uint8Array {
    return encode(Value, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): Value {
    return decode(Value, bytes, options);
  },
  view(bytes: Uint8Array, options?: BebopReaderOptions): ValueView {
    const reader = new BebopViewReader(bytes, options);
    const view = ValueView.readFrom(reader);
    reader.finish();
    return view;
  },
  readView(reader: BebopViewReader): ValueView {
    return ValueView.readFrom(reader);
  },
  readFrom(reader: BebopReader): Value {
    return reader.readLengthPrefixed((valueReader) => {
      const discriminator = valueReader.readByte();
      switch (discriminator) {
        case 1: return { kind: "null", value: valueReader.readNested(Null) };
        case 2: return { kind: "bool", value: valueReader.readNested(Value_Bool) };
        case 3: return { kind: "number", value: valueReader.readNested(Value_Number) };
        case 4: return { kind: "string", value: valueReader.readNested(Value_String) };
        case 5: return { kind: "list", value: valueReader.readNested(Value_List) };
        case 6: return { kind: "map", value: valueReader.readNested(Value_Map) };
        default: return { kind: "unknown", discriminator, data: valueReader.readBytes(valueReader.length - valueReader.index) };
      }
    });
  },
  writeInto(writer: BebopWriter, value: Value): void {
    const position = writer.beginLengthPrefixed();
    switch (value.kind) {
      case "null":
        writer.writeByte(1);
        Null.writeInto(writer, value.value);
        break;
      case "bool":
        writer.writeByte(2);
        Value_Bool.writeInto(writer, value.value);
        break;
      case "number":
        writer.writeByte(3);
        Value_Number.writeInto(writer, value.value);
        break;
      case "string":
        writer.writeByte(4);
        Value_String.writeInto(writer, value.value);
        break;
      case "list":
        writer.writeByte(5);
        Value_List.writeInto(writer, value.value);
        break;
      case "map":
        writer.writeByte(6);
        Value_Map.writeInto(writer, value.value);
        break;
      case "unknown":
        writer.writeByte(value.discriminator);
        writer.writeBytes(value.data);
        break;
    }
    writer.endLengthPrefixed(position);
  },
  encodedSize(value: Value): number {
    switch (value.kind) {
      case "null": return 5 + Null.encodedSize(value.value);
      case "bool": return 5 + Value_Bool.encodedSize(value.value);
      case "number": return 5 + Value_Number.encodedSize(value.value);
      case "string": return 5 + Value_String.encodedSize(value.value);
      case "list": return 5 + Value_List.encodedSize(value.value);
      case "map": return 5 + Value_Map.encodedSize(value.value);
      case "unknown": return 5 + value.data.length;
    }
  },
  reflection: {
    name: "Value",
    fqn: "bebop.Value",
    kind: "union",
    detail: {
      branches: [
        { discriminator: 1, name: "Null", typeName: "Null" },
        { discriminator: 2, name: "Bool", typeName: "Value_Bool" },
        { discriminator: 3, name: "Number", typeName: "Value_Number" },
        { discriminator: 4, name: "String", typeName: "Value_String" },
        { discriminator: 5, name: "List", typeName: "Value_List" },
        { discriminator: 6, name: "Map", typeName: "Value_Map" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<Value, ValueView>;

export type Object = {
  readonly fields?: ReadonlyMap<string, Value> | undefined;
};

export class ObjectView {
  private constructor(private readonly message: BebopMessageView) {}

  get encoded(): Uint8Array { return this.message.encoded; }

  field(tag: number): Uint8Array | undefined {
    return this.message.field(tag);
  }

  get fields(): BebopMapView<BebopStringView, ValueView> | undefined {
    return readMessageField(this.message, 1, (_r) => _r.readMapView((_r) => _r.readStringView(), (_r) => _r.readNestedView(ValueView), (_r) => _r.skipString(), (_r) => _r.skipNestedView(ValueView)));
  }

  static readFrom(reader: BebopViewReader): ObjectView {
    return new ObjectView(reader.readMessage());
  }

  static skip(reader: BebopViewReader): void {
    reader.skipMessage();
  }

  decoded(options?: BebopReaderOptions): Object {
    return Object.decode(this.encoded, options);
  }
}

export const Object = {
  encode(value: Object): Uint8Array {
    return encode(Object, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): Object {
    return decode(Object, bytes, options);
  },
  view(bytes: Uint8Array, options?: BebopReaderOptions): ObjectView {
    const reader = new BebopViewReader(bytes, options);
    const view = ObjectView.readFrom(reader);
    reader.finish();
    return view;
  },
  readView(reader: BebopViewReader): ObjectView {
    return ObjectView.readFrom(reader);
  },
  readFrom(reader: BebopReader): Object {
    const message = reader.readMessage();
    return {
      fields: message.read(1, (_r) => _r.readDynamicMap((_r) => _r.readString(), (_r) => _r.readNested(Value))),
    };
  },
  writeInto(writer: BebopWriter, value: Object): void {
    const message = writer.beginMessage();
    if (value.fields !== undefined) {
      writer.markMessageField(message, 1);
      writer.writeDynamicMap(value.fields, (_w, _k, _v) => {
        _w.writeString(_k);
        Value.writeInto(_w, _v);
      });
    }
    writer.endMessage(message);
  },
  encodedSize(value: Object): number {
    let size = 0;
    let fieldCount = 0;
    let maxTag = 0;
    let blockMask = 0;
    if (value.fields !== undefined) {
      fieldCount++;
      maxTag = 1;
      blockMask |= 1;
      size += 4;
      for (const [_k, _v] of value.fields) {
        size += 5 + utf8ByteLength(_k);
        size += Value.encodedSize(_v);
      }
    }
    return messageEncodedSize(size, fieldCount, maxTag, blockMask);
  },
  reflection: {
    name: "Object",
    fqn: "bebop.Object",
    kind: "message",
    detail: {
      fields: [
        { name: "fields", index: 1, typeName: "ReadonlyMap<string, Value>" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<Object, ObjectView>;

export type List = {
  readonly values?: readonly Value[] | undefined;
};

export class ListView {
  private constructor(private readonly message: BebopMessageView) {}

  get encoded(): Uint8Array { return this.message.encoded; }

  field(tag: number): Uint8Array | undefined {
    return this.message.field(tag);
  }

  get values(): BebopArrayView<ValueView> | undefined {
    return readMessageField(this.message, 1, (_r) => _r.readArrayView((_r) => _r.readNestedView(ValueView), undefined, (_r) => _r.skipNestedView(ValueView)));
  }

  static readFrom(reader: BebopViewReader): ListView {
    return new ListView(reader.readMessage());
  }

  static skip(reader: BebopViewReader): void {
    reader.skipMessage();
  }

  decoded(options?: BebopReaderOptions): List {
    return List.decode(this.encoded, options);
  }
}

export const List = {
  encode(value: List): Uint8Array {
    return encode(List, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): List {
    return decode(List, bytes, options);
  },
  view(bytes: Uint8Array, options?: BebopReaderOptions): ListView {
    const reader = new BebopViewReader(bytes, options);
    const view = ListView.readFrom(reader);
    reader.finish();
    return view;
  },
  readView(reader: BebopViewReader): ListView {
    return ListView.readFrom(reader);
  },
  readFrom(reader: BebopReader): List {
    const message = reader.readMessage();
    return {
      values: message.read(1, (_r) => _r.readDynamicArray((_r) => _r.readNested(Value))),
    };
  },
  writeInto(writer: BebopWriter, value: List): void {
    const message = writer.beginMessage();
    if (value.values !== undefined) {
      writer.markMessageField(message, 1);
      writer.writeDynamicArray(value.values, (_w, _v) => {
        Value.writeInto(_w, _v);
      });
    }
    writer.endMessage(message);
  },
  encodedSize(value: List): number {
    let size = 0;
    let fieldCount = 0;
    let maxTag = 0;
    let blockMask = 0;
    if (value.values !== undefined) {
      fieldCount++;
      maxTag = 1;
      blockMask |= 1;
      size += 4;
      for (let _i2 = 0; _i2 < value.values.length; _i2++) {
        const _item3 = value.values[_i2]!;
        size += Value.encodedSize(_item3);
      }
    }
    return messageEncodedSize(size, fieldCount, maxTag, blockMask);
  },
  reflection: {
    name: "List",
    fqn: "bebop.List",
    kind: "message",
    detail: {
      fields: [
        { name: "values", index: 1, typeName: "readonly Value[]" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<List, ListView>;
