// Code generated by bebopc-gen-typescript. DO NOT EDIT.
// source: bebop/schemas/bebop/rpc.bop
// bebopc 2026.0.0-alpha.3

import { BebopDefinitionKind } from "./reflection";
import { BebopTimestamp } from "./temporal";
import { BebopUUID } from "./uuid";
import type { BebopReflectableCodec } from "./reflection";
import type { BebopReader, BebopWriter } from "./wire";


export const StatusCode = {
  OK: 0,
  CANCELLED: 1,
  UNKNOWN: 2,
  INVALID_ARGUMENT: 3,
  DEADLINE_EXCEEDED: 4,
  NOT_FOUND: 5,
  PERMISSION_DENIED: 7,
  RESOURCE_EXHAUSTED: 8,
  UNIMPLEMENTED: 12,
  INTERNAL: 13,
  UNAVAILABLE: 14,
  UNAUTHENTICATED: 16,
} as const;
export type StatusCode = (typeof StatusCode)[keyof typeof StatusCode];

export const FrameFlags = {
  NONE: 0,
  END_STREAM: 1,
  ERROR: 2,
  COMPRESSED: 4,
  TRAILER: 8,
  CURSOR: 16,
} as const;
export type FrameFlags = number;

export const MethodType = {
  UNARY: 0,
  SERVER_STREAM: 1,
  CLIENT_STREAM: 2,
  DUPLEX_STREAM: 3,
} as const;
export type MethodType = (typeof MethodType)[keyof typeof MethodType];

export type FrameHeader = {
  readonly length: number;
  readonly flags: FrameFlags;
  readonly streamId: number;
};

export const FrameHeader = {
  readFrom(reader: BebopReader): FrameHeader {
    return {
      length: reader.readUint32(),
      flags: reader.readByte() as FrameFlags,
      streamId: reader.readUint32(),
    };
  },
  writeInto(writer: BebopWriter, value: FrameHeader): void {
    writer.writeUint32(value.length);
    writer.writeByte(value.flags);
    writer.writeUint32(value.streamId);
  },
  encodedSize(value: FrameHeader): number {
    let size = 0;
    size += 4;
    size += 1;
    size += 4;
    return size;
  },
  reflection: {
    name: "FrameHeader",
    fqn: "bebop.FrameHeader",
    kind: BebopDefinitionKind.struct,
    detail: {
      fields: [
        { name: "length", index: 0, typeName: "number" },
        { name: "flags", index: 0, typeName: "FrameFlags" },
        { name: "stream_id", index: 0, typeName: "number" },
      ],
    },
  },
} satisfies BebopReflectableCodec<FrameHeader>;

export type CallHeader = {
  readonly methodId?: number | undefined;
  readonly deadline?: BebopTimestamp | undefined;
  readonly metadata?: ReadonlyMap<string, string> | undefined;
  readonly cursor?: bigint | undefined;
};

export const CallHeader = {
  readFrom(reader: BebopReader): CallHeader {
    const end = reader.readMessageEnd();
    let methodIdValue: number | undefined;
    let deadlineValue: BebopTimestamp | undefined;
    let metadataValue: ReadonlyMap<string, string> | undefined;
    let cursorValue: bigint | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: methodIdValue = reader.readUint32(); break;
        case 2: deadlineValue = reader.readTimestamp(); break;
        case 3: metadataValue = reader.readDynamicMap((_r) => _r.readString(), (_r) => _r.readString()); break;
        case 4: cursorValue = reader.readUint64(); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      methodId: methodIdValue,
      deadline: deadlineValue,
      metadata: metadataValue,
      cursor: cursorValue,
    };
  },
  writeInto(writer: BebopWriter, value: CallHeader): void {
    const pos = writer.reserveMessageLength();
    if (value.methodId !== undefined) {
      writer.writeTag(1);
      writer.writeUint32(value.methodId);
    }
    if (value.deadline !== undefined) {
      writer.writeTag(2);
      writer.writeTimestamp(value.deadline);
    }
    if (value.metadata !== undefined) {
      writer.writeTag(3);
      writer.writeDynamicMap(value.metadata, (_w, _k, _v) => {
        _w.writeString(_k);
        _w.writeString(_v);
      });
    }
    if (value.cursor !== undefined) {
      writer.writeTag(4);
      writer.writeUint64(value.cursor);
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: CallHeader): number {
    let size = 5;
    if (value.methodId !== undefined) {
      size += 1;
      size += 4;
    }
    if (value.deadline !== undefined) {
      size += 1;
      size += 16;
    }
    if (value.metadata !== undefined) {
      size += 1;
      size += 4;
      value.metadata.forEach((_v, _k) => {
        size += 4 + new TextEncoder().encode(_k).length + 1;
        size += 4 + new TextEncoder().encode(_v).length + 1;
      });
    }
    if (value.cursor !== undefined) {
      size += 1;
      size += 8;
    }
    return size;
  },
  reflection: {
    name: "CallHeader",
    fqn: "bebop.CallHeader",
    kind: BebopDefinitionKind.message,
    detail: {
      fields: [
        { name: "method_id", index: 1, typeName: "number" },
        { name: "deadline", index: 2, typeName: "BebopTimestamp" },
        { name: "metadata", index: 3, typeName: "ReadonlyMap<string, string>" },
        { name: "cursor", index: 4, typeName: "bigint" },
      ],
    },
  },
} satisfies BebopReflectableCodec<CallHeader>;

export type RpcError = {
  readonly code?: StatusCode | undefined;
  readonly detail?: string | undefined;
  readonly metadata?: ReadonlyMap<string, string> | undefined;
};

export const RpcError = {
  readFrom(reader: BebopReader): RpcError {
    const end = reader.readMessageEnd();
    let codeValue: StatusCode | undefined;
    let detailValue: string | undefined;
    let metadataValue: ReadonlyMap<string, string> | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: codeValue = reader.readByte() as StatusCode; break;
        case 2: detailValue = reader.readString(); break;
        case 3: metadataValue = reader.readDynamicMap((_r) => _r.readString(), (_r) => _r.readString()); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      code: codeValue,
      detail: detailValue,
      metadata: metadataValue,
    };
  },
  writeInto(writer: BebopWriter, value: RpcError): void {
    const pos = writer.reserveMessageLength();
    if (value.code !== undefined) {
      writer.writeTag(1);
      writer.writeByte(value.code);
    }
    if (value.detail !== undefined) {
      writer.writeTag(2);
      writer.writeString(value.detail);
    }
    if (value.metadata !== undefined) {
      writer.writeTag(3);
      writer.writeDynamicMap(value.metadata, (_w, _k, _v) => {
        _w.writeString(_k);
        _w.writeString(_v);
      });
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: RpcError): number {
    let size = 5;
    if (value.code !== undefined) {
      size += 1;
      size += 1;
    }
    if (value.detail !== undefined) {
      size += 1;
      size += 4 + new TextEncoder().encode(value.detail).length + 1;
    }
    if (value.metadata !== undefined) {
      size += 1;
      size += 4;
      value.metadata.forEach((_v, _k) => {
        size += 4 + new TextEncoder().encode(_k).length + 1;
        size += 4 + new TextEncoder().encode(_v).length + 1;
      });
    }
    return size;
  },
  reflection: {
    name: "RpcError",
    fqn: "bebop.RpcError",
    kind: BebopDefinitionKind.message,
    detail: {
      fields: [
        { name: "code", index: 1, typeName: "StatusCode" },
        { name: "detail", index: 2, typeName: "string" },
        { name: "metadata", index: 3, typeName: "ReadonlyMap<string, string>" },
      ],
    },
  },
} satisfies BebopReflectableCodec<RpcError>;

export type TrailingMetadata = {
  readonly metadata?: ReadonlyMap<string, string> | undefined;
};

export const TrailingMetadata = {
  readFrom(reader: BebopReader): TrailingMetadata {
    const end = reader.readMessageEnd();
    let metadataValue: ReadonlyMap<string, string> | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: metadataValue = reader.readDynamicMap((_r) => _r.readString(), (_r) => _r.readString()); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      metadata: metadataValue,
    };
  },
  writeInto(writer: BebopWriter, value: TrailingMetadata): void {
    const pos = writer.reserveMessageLength();
    if (value.metadata !== undefined) {
      writer.writeTag(1);
      writer.writeDynamicMap(value.metadata, (_w, _k, _v) => {
        _w.writeString(_k);
        _w.writeString(_v);
      });
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: TrailingMetadata): number {
    let size = 5;
    if (value.metadata !== undefined) {
      size += 1;
      size += 4;
      value.metadata.forEach((_v, _k) => {
        size += 4 + new TextEncoder().encode(_k).length + 1;
        size += 4 + new TextEncoder().encode(_v).length + 1;
      });
    }
    return size;
  },
  reflection: {
    name: "TrailingMetadata",
    fqn: "bebop.TrailingMetadata",
    kind: BebopDefinitionKind.message,
    detail: {
      fields: [
        { name: "metadata", index: 1, typeName: "ReadonlyMap<string, string>" },
      ],
    },
  },
} satisfies BebopReflectableCodec<TrailingMetadata>;

export type MethodInfo = {
  readonly name: string;
  readonly methodId: number;
  readonly methodType: MethodType;
  readonly requestTypeUrl: string;
  readonly responseTypeUrl: string;
};

export const MethodInfo = {
  readFrom(reader: BebopReader): MethodInfo {
    return {
      name: reader.readString(),
      methodId: reader.readUint32(),
      methodType: reader.readByte() as MethodType,
      requestTypeUrl: reader.readString(),
      responseTypeUrl: reader.readString(),
    };
  },
  writeInto(writer: BebopWriter, value: MethodInfo): void {
    writer.writeString(value.name);
    writer.writeUint32(value.methodId);
    writer.writeByte(value.methodType);
    writer.writeString(value.requestTypeUrl);
    writer.writeString(value.responseTypeUrl);
  },
  encodedSize(value: MethodInfo): number {
    let size = 0;
    size += 4 + new TextEncoder().encode(value.name).length + 1;
    size += 4;
    size += 1;
    size += 4 + new TextEncoder().encode(value.requestTypeUrl).length + 1;
    size += 4 + new TextEncoder().encode(value.responseTypeUrl).length + 1;
    return size;
  },
  reflection: {
    name: "MethodInfo",
    fqn: "bebop.MethodInfo",
    kind: BebopDefinitionKind.struct,
    detail: {
      fields: [
        { name: "name", index: 0, typeName: "string" },
        { name: "method_id", index: 0, typeName: "number" },
        { name: "method_type", index: 0, typeName: "MethodType" },
        { name: "request_type_url", index: 0, typeName: "string" },
        { name: "response_type_url", index: 0, typeName: "string" },
      ],
    },
  },
} satisfies BebopReflectableCodec<MethodInfo>;

export type ServiceInfo = {
  readonly name: string;
  readonly methods: readonly MethodInfo[];
};

export const ServiceInfo = {
  readFrom(reader: BebopReader): ServiceInfo {
    return {
      name: reader.readString(),
      methods: reader.readDynamicArray((_r) => MethodInfo.readFrom(_r)),
    };
  },
  writeInto(writer: BebopWriter, value: ServiceInfo): void {
    writer.writeString(value.name);
    writer.writeDynamicArray(value.methods, (_w, _v) => {
      MethodInfo.writeInto(_w, _v);
    });
  },
  encodedSize(value: ServiceInfo): number {
    let size = 0;
    size += 4 + new TextEncoder().encode(value.name).length + 1;
    size += 4;
    for (let i = 0; i < value.methods.length; i++) {
      const item = value.methods[i]!;
      size += MethodInfo.encodedSize(item);
    }
    return size;
  },
  reflection: {
    name: "ServiceInfo",
    fqn: "bebop.ServiceInfo",
    kind: BebopDefinitionKind.struct,
    detail: {
      fields: [
        { name: "name", index: 0, typeName: "string" },
        { name: "methods", index: 0, typeName: "readonly MethodInfo[]" },
      ],
    },
  },
} satisfies BebopReflectableCodec<ServiceInfo>;

export type DiscoveryResponse = {
  readonly services: readonly ServiceInfo[];
};

export const DiscoveryResponse = {
  readFrom(reader: BebopReader): DiscoveryResponse {
    return {
      services: reader.readDynamicArray((_r) => ServiceInfo.readFrom(_r)),
    };
  },
  writeInto(writer: BebopWriter, value: DiscoveryResponse): void {
    writer.writeDynamicArray(value.services, (_w, _v) => {
      ServiceInfo.writeInto(_w, _v);
    });
  },
  encodedSize(value: DiscoveryResponse): number {
    let size = 0;
    size += 4;
    for (let i = 0; i < value.services.length; i++) {
      const item = value.services[i]!;
      size += ServiceInfo.encodedSize(item);
    }
    return size;
  },
  reflection: {
    name: "DiscoveryResponse",
    fqn: "bebop.DiscoveryResponse",
    kind: BebopDefinitionKind.struct,
    detail: {
      fields: [
        { name: "services", index: 0, typeName: "readonly ServiceInfo[]" },
      ],
    },
  },
} satisfies BebopReflectableCodec<DiscoveryResponse>;

export type BatchCall = {
  readonly callId: number;
  readonly methodId: number;
  readonly payload: Uint8Array;
  readonly inputFrom: number;
};

export const BatchCall = {
  readFrom(reader: BebopReader): BatchCall {
    return {
      callId: reader.readInt32(),
      methodId: reader.readUint32(),
      payload: reader.readUint8Array(),
      inputFrom: reader.readInt32(),
    };
  },
  writeInto(writer: BebopWriter, value: BatchCall): void {
    writer.writeInt32(value.callId);
    writer.writeUint32(value.methodId);
    writer.writeUint8Array(value.payload);
    writer.writeInt32(value.inputFrom);
  },
  encodedSize(value: BatchCall): number {
    let size = 0;
    size += 4;
    size += 4;
    size += 4 + value.payload.length;
    size += 4;
    return size;
  },
  reflection: {
    name: "BatchCall",
    fqn: "bebop.BatchCall",
    kind: BebopDefinitionKind.struct,
    detail: {
      fields: [
        { name: "call_id", index: 0, typeName: "number" },
        { name: "method_id", index: 0, typeName: "number" },
        { name: "payload", index: 0, typeName: "Uint8Array" },
        { name: "input_from", index: 0, typeName: "number" },
      ],
    },
  },
} satisfies BebopReflectableCodec<BatchCall>;

export type BatchRequest = {
  readonly calls: readonly BatchCall[];
  readonly metadata: ReadonlyMap<string, string>;
};

export const BatchRequest = {
  readFrom(reader: BebopReader): BatchRequest {
    return {
      calls: reader.readDynamicArray((_r) => BatchCall.readFrom(_r)),
      metadata: reader.readDynamicMap((_r) => _r.readString(), (_r) => _r.readString()),
    };
  },
  writeInto(writer: BebopWriter, value: BatchRequest): void {
    writer.writeDynamicArray(value.calls, (_w, _v) => {
      BatchCall.writeInto(_w, _v);
    });
    writer.writeDynamicMap(value.metadata, (_w, _k, _v) => {
      _w.writeString(_k);
      _w.writeString(_v);
    });
  },
  encodedSize(value: BatchRequest): number {
    let size = 0;
    size += 4;
    for (let i = 0; i < value.calls.length; i++) {
      const item = value.calls[i]!;
      size += BatchCall.encodedSize(item);
    }
    size += 4;
    value.metadata.forEach((_v, _k) => {
      size += 4 + new TextEncoder().encode(_k).length + 1;
      size += 4 + new TextEncoder().encode(_v).length + 1;
    });
    return size;
  },
  reflection: {
    name: "BatchRequest",
    fqn: "bebop.BatchRequest",
    kind: BebopDefinitionKind.struct,
    detail: {
      fields: [
        { name: "calls", index: 0, typeName: "readonly BatchCall[]" },
        { name: "metadata", index: 0, typeName: "ReadonlyMap<string, string>" },
      ],
    },
  },
} satisfies BebopReflectableCodec<BatchRequest>;

export type BatchSuccess = {
  readonly payloads: readonly Uint8Array[];
  readonly metadata: ReadonlyMap<string, string>;
};

export const BatchSuccess = {
  readFrom(reader: BebopReader): BatchSuccess {
    return {
      payloads: reader.readDynamicArray((_r) => _r.readUint8Array()),
      metadata: reader.readDynamicMap((_r) => _r.readString(), (_r) => _r.readString()),
    };
  },
  writeInto(writer: BebopWriter, value: BatchSuccess): void {
    writer.writeDynamicArray(value.payloads, (_w, _v) => {
      _w.writeUint8Array(_v);
    });
    writer.writeDynamicMap(value.metadata, (_w, _k, _v) => {
      _w.writeString(_k);
      _w.writeString(_v);
    });
  },
  encodedSize(value: BatchSuccess): number {
    let size = 0;
    size += 4;
    for (let i = 0; i < value.payloads.length; i++) {
      const item = value.payloads[i]!;
      size += 4 + item.length;
    }
    size += 4;
    value.metadata.forEach((_v, _k) => {
      size += 4 + new TextEncoder().encode(_k).length + 1;
      size += 4 + new TextEncoder().encode(_v).length + 1;
    });
    return size;
  },
  reflection: {
    name: "BatchSuccess",
    fqn: "bebop.BatchSuccess",
    kind: BebopDefinitionKind.struct,
    detail: {
      fields: [
        { name: "payloads", index: 0, typeName: "readonly Uint8Array[]" },
        { name: "metadata", index: 0, typeName: "ReadonlyMap<string, string>" },
      ],
    },
  },
} satisfies BebopReflectableCodec<BatchSuccess>;

export type BatchOutcome =
  | { readonly kind: "unknown"; readonly discriminator: number; readonly data: Uint8Array }
  | { readonly kind: "Success"; readonly value: BatchSuccess }
  | { readonly kind: "Error"; readonly value: RpcError }
;

export const BatchOutcome = {
  readFrom(reader: BebopReader): BatchOutcome {
    const end = reader.readMessageEnd();
    const discriminator = reader.readByte();
    switch (discriminator) {
      case 1: return { kind: "Success", value: BatchSuccess.readFrom(reader) };
      case 2: return { kind: "Error", value: RpcError.readFrom(reader) };
      default: return { kind: "unknown", discriminator, data: reader.readBytes(end - reader.index) };
    }
  },
  writeInto(writer: BebopWriter, value: BatchOutcome): void {
    const pos = writer.reserveMessageLength();
    switch (value.kind) {
      case "Success":
        writer.writeByte(1);
        BatchSuccess.writeInto(writer, value.value);
        break;
      case "Error":
        writer.writeByte(2);
        RpcError.writeInto(writer, value.value);
        break;
      case "unknown":
        writer.writeByte(value.discriminator);
        writer.writeBytes(value.data);
        break;
    }
    writer.fillMessageLength(pos);
  },
  encodedSize(value: BatchOutcome): number {
    switch (value.kind) {
      case "Success": return 5 + BatchSuccess.encodedSize(value.value);
      case "Error": return 5 + RpcError.encodedSize(value.value);
      case "unknown": return 5 + value.data.length;
    }
  },
  reflection: {
    name: "BatchOutcome",
    fqn: "bebop.BatchOutcome",
    kind: BebopDefinitionKind.union,
    detail: {
      branches: [
        { discriminator: 1, name: "Success", typeName: "BatchSuccess" },
        { discriminator: 2, name: "Error", typeName: "RpcError" },
      ],
    },
  },
} satisfies BebopReflectableCodec<BatchOutcome>;

export type BatchResult = {
  readonly callId: number;
  readonly outcome: BatchOutcome;
};

export const BatchResult = {
  readFrom(reader: BebopReader): BatchResult {
    return {
      callId: reader.readInt32(),
      outcome: BatchOutcome.readFrom(reader),
    };
  },
  writeInto(writer: BebopWriter, value: BatchResult): void {
    writer.writeInt32(value.callId);
    BatchOutcome.writeInto(writer, value.outcome);
  },
  encodedSize(value: BatchResult): number {
    let size = 0;
    size += 4;
    size += BatchOutcome.encodedSize(value.outcome);
    return size;
  },
  reflection: {
    name: "BatchResult",
    fqn: "bebop.BatchResult",
    kind: BebopDefinitionKind.struct,
    detail: {
      fields: [
        { name: "call_id", index: 0, typeName: "number" },
        { name: "outcome", index: 0, typeName: "BatchOutcome" },
      ],
    },
  },
} satisfies BebopReflectableCodec<BatchResult>;

export type BatchResponse = {
  readonly results: readonly BatchResult[];
};

export const BatchResponse = {
  readFrom(reader: BebopReader): BatchResponse {
    return {
      results: reader.readDynamicArray((_r) => BatchResult.readFrom(_r)),
    };
  },
  writeInto(writer: BebopWriter, value: BatchResponse): void {
    writer.writeDynamicArray(value.results, (_w, _v) => {
      BatchResult.writeInto(_w, _v);
    });
  },
  encodedSize(value: BatchResponse): number {
    let size = 0;
    size += 4;
    for (let i = 0; i < value.results.length; i++) {
      const item = value.results[i]!;
      size += BatchResult.encodedSize(item);
    }
    return size;
  },
  reflection: {
    name: "BatchResponse",
    fqn: "bebop.BatchResponse",
    kind: BebopDefinitionKind.struct,
    detail: {
      fields: [
        { name: "results", index: 0, typeName: "readonly BatchResult[]" },
      ],
    },
  },
} satisfies BebopReflectableCodec<BatchResponse>;

export type FutureDispatchRequest = {
  readonly methodId?: number | undefined;
  readonly payload?: Uint8Array | undefined;
  readonly idempotencyKey?: BebopUUID | undefined;
  readonly metadata?: ReadonlyMap<string, string> | undefined;
  readonly deadline?: BebopTimestamp | undefined;
  readonly discardResult?: boolean | undefined;
};

export const FutureDispatchRequest = {
  readFrom(reader: BebopReader): FutureDispatchRequest {
    const end = reader.readMessageEnd();
    let methodIdValue: number | undefined;
    let payloadValue: Uint8Array | undefined;
    let idempotencyKeyValue: BebopUUID | undefined;
    let metadataValue: ReadonlyMap<string, string> | undefined;
    let deadlineValue: BebopTimestamp | undefined;
    let discardResultValue: boolean | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: methodIdValue = reader.readUint32(); break;
        case 2: payloadValue = reader.readUint8Array(); break;
        case 3: idempotencyKeyValue = BebopUUID.readFrom(reader); break;
        case 4: metadataValue = reader.readDynamicMap((_r) => _r.readString(), (_r) => _r.readString()); break;
        case 5: deadlineValue = reader.readTimestamp(); break;
        case 6: discardResultValue = reader.readBool(); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      methodId: methodIdValue,
      payload: payloadValue,
      idempotencyKey: idempotencyKeyValue,
      metadata: metadataValue,
      deadline: deadlineValue,
      discardResult: discardResultValue,
    };
  },
  writeInto(writer: BebopWriter, value: FutureDispatchRequest): void {
    const pos = writer.reserveMessageLength();
    if (value.methodId !== undefined) {
      writer.writeTag(1);
      writer.writeUint32(value.methodId);
    }
    if (value.payload !== undefined) {
      writer.writeTag(2);
      writer.writeUint8Array(value.payload);
    }
    if (value.idempotencyKey !== undefined) {
      writer.writeTag(3);
      BebopUUID.writeInto(writer, value.idempotencyKey);
    }
    if (value.metadata !== undefined) {
      writer.writeTag(4);
      writer.writeDynamicMap(value.metadata, (_w, _k, _v) => {
        _w.writeString(_k);
        _w.writeString(_v);
      });
    }
    if (value.deadline !== undefined) {
      writer.writeTag(5);
      writer.writeTimestamp(value.deadline);
    }
    if (value.discardResult !== undefined) {
      writer.writeTag(6);
      writer.writeBool(value.discardResult);
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: FutureDispatchRequest): number {
    let size = 5;
    if (value.methodId !== undefined) {
      size += 1;
      size += 4;
    }
    if (value.payload !== undefined) {
      size += 1;
      size += 4 + value.payload.length;
    }
    if (value.idempotencyKey !== undefined) {
      size += 1;
      size += 16;
    }
    if (value.metadata !== undefined) {
      size += 1;
      size += 4;
      value.metadata.forEach((_v, _k) => {
        size += 4 + new TextEncoder().encode(_k).length + 1;
        size += 4 + new TextEncoder().encode(_v).length + 1;
      });
    }
    if (value.deadline !== undefined) {
      size += 1;
      size += 16;
    }
    if (value.discardResult !== undefined) {
      size += 1;
      size += 1;
    }
    return size;
  },
  reflection: {
    name: "FutureDispatchRequest",
    fqn: "bebop.FutureDispatchRequest",
    kind: BebopDefinitionKind.message,
    detail: {
      fields: [
        { name: "method_id", index: 1, typeName: "number" },
        { name: "payload", index: 2, typeName: "Uint8Array" },
        { name: "idempotency_key", index: 3, typeName: "BebopUUID" },
        { name: "metadata", index: 4, typeName: "ReadonlyMap<string, string>" },
        { name: "deadline", index: 5, typeName: "BebopTimestamp" },
        { name: "discard_result", index: 6, typeName: "boolean" },
      ],
    },
  },
} satisfies BebopReflectableCodec<FutureDispatchRequest>;

export type FutureHandle = {
  readonly id: BebopUUID;
};

export const FutureHandle = {
  readFrom(reader: BebopReader): FutureHandle {
    return {
      id: BebopUUID.readFrom(reader),
    };
  },
  writeInto(writer: BebopWriter, value: FutureHandle): void {
    BebopUUID.writeInto(writer, value.id);
  },
  encodedSize(value: FutureHandle): number {
    let size = 0;
    size += 16;
    return size;
  },
  reflection: {
    name: "FutureHandle",
    fqn: "bebop.FutureHandle",
    kind: BebopDefinitionKind.struct,
    detail: {
      fields: [
        { name: "id", index: 0, typeName: "BebopUUID" },
      ],
    },
  },
} satisfies BebopReflectableCodec<FutureHandle>;

export type FutureResolveRequest = {
  readonly ids?: readonly BebopUUID[] | undefined;
};

export const FutureResolveRequest = {
  readFrom(reader: BebopReader): FutureResolveRequest {
    const end = reader.readMessageEnd();
    let idsValue: readonly BebopUUID[] | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: idsValue = reader.readDynamicArray((_r) => BebopUUID.readFrom(_r)); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      ids: idsValue,
    };
  },
  writeInto(writer: BebopWriter, value: FutureResolveRequest): void {
    const pos = writer.reserveMessageLength();
    if (value.ids !== undefined) {
      writer.writeTag(1);
      writer.writeDynamicArray(value.ids, (_w, _v) => {
        BebopUUID.writeInto(_w, _v);
      });
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: FutureResolveRequest): number {
    let size = 5;
    if (value.ids !== undefined) {
      size += 1;
      size += 4;
      for (let i = 0; i < value.ids.length; i++) {
        const item = value.ids[i]!;
        size += 16;
      }
    }
    return size;
  },
  reflection: {
    name: "FutureResolveRequest",
    fqn: "bebop.FutureResolveRequest",
    kind: BebopDefinitionKind.message,
    detail: {
      fields: [
        { name: "ids", index: 1, typeName: "readonly BebopUUID[]" },
      ],
    },
  },
} satisfies BebopReflectableCodec<FutureResolveRequest>;

export type FutureSuccess = {
  readonly payload: Uint8Array;
  readonly metadata: ReadonlyMap<string, string>;
};

export const FutureSuccess = {
  readFrom(reader: BebopReader): FutureSuccess {
    return {
      payload: reader.readUint8Array(),
      metadata: reader.readDynamicMap((_r) => _r.readString(), (_r) => _r.readString()),
    };
  },
  writeInto(writer: BebopWriter, value: FutureSuccess): void {
    writer.writeUint8Array(value.payload);
    writer.writeDynamicMap(value.metadata, (_w, _k, _v) => {
      _w.writeString(_k);
      _w.writeString(_v);
    });
  },
  encodedSize(value: FutureSuccess): number {
    let size = 0;
    size += 4 + value.payload.length;
    size += 4;
    value.metadata.forEach((_v, _k) => {
      size += 4 + new TextEncoder().encode(_k).length + 1;
      size += 4 + new TextEncoder().encode(_v).length + 1;
    });
    return size;
  },
  reflection: {
    name: "FutureSuccess",
    fqn: "bebop.FutureSuccess",
    kind: BebopDefinitionKind.struct,
    detail: {
      fields: [
        { name: "payload", index: 0, typeName: "Uint8Array" },
        { name: "metadata", index: 0, typeName: "ReadonlyMap<string, string>" },
      ],
    },
  },
} satisfies BebopReflectableCodec<FutureSuccess>;

export type FutureOutcome =
  | { readonly kind: "unknown"; readonly discriminator: number; readonly data: Uint8Array }
  | { readonly kind: "Success"; readonly value: FutureSuccess }
  | { readonly kind: "Error"; readonly value: RpcError }
;

export const FutureOutcome = {
  readFrom(reader: BebopReader): FutureOutcome {
    const end = reader.readMessageEnd();
    const discriminator = reader.readByte();
    switch (discriminator) {
      case 1: return { kind: "Success", value: FutureSuccess.readFrom(reader) };
      case 2: return { kind: "Error", value: RpcError.readFrom(reader) };
      default: return { kind: "unknown", discriminator, data: reader.readBytes(end - reader.index) };
    }
  },
  writeInto(writer: BebopWriter, value: FutureOutcome): void {
    const pos = writer.reserveMessageLength();
    switch (value.kind) {
      case "Success":
        writer.writeByte(1);
        FutureSuccess.writeInto(writer, value.value);
        break;
      case "Error":
        writer.writeByte(2);
        RpcError.writeInto(writer, value.value);
        break;
      case "unknown":
        writer.writeByte(value.discriminator);
        writer.writeBytes(value.data);
        break;
    }
    writer.fillMessageLength(pos);
  },
  encodedSize(value: FutureOutcome): number {
    switch (value.kind) {
      case "Success": return 5 + FutureSuccess.encodedSize(value.value);
      case "Error": return 5 + RpcError.encodedSize(value.value);
      case "unknown": return 5 + value.data.length;
    }
  },
  reflection: {
    name: "FutureOutcome",
    fqn: "bebop.FutureOutcome",
    kind: BebopDefinitionKind.union,
    detail: {
      branches: [
        { discriminator: 1, name: "Success", typeName: "FutureSuccess" },
        { discriminator: 2, name: "Error", typeName: "RpcError" },
      ],
    },
  },
} satisfies BebopReflectableCodec<FutureOutcome>;

export type FutureResult = {
  readonly id: BebopUUID;
  readonly outcome: FutureOutcome;
};

export const FutureResult = {
  readFrom(reader: BebopReader): FutureResult {
    return {
      id: BebopUUID.readFrom(reader),
      outcome: FutureOutcome.readFrom(reader),
    };
  },
  writeInto(writer: BebopWriter, value: FutureResult): void {
    BebopUUID.writeInto(writer, value.id);
    FutureOutcome.writeInto(writer, value.outcome);
  },
  encodedSize(value: FutureResult): number {
    let size = 0;
    size += 16;
    size += FutureOutcome.encodedSize(value.outcome);
    return size;
  },
  reflection: {
    name: "FutureResult",
    fqn: "bebop.FutureResult",
    kind: BebopDefinitionKind.struct,
    detail: {
      fields: [
        { name: "id", index: 0, typeName: "BebopUUID" },
        { name: "outcome", index: 0, typeName: "FutureOutcome" },
      ],
    },
  },
} satisfies BebopReflectableCodec<FutureResult>;

export type FutureCancelRequest = {
  readonly id: BebopUUID;
};

export const FutureCancelRequest = {
  readFrom(reader: BebopReader): FutureCancelRequest {
    return {
      id: BebopUUID.readFrom(reader),
    };
  },
  writeInto(writer: BebopWriter, value: FutureCancelRequest): void {
    BebopUUID.writeInto(writer, value.id);
  },
  encodedSize(value: FutureCancelRequest): number {
    let size = 0;
    size += 16;
    return size;
  },
  reflection: {
    name: "FutureCancelRequest",
    fqn: "bebop.FutureCancelRequest",
    kind: BebopDefinitionKind.struct,
    detail: {
      fields: [
        { name: "id", index: 0, typeName: "BebopUUID" },
      ],
    },
  },
} satisfies BebopReflectableCodec<FutureCancelRequest>;

