// Code generated by bebopc-gen-typescript. DO NOT EDIT.
// source: ../../bebop/schemas/bebop/rpc.bop
// bebopc 2026.0.0-alpha.3

import { decode, encode } from "./codec.js";
import { messageEncodedSize, type BebopMessageView } from "./message.js";
import type { BebopGeneratedCodec, BebopTypeReflection } from "./reflection.js";
import { BebopTimestamp } from "./temporal.js";
import { BebopUUID } from "./uuid.js";
import { BebopStringView, BebopViewReader, readMessageField, type BebopArrayView, type BebopMapView } from "./view.js";
import { BebopReader, utf8ByteLength, type BebopReaderOptions, type BebopWriter } from "./wire.js";

export const StatusCode = {
  OK: 0,
  CANCELLED: 1,
  UNKNOWN: 2,
  INVALID_ARGUMENT: 3,
  DEADLINE_EXCEEDED: 4,
  NOT_FOUND: 5,
  PERMISSION_DENIED: 7,
  RESOURCE_EXHAUSTED: 8,
  UNIMPLEMENTED: 12,
  INTERNAL: 13,
  UNAVAILABLE: 14,
  UNAUTHENTICATED: 16,
} as const;
export type StatusCode = (typeof StatusCode)[keyof typeof StatusCode];

export const StatusCodeReflection = {
  name: "StatusCode",
  fqn: "bebop.StatusCode",
  kind: "enum",
  detail: {
    members: [
      { name: "OK", value: 0 },
      { name: "CANCELLED", value: 1 },
      { name: "UNKNOWN", value: 2 },
      { name: "INVALID_ARGUMENT", value: 3 },
      { name: "DEADLINE_EXCEEDED", value: 4 },
      { name: "NOT_FOUND", value: 5 },
      { name: "PERMISSION_DENIED", value: 7 },
      { name: "RESOURCE_EXHAUSTED", value: 8 },
      { name: "UNIMPLEMENTED", value: 12 },
      { name: "INTERNAL", value: 13 },
      { name: "UNAVAILABLE", value: 14 },
      { name: "UNAUTHENTICATED", value: 16 },
    ],
    isFlags: false,
  },
} as const satisfies BebopTypeReflection;

export const FrameFlags = {
  NONE: 0,
  END_STREAM: 1,
  ERROR: 2,
  COMPRESSED: 4,
  TRAILER: 8,
  CURSOR: 16,
} as const;
export type FrameFlags = number;

export const FrameFlagsReflection = {
  name: "FrameFlags",
  fqn: "bebop.FrameFlags",
  kind: "enum",
  detail: {
    members: [
      { name: "NONE", value: 0 },
      { name: "END_STREAM", value: 1 },
      { name: "ERROR", value: 2 },
      { name: "COMPRESSED", value: 4 },
      { name: "TRAILER", value: 8 },
      { name: "CURSOR", value: 16 },
    ],
    isFlags: true,
  },
} as const satisfies BebopTypeReflection;

export const MethodType = {
  UNARY: 0,
  SERVER_STREAM: 1,
  CLIENT_STREAM: 2,
  DUPLEX_STREAM: 3,
} as const;
export type MethodType = (typeof MethodType)[keyof typeof MethodType];

export const MethodTypeReflection = {
  name: "MethodType",
  fqn: "bebop.MethodType",
  kind: "enum",
  detail: {
    members: [
      { name: "UNARY", value: 0 },
      { name: "SERVER_STREAM", value: 1 },
      { name: "CLIENT_STREAM", value: 2 },
      { name: "DUPLEX_STREAM", value: 3 },
    ],
    isFlags: false,
  },
} as const satisfies BebopTypeReflection;

export type FrameHeader = {
  readonly length: number;
  readonly flags: FrameFlags;
  readonly streamId: number;
};

export class FrameHeaderView {
  readonly encoded: Uint8Array;
  readonly length: number;
  readonly flags: FrameFlags;
  readonly streamId: number;

  private constructor(encoded: Uint8Array, lengthValue: number, flagsValue: FrameFlags, streamIdValue: number) {
    this.encoded = encoded;
    this.length = lengthValue;
    this.flags = flagsValue;
    this.streamId = streamIdValue;
  }

  static readFrom(reader: BebopViewReader): FrameHeaderView {
    const start = reader.position;
    const lengthValue = reader.readUint32();
    const flagsValue = reader.readByte() as FrameFlags;
    const streamIdValue = reader.readUint32();
    return new FrameHeaderView(reader.encodedFrom(start), lengthValue, flagsValue, streamIdValue);
  }

  static skip(reader: BebopViewReader): void {
    reader.skip(4);
    reader.skip(1);
    reader.skip(4);
  }

  decoded(options?: BebopReaderOptions): FrameHeader {
    return FrameHeader.decode(this.encoded, options);
  }
}

export const FrameHeader = {
  encode(value: FrameHeader): Uint8Array {
    return encode(FrameHeader, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): FrameHeader {
    return decode(FrameHeader, bytes, options);
  },
  view(bytes: Uint8Array, options?: BebopReaderOptions): FrameHeaderView {
    const reader = new BebopViewReader(bytes, options);
    const view = FrameHeaderView.readFrom(reader);
    reader.finish();
    return view;
  },
  readView(reader: BebopViewReader): FrameHeaderView {
    return FrameHeaderView.readFrom(reader);
  },
  readFrom(reader: BebopReader): FrameHeader {
    return {
      length: reader.readUint32(),
      flags: reader.readByte() as FrameFlags,
      streamId: reader.readUint32(),
    };
  },
  writeInto(writer: BebopWriter, value: FrameHeader): void {
    writer.writeUint32(value.length);
    writer.writeByte(value.flags);
    writer.writeUint32(value.streamId);
  },
  encodedSize(_value: FrameHeader): number {
    let size = 0;
    size += 4;
    size += 1;
    size += 4;
    return size;
  },
  reflection: {
    name: "FrameHeader",
    fqn: "bebop.FrameHeader",
    kind: "struct",
    detail: {
      fields: [
        { name: "length", index: 0, typeName: "number" },
        { name: "flags", index: 0, typeName: "FrameFlags" },
        { name: "stream_id", index: 0, typeName: "number" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<FrameHeader, FrameHeaderView>;

export type CallHeader = {
  readonly methodId?: number | undefined;
  readonly deadline?: BebopTimestamp | undefined;
  readonly metadata?: ReadonlyMap<string, string> | undefined;
  readonly cursor?: bigint | undefined;
};

export class CallHeaderView {
  private constructor(private readonly message: BebopMessageView) {}

  get encoded(): Uint8Array { return this.message.encoded; }

  field(tag: number): Uint8Array | undefined {
    return this.message.field(tag);
  }

  get methodId(): number | undefined {
    return readMessageField(this.message, 1, (_r) => _r.readUint32());
  }

  get deadline(): BebopTimestamp | undefined {
    return readMessageField(this.message, 2, (_r) => _r.readTimestamp());
  }

  get metadata(): BebopMapView<BebopStringView, BebopStringView> | undefined {
    return readMessageField(this.message, 3, (_r) => _r.readMapView((_r) => _r.readStringView(), (_r) => _r.readStringView(), (_r) => _r.skipString(), (_r) => _r.skipString()));
  }

  get cursor(): bigint | undefined {
    return readMessageField(this.message, 4, (_r) => _r.readUint64());
  }

  static readFrom(reader: BebopViewReader): CallHeaderView {
    return new CallHeaderView(reader.readMessage());
  }

  static skip(reader: BebopViewReader): void {
    reader.skipMessage();
  }

  decoded(options?: BebopReaderOptions): CallHeader {
    return CallHeader.decode(this.encoded, options);
  }
}

export const CallHeader = {
  encode(value: CallHeader): Uint8Array {
    return encode(CallHeader, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): CallHeader {
    return decode(CallHeader, bytes, options);
  },
  view(bytes: Uint8Array, options?: BebopReaderOptions): CallHeaderView {
    const reader = new BebopViewReader(bytes, options);
    const view = CallHeaderView.readFrom(reader);
    reader.finish();
    return view;
  },
  readView(reader: BebopViewReader): CallHeaderView {
    return CallHeaderView.readFrom(reader);
  },
  readFrom(reader: BebopReader): CallHeader {
    const message = reader.readMessage();
    return {
      methodId: message.read(1, (_r) => _r.readUint32()),
      deadline: message.read(2, (_r) => _r.readTimestamp()),
      metadata: message.read(3, (_r) => _r.readDynamicMap((_r) => _r.readString(), (_r) => _r.readString())),
      cursor: message.read(4, (_r) => _r.readUint64()),
    };
  },
  writeInto(writer: BebopWriter, value: CallHeader): void {
    const message = writer.beginMessage();
    if (value.methodId !== undefined) {
      writer.markMessageField(message, 1);
      writer.writeUint32(value.methodId);
    }
    if (value.deadline !== undefined) {
      writer.markMessageField(message, 2);
      writer.writeTimestamp(value.deadline);
    }
    if (value.metadata !== undefined) {
      writer.markMessageField(message, 3);
      writer.writeDynamicMap(value.metadata, (_w, _k, _v) => {
        _w.writeString(_k);
        _w.writeString(_v);
      });
    }
    if (value.cursor !== undefined) {
      writer.markMessageField(message, 4);
      writer.writeUint64(value.cursor);
    }
    writer.endMessage(message);
  },
  encodedSize(value: CallHeader): number {
    let size = 0;
    let fieldCount = 0;
    let maxTag = 0;
    let blockMask = 0;
    if (value.methodId !== undefined) {
      fieldCount++;
      maxTag = 1;
      blockMask |= 1;
      size += 4;
    }
    if (value.deadline !== undefined) {
      fieldCount++;
      maxTag = 2;
      blockMask |= 1;
      size += 16;
    }
    if (value.metadata !== undefined) {
      fieldCount++;
      maxTag = 3;
      blockMask |= 1;
      size += 4;
      for (const [_k, _v] of value.metadata) {
        size += 5 + utf8ByteLength(_k);
        size += 5 + utf8ByteLength(_v);
      }
    }
    if (value.cursor !== undefined) {
      fieldCount++;
      maxTag = 4;
      blockMask |= 1;
      size += 8;
    }
    return messageEncodedSize(size, fieldCount, maxTag, blockMask);
  },
  reflection: {
    name: "CallHeader",
    fqn: "bebop.CallHeader",
    kind: "message",
    detail: {
      fields: [
        { name: "method_id", index: 1, typeName: "number" },
        { name: "deadline", index: 2, typeName: "BebopTimestamp" },
        { name: "metadata", index: 3, typeName: "ReadonlyMap<string, string>" },
        { name: "cursor", index: 4, typeName: "bigint" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<CallHeader, CallHeaderView>;

export type RpcError = {
  readonly code?: StatusCode | undefined;
  readonly detail?: string | undefined;
  readonly metadata?: ReadonlyMap<string, string> | undefined;
};

export class RpcErrorView {
  private constructor(private readonly message: BebopMessageView) {}

  get encoded(): Uint8Array { return this.message.encoded; }

  field(tag: number): Uint8Array | undefined {
    return this.message.field(tag);
  }

  get code(): StatusCode | undefined {
    return readMessageField(this.message, 1, (_r) => _r.readByte() as StatusCode);
  }

  get detail(): BebopStringView | undefined {
    return readMessageField(this.message, 2, (_r) => _r.readStringView());
  }

  get metadata(): BebopMapView<BebopStringView, BebopStringView> | undefined {
    return readMessageField(this.message, 3, (_r) => _r.readMapView((_r) => _r.readStringView(), (_r) => _r.readStringView(), (_r) => _r.skipString(), (_r) => _r.skipString()));
  }

  static readFrom(reader: BebopViewReader): RpcErrorView {
    return new RpcErrorView(reader.readMessage());
  }

  static skip(reader: BebopViewReader): void {
    reader.skipMessage();
  }

  decoded(options?: BebopReaderOptions): RpcError {
    return RpcError.decode(this.encoded, options);
  }
}

export const RpcError = {
  encode(value: RpcError): Uint8Array {
    return encode(RpcError, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): RpcError {
    return decode(RpcError, bytes, options);
  },
  view(bytes: Uint8Array, options?: BebopReaderOptions): RpcErrorView {
    const reader = new BebopViewReader(bytes, options);
    const view = RpcErrorView.readFrom(reader);
    reader.finish();
    return view;
  },
  readView(reader: BebopViewReader): RpcErrorView {
    return RpcErrorView.readFrom(reader);
  },
  readFrom(reader: BebopReader): RpcError {
    const message = reader.readMessage();
    return {
      code: message.read(1, (_r) => _r.readByte() as StatusCode),
      detail: message.read(2, (_r) => _r.readString()),
      metadata: message.read(3, (_r) => _r.readDynamicMap((_r) => _r.readString(), (_r) => _r.readString())),
    };
  },
  writeInto(writer: BebopWriter, value: RpcError): void {
    const message = writer.beginMessage();
    if (value.code !== undefined) {
      writer.markMessageField(message, 1);
      writer.writeByte(value.code);
    }
    if (value.detail !== undefined) {
      writer.markMessageField(message, 2);
      writer.writeString(value.detail);
    }
    if (value.metadata !== undefined) {
      writer.markMessageField(message, 3);
      writer.writeDynamicMap(value.metadata, (_w, _k, _v) => {
        _w.writeString(_k);
        _w.writeString(_v);
      });
    }
    writer.endMessage(message);
  },
  encodedSize(value: RpcError): number {
    let size = 0;
    let fieldCount = 0;
    let maxTag = 0;
    let blockMask = 0;
    if (value.code !== undefined) {
      fieldCount++;
      maxTag = 1;
      blockMask |= 1;
      size += 1;
    }
    if (value.detail !== undefined) {
      fieldCount++;
      maxTag = 2;
      blockMask |= 1;
      size += 5 + utf8ByteLength(value.detail);
    }
    if (value.metadata !== undefined) {
      fieldCount++;
      maxTag = 3;
      blockMask |= 1;
      size += 4;
      for (const [_k, _v] of value.metadata) {
        size += 5 + utf8ByteLength(_k);
        size += 5 + utf8ByteLength(_v);
      }
    }
    return messageEncodedSize(size, fieldCount, maxTag, blockMask);
  },
  reflection: {
    name: "RpcError",
    fqn: "bebop.RpcError",
    kind: "message",
    detail: {
      fields: [
        { name: "code", index: 1, typeName: "StatusCode" },
        { name: "detail", index: 2, typeName: "string" },
        { name: "metadata", index: 3, typeName: "ReadonlyMap<string, string>" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<RpcError, RpcErrorView>;

export type TrailingMetadata = {
  readonly metadata?: ReadonlyMap<string, string> | undefined;
};

export class TrailingMetadataView {
  private constructor(private readonly message: BebopMessageView) {}

  get encoded(): Uint8Array { return this.message.encoded; }

  field(tag: number): Uint8Array | undefined {
    return this.message.field(tag);
  }

  get metadata(): BebopMapView<BebopStringView, BebopStringView> | undefined {
    return readMessageField(this.message, 1, (_r) => _r.readMapView((_r) => _r.readStringView(), (_r) => _r.readStringView(), (_r) => _r.skipString(), (_r) => _r.skipString()));
  }

  static readFrom(reader: BebopViewReader): TrailingMetadataView {
    return new TrailingMetadataView(reader.readMessage());
  }

  static skip(reader: BebopViewReader): void {
    reader.skipMessage();
  }

  decoded(options?: BebopReaderOptions): TrailingMetadata {
    return TrailingMetadata.decode(this.encoded, options);
  }
}

export const TrailingMetadata = {
  encode(value: TrailingMetadata): Uint8Array {
    return encode(TrailingMetadata, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): TrailingMetadata {
    return decode(TrailingMetadata, bytes, options);
  },
  view(bytes: Uint8Array, options?: BebopReaderOptions): TrailingMetadataView {
    const reader = new BebopViewReader(bytes, options);
    const view = TrailingMetadataView.readFrom(reader);
    reader.finish();
    return view;
  },
  readView(reader: BebopViewReader): TrailingMetadataView {
    return TrailingMetadataView.readFrom(reader);
  },
  readFrom(reader: BebopReader): TrailingMetadata {
    const message = reader.readMessage();
    return {
      metadata: message.read(1, (_r) => _r.readDynamicMap((_r) => _r.readString(), (_r) => _r.readString())),
    };
  },
  writeInto(writer: BebopWriter, value: TrailingMetadata): void {
    const message = writer.beginMessage();
    if (value.metadata !== undefined) {
      writer.markMessageField(message, 1);
      writer.writeDynamicMap(value.metadata, (_w, _k, _v) => {
        _w.writeString(_k);
        _w.writeString(_v);
      });
    }
    writer.endMessage(message);
  },
  encodedSize(value: TrailingMetadata): number {
    let size = 0;
    let fieldCount = 0;
    let maxTag = 0;
    let blockMask = 0;
    if (value.metadata !== undefined) {
      fieldCount++;
      maxTag = 1;
      blockMask |= 1;
      size += 4;
      for (const [_k, _v] of value.metadata) {
        size += 5 + utf8ByteLength(_k);
        size += 5 + utf8ByteLength(_v);
      }
    }
    return messageEncodedSize(size, fieldCount, maxTag, blockMask);
  },
  reflection: {
    name: "TrailingMetadata",
    fqn: "bebop.TrailingMetadata",
    kind: "message",
    detail: {
      fields: [
        { name: "metadata", index: 1, typeName: "ReadonlyMap<string, string>" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<TrailingMetadata, TrailingMetadataView>;

export type MethodInfo = {
  readonly name: string;
  readonly methodId: number;
  readonly methodType: MethodType;
  readonly requestTypeUrl: string;
  readonly responseTypeUrl: string;
};

export class MethodInfoView {
  readonly encoded: Uint8Array;
  readonly name: BebopStringView;
  readonly methodId: number;
  readonly methodType: MethodType;
  readonly requestTypeUrl: BebopStringView;
  readonly responseTypeUrl: BebopStringView;

  private constructor(encoded: Uint8Array, nameValue: BebopStringView, methodIdValue: number, methodTypeValue: MethodType, requestTypeUrlValue: BebopStringView, responseTypeUrlValue: BebopStringView) {
    this.encoded = encoded;
    this.name = nameValue;
    this.methodId = methodIdValue;
    this.methodType = methodTypeValue;
    this.requestTypeUrl = requestTypeUrlValue;
    this.responseTypeUrl = responseTypeUrlValue;
  }

  static readFrom(reader: BebopViewReader): MethodInfoView {
    const start = reader.position;
    const nameValue = reader.readStringView();
    const methodIdValue = reader.readUint32();
    const methodTypeValue = reader.readByte() as MethodType;
    const requestTypeUrlValue = reader.readStringView();
    const responseTypeUrlValue = reader.readStringView();
    return new MethodInfoView(reader.encodedFrom(start), nameValue, methodIdValue, methodTypeValue, requestTypeUrlValue, responseTypeUrlValue);
  }

  static skip(reader: BebopViewReader): void {
    reader.skipString();
    reader.skip(4);
    reader.skip(1);
    reader.skipString();
    reader.skipString();
  }

  decoded(options?: BebopReaderOptions): MethodInfo {
    return MethodInfo.decode(this.encoded, options);
  }
}

export const MethodInfo = {
  encode(value: MethodInfo): Uint8Array {
    return encode(MethodInfo, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): MethodInfo {
    return decode(MethodInfo, bytes, options);
  },
  view(bytes: Uint8Array, options?: BebopReaderOptions): MethodInfoView {
    const reader = new BebopViewReader(bytes, options);
    const view = MethodInfoView.readFrom(reader);
    reader.finish();
    return view;
  },
  readView(reader: BebopViewReader): MethodInfoView {
    return MethodInfoView.readFrom(reader);
  },
  readFrom(reader: BebopReader): MethodInfo {
    return {
      name: reader.readString(),
      methodId: reader.readUint32(),
      methodType: reader.readByte() as MethodType,
      requestTypeUrl: reader.readString(),
      responseTypeUrl: reader.readString(),
    };
  },
  writeInto(writer: BebopWriter, value: MethodInfo): void {
    writer.writeString(value.name);
    writer.writeUint32(value.methodId);
    writer.writeByte(value.methodType);
    writer.writeString(value.requestTypeUrl);
    writer.writeString(value.responseTypeUrl);
  },
  encodedSize(value: MethodInfo): number {
    let size = 0;
    size += 5 + utf8ByteLength(value.name);
    size += 4;
    size += 1;
    size += 5 + utf8ByteLength(value.requestTypeUrl);
    size += 5 + utf8ByteLength(value.responseTypeUrl);
    return size;
  },
  reflection: {
    name: "MethodInfo",
    fqn: "bebop.MethodInfo",
    kind: "struct",
    detail: {
      fields: [
        { name: "name", index: 0, typeName: "string" },
        { name: "method_id", index: 0, typeName: "number" },
        { name: "method_type", index: 0, typeName: "MethodType" },
        { name: "request_type_url", index: 0, typeName: "string" },
        { name: "response_type_url", index: 0, typeName: "string" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<MethodInfo, MethodInfoView>;

export type ServiceInfo = {
  readonly name: string;
  readonly methods: readonly MethodInfo[];
};

export class ServiceInfoView {
  readonly encoded: Uint8Array;
  readonly name: BebopStringView;
  readonly methods: BebopArrayView<MethodInfoView>;

  private constructor(encoded: Uint8Array, nameValue: BebopStringView, methodsValue: BebopArrayView<MethodInfoView>) {
    this.encoded = encoded;
    this.name = nameValue;
    this.methods = methodsValue;
  }

  static readFrom(reader: BebopViewReader): ServiceInfoView {
    const start = reader.position;
    const nameValue = reader.readStringView();
    const methodsValue = reader.readArrayView((_r) => _r.readNestedView(MethodInfoView), undefined, (_r) => _r.skipNestedView(MethodInfoView));
    return new ServiceInfoView(reader.encodedFrom(start), nameValue, methodsValue);
  }

  static skip(reader: BebopViewReader): void {
    reader.skipString();
    reader.skipArray((_r) => _r.skipNestedView(MethodInfoView));
  }

  decoded(options?: BebopReaderOptions): ServiceInfo {
    return ServiceInfo.decode(this.encoded, options);
  }
}

export const ServiceInfo = {
  encode(value: ServiceInfo): Uint8Array {
    return encode(ServiceInfo, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): ServiceInfo {
    return decode(ServiceInfo, bytes, options);
  },
  view(bytes: Uint8Array, options?: BebopReaderOptions): ServiceInfoView {
    const reader = new BebopViewReader(bytes, options);
    const view = ServiceInfoView.readFrom(reader);
    reader.finish();
    return view;
  },
  readView(reader: BebopViewReader): ServiceInfoView {
    return ServiceInfoView.readFrom(reader);
  },
  readFrom(reader: BebopReader): ServiceInfo {
    return {
      name: reader.readString(),
      methods: reader.readDynamicArray((_r) => _r.readNested(MethodInfo)),
    };
  },
  writeInto(writer: BebopWriter, value: ServiceInfo): void {
    writer.writeString(value.name);
    writer.writeDynamicArray(value.methods, (_w, _v) => {
      MethodInfo.writeInto(_w, _v);
    });
  },
  encodedSize(value: ServiceInfo): number {
    let size = 0;
    size += 5 + utf8ByteLength(value.name);
    size += 4;
    for (let _i0 = 0; _i0 < value.methods.length; _i0++) {
      const _item1 = value.methods[_i0]!;
      size += MethodInfo.encodedSize(_item1);
    }
    return size;
  },
  reflection: {
    name: "ServiceInfo",
    fqn: "bebop.ServiceInfo",
    kind: "struct",
    detail: {
      fields: [
        { name: "name", index: 0, typeName: "string" },
        { name: "methods", index: 0, typeName: "readonly MethodInfo[]" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<ServiceInfo, ServiceInfoView>;

export type DiscoveryResponse = {
  readonly services: readonly ServiceInfo[];
};

export class DiscoveryResponseView {
  readonly encoded: Uint8Array;
  readonly services: BebopArrayView<ServiceInfoView>;

  private constructor(encoded: Uint8Array, servicesValue: BebopArrayView<ServiceInfoView>) {
    this.encoded = encoded;
    this.services = servicesValue;
  }

  static readFrom(reader: BebopViewReader): DiscoveryResponseView {
    const start = reader.position;
    const servicesValue = reader.readArrayView((_r) => _r.readNestedView(ServiceInfoView), undefined, (_r) => _r.skipNestedView(ServiceInfoView));
    return new DiscoveryResponseView(reader.encodedFrom(start), servicesValue);
  }

  static skip(reader: BebopViewReader): void {
    reader.skipArray((_r) => _r.skipNestedView(ServiceInfoView));
  }

  decoded(options?: BebopReaderOptions): DiscoveryResponse {
    return DiscoveryResponse.decode(this.encoded, options);
  }
}

export const DiscoveryResponse = {
  encode(value: DiscoveryResponse): Uint8Array {
    return encode(DiscoveryResponse, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): DiscoveryResponse {
    return decode(DiscoveryResponse, bytes, options);
  },
  view(bytes: Uint8Array, options?: BebopReaderOptions): DiscoveryResponseView {
    const reader = new BebopViewReader(bytes, options);
    const view = DiscoveryResponseView.readFrom(reader);
    reader.finish();
    return view;
  },
  readView(reader: BebopViewReader): DiscoveryResponseView {
    return DiscoveryResponseView.readFrom(reader);
  },
  readFrom(reader: BebopReader): DiscoveryResponse {
    return {
      services: reader.readDynamicArray((_r) => _r.readNested(ServiceInfo)),
    };
  },
  writeInto(writer: BebopWriter, value: DiscoveryResponse): void {
    writer.writeDynamicArray(value.services, (_w, _v) => {
      ServiceInfo.writeInto(_w, _v);
    });
  },
  encodedSize(value: DiscoveryResponse): number {
    let size = 0;
    size += 4;
    for (let _i2 = 0; _i2 < value.services.length; _i2++) {
      const _item3 = value.services[_i2]!;
      size += ServiceInfo.encodedSize(_item3);
    }
    return size;
  },
  reflection: {
    name: "DiscoveryResponse",
    fqn: "bebop.DiscoveryResponse",
    kind: "struct",
    detail: {
      fields: [
        { name: "services", index: 0, typeName: "readonly ServiceInfo[]" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<DiscoveryResponse, DiscoveryResponseView>;

export type BatchCall = {
  readonly callId: number;
  readonly methodId: number;
  readonly payload: Uint8Array;
  readonly inputFrom: number;
};

export class BatchCallView {
  readonly encoded: Uint8Array;
  readonly callId: number;
  readonly methodId: number;
  readonly payload: BebopArrayView<number>;
  readonly inputFrom: number;

  private constructor(encoded: Uint8Array, callIdValue: number, methodIdValue: number, payloadValue: BebopArrayView<number>, inputFromValue: number) {
    this.encoded = encoded;
    this.callId = callIdValue;
    this.methodId = methodIdValue;
    this.payload = payloadValue;
    this.inputFrom = inputFromValue;
  }

  static readFrom(reader: BebopViewReader): BatchCallView {
    const start = reader.position;
    const callIdValue = reader.readInt32();
    const methodIdValue = reader.readUint32();
    const payloadValue = reader.readArrayView((_r) => _r.readByte(), 1);
    const inputFromValue = reader.readInt32();
    return new BatchCallView(reader.encodedFrom(start), callIdValue, methodIdValue, payloadValue, inputFromValue);
  }

  static skip(reader: BebopViewReader): void {
    reader.skip(4);
    reader.skip(4);
    reader.skipArray((_r) => _r.skip(1), 1);
    reader.skip(4);
  }

  decoded(options?: BebopReaderOptions): BatchCall {
    return BatchCall.decode(this.encoded, options);
  }
}

export const BatchCall = {
  encode(value: BatchCall): Uint8Array {
    return encode(BatchCall, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): BatchCall {
    return decode(BatchCall, bytes, options);
  },
  view(bytes: Uint8Array, options?: BebopReaderOptions): BatchCallView {
    const reader = new BebopViewReader(bytes, options);
    const view = BatchCallView.readFrom(reader);
    reader.finish();
    return view;
  },
  readView(reader: BebopViewReader): BatchCallView {
    return BatchCallView.readFrom(reader);
  },
  readFrom(reader: BebopReader): BatchCall {
    return {
      callId: reader.readInt32(),
      methodId: reader.readUint32(),
      payload: reader.readUint8Array(),
      inputFrom: reader.readInt32(),
    };
  },
  writeInto(writer: BebopWriter, value: BatchCall): void {
    writer.writeInt32(value.callId);
    writer.writeUint32(value.methodId);
    writer.writeUint8Array(value.payload);
    writer.writeInt32(value.inputFrom);
  },
  encodedSize(value: BatchCall): number {
    let size = 0;
    size += 4;
    size += 4;
    size += 4 + value.payload.length;
    size += 4;
    return size;
  },
  reflection: {
    name: "BatchCall",
    fqn: "bebop.BatchCall",
    kind: "struct",
    detail: {
      fields: [
        { name: "call_id", index: 0, typeName: "number" },
        { name: "method_id", index: 0, typeName: "number" },
        { name: "payload", index: 0, typeName: "Uint8Array" },
        { name: "input_from", index: 0, typeName: "number" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<BatchCall, BatchCallView>;

export type BatchRequest = {
  readonly calls: readonly BatchCall[];
  readonly metadata: ReadonlyMap<string, string>;
};

export class BatchRequestView {
  readonly encoded: Uint8Array;
  readonly calls: BebopArrayView<BatchCallView>;
  readonly metadata: BebopMapView<BebopStringView, BebopStringView>;

  private constructor(encoded: Uint8Array, callsValue: BebopArrayView<BatchCallView>, metadataValue: BebopMapView<BebopStringView, BebopStringView>) {
    this.encoded = encoded;
    this.calls = callsValue;
    this.metadata = metadataValue;
  }

  static readFrom(reader: BebopViewReader): BatchRequestView {
    const start = reader.position;
    const callsValue = reader.readArrayView((_r) => _r.readNestedView(BatchCallView), undefined, (_r) => _r.skipNestedView(BatchCallView));
    const metadataValue = reader.readMapView((_r) => _r.readStringView(), (_r) => _r.readStringView(), (_r) => _r.skipString(), (_r) => _r.skipString());
    return new BatchRequestView(reader.encodedFrom(start), callsValue, metadataValue);
  }

  static skip(reader: BebopViewReader): void {
    reader.skipArray((_r) => _r.skipNestedView(BatchCallView));
    reader.skipMap((_r) => _r.skipString(), (_r) => _r.skipString());
  }

  decoded(options?: BebopReaderOptions): BatchRequest {
    return BatchRequest.decode(this.encoded, options);
  }
}

export const BatchRequest = {
  encode(value: BatchRequest): Uint8Array {
    return encode(BatchRequest, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): BatchRequest {
    return decode(BatchRequest, bytes, options);
  },
  view(bytes: Uint8Array, options?: BebopReaderOptions): BatchRequestView {
    const reader = new BebopViewReader(bytes, options);
    const view = BatchRequestView.readFrom(reader);
    reader.finish();
    return view;
  },
  readView(reader: BebopViewReader): BatchRequestView {
    return BatchRequestView.readFrom(reader);
  },
  readFrom(reader: BebopReader): BatchRequest {
    return {
      calls: reader.readDynamicArray((_r) => _r.readNested(BatchCall)),
      metadata: reader.readDynamicMap((_r) => _r.readString(), (_r) => _r.readString()),
    };
  },
  writeInto(writer: BebopWriter, value: BatchRequest): void {
    writer.writeDynamicArray(value.calls, (_w, _v) => {
      BatchCall.writeInto(_w, _v);
    });
    writer.writeDynamicMap(value.metadata, (_w, _k, _v) => {
      _w.writeString(_k);
      _w.writeString(_v);
    });
  },
  encodedSize(value: BatchRequest): number {
    let size = 0;
    size += 4;
    for (let _i4 = 0; _i4 < value.calls.length; _i4++) {
      const _item5 = value.calls[_i4]!;
      size += BatchCall.encodedSize(_item5);
    }
    size += 4;
    for (const [_k, _v] of value.metadata) {
      size += 5 + utf8ByteLength(_k);
      size += 5 + utf8ByteLength(_v);
    }
    return size;
  },
  reflection: {
    name: "BatchRequest",
    fqn: "bebop.BatchRequest",
    kind: "struct",
    detail: {
      fields: [
        { name: "calls", index: 0, typeName: "readonly BatchCall[]" },
        { name: "metadata", index: 0, typeName: "ReadonlyMap<string, string>" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<BatchRequest, BatchRequestView>;

export type BatchSuccess = {
  readonly payloads: readonly Uint8Array[];
  readonly metadata: ReadonlyMap<string, string>;
};

export class BatchSuccessView {
  readonly encoded: Uint8Array;
  readonly payloads: BebopArrayView<BebopArrayView<number>>;
  readonly metadata: BebopMapView<BebopStringView, BebopStringView>;

  private constructor(encoded: Uint8Array, payloadsValue: BebopArrayView<BebopArrayView<number>>, metadataValue: BebopMapView<BebopStringView, BebopStringView>) {
    this.encoded = encoded;
    this.payloads = payloadsValue;
    this.metadata = metadataValue;
  }

  static readFrom(reader: BebopViewReader): BatchSuccessView {
    const start = reader.position;
    const payloadsValue = reader.readArrayView((_r) => _r.readArrayView((_r) => _r.readByte(), 1), undefined, (_r) => _r.skipArray((_r) => _r.skip(1), 1));
    const metadataValue = reader.readMapView((_r) => _r.readStringView(), (_r) => _r.readStringView(), (_r) => _r.skipString(), (_r) => _r.skipString());
    return new BatchSuccessView(reader.encodedFrom(start), payloadsValue, metadataValue);
  }

  static skip(reader: BebopViewReader): void {
    reader.skipArray((_r) => _r.skipArray((_r) => _r.skip(1), 1));
    reader.skipMap((_r) => _r.skipString(), (_r) => _r.skipString());
  }

  decoded(options?: BebopReaderOptions): BatchSuccess {
    return BatchSuccess.decode(this.encoded, options);
  }
}

export const BatchSuccess = {
  encode(value: BatchSuccess): Uint8Array {
    return encode(BatchSuccess, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): BatchSuccess {
    return decode(BatchSuccess, bytes, options);
  },
  view(bytes: Uint8Array, options?: BebopReaderOptions): BatchSuccessView {
    const reader = new BebopViewReader(bytes, options);
    const view = BatchSuccessView.readFrom(reader);
    reader.finish();
    return view;
  },
  readView(reader: BebopViewReader): BatchSuccessView {
    return BatchSuccessView.readFrom(reader);
  },
  readFrom(reader: BebopReader): BatchSuccess {
    return {
      payloads: reader.readDynamicArray((_r) => _r.readUint8Array()),
      metadata: reader.readDynamicMap((_r) => _r.readString(), (_r) => _r.readString()),
    };
  },
  writeInto(writer: BebopWriter, value: BatchSuccess): void {
    writer.writeDynamicArray(value.payloads, (_w, _v) => {
      _w.writeUint8Array(_v);
    });
    writer.writeDynamicMap(value.metadata, (_w, _k, _v) => {
      _w.writeString(_k);
      _w.writeString(_v);
    });
  },
  encodedSize(value: BatchSuccess): number {
    let size = 0;
    size += 4;
    for (let _i6 = 0; _i6 < value.payloads.length; _i6++) {
      const _item7 = value.payloads[_i6]!;
      size += 4 + _item7.length;
    }
    size += 4;
    for (const [_k, _v] of value.metadata) {
      size += 5 + utf8ByteLength(_k);
      size += 5 + utf8ByteLength(_v);
    }
    return size;
  },
  reflection: {
    name: "BatchSuccess",
    fqn: "bebop.BatchSuccess",
    kind: "struct",
    detail: {
      fields: [
        { name: "payloads", index: 0, typeName: "readonly Uint8Array[]" },
        { name: "metadata", index: 0, typeName: "ReadonlyMap<string, string>" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<BatchSuccess, BatchSuccessView>;

export type BatchOutcome =
  | { readonly kind: "unknown"; readonly discriminator: number; readonly data: Uint8Array }
  | { readonly kind: "success"; readonly value: BatchSuccess }
  | { readonly kind: "error"; readonly value: RpcError };

export type BatchOutcomeView =
  | {
    readonly encoded: Uint8Array;
    readonly kind: "unknown";
    readonly discriminator: number;
    readonly data: Uint8Array;
    decoded(options?: BebopReaderOptions): BatchOutcome;
  }
  | {
    readonly encoded: Uint8Array;
    readonly kind: "success";
    readonly value: BatchSuccessView;
    decoded(options?: BebopReaderOptions): BatchOutcome;
  }
  | {
    readonly encoded: Uint8Array;
    readonly kind: "error";
    readonly value: RpcErrorView;
    decoded(options?: BebopReaderOptions): BatchOutcome;
  };

export const BatchOutcomeView = {
  readFrom(reader: BebopViewReader): BatchOutcomeView {
    const result = reader.readLengthPrefixedValue((_r) => {
      const discriminator = _r.readByte();
      switch (discriminator) {
        case 1: return { kind: "success" as const, value: _r.readNestedView(BatchSuccessView) };
        case 2: return { kind: "error" as const, value: _r.readNestedView(RpcErrorView) };
        default: return { kind: "unknown" as const, discriminator, data: _r.readView(_r.remaining) };
      }
    });
    return {
      encoded: result.encoded,
      ...result.value,
      decoded(options?: BebopReaderOptions): BatchOutcome {
        return BatchOutcome.decode(this.encoded, options);
      },
    };
  },
  skip(reader: BebopViewReader): void {
    reader.skipLengthPrefixed();
  },
} as const;

export const BatchOutcome = {
  encode(value: BatchOutcome): Uint8Array {
    return encode(BatchOutcome, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): BatchOutcome {
    return decode(BatchOutcome, bytes, options);
  },
  view(bytes: Uint8Array, options?: BebopReaderOptions): BatchOutcomeView {
    const reader = new BebopViewReader(bytes, options);
    const view = BatchOutcomeView.readFrom(reader);
    reader.finish();
    return view;
  },
  readView(reader: BebopViewReader): BatchOutcomeView {
    return BatchOutcomeView.readFrom(reader);
  },
  readFrom(reader: BebopReader): BatchOutcome {
    return reader.readLengthPrefixed((valueReader) => {
      const discriminator = valueReader.readByte();
      switch (discriminator) {
        case 1: return { kind: "success", value: valueReader.readNested(BatchSuccess) };
        case 2: return { kind: "error", value: valueReader.readNested(RpcError) };
        default: return { kind: "unknown", discriminator, data: valueReader.readBytes(valueReader.length - valueReader.index) };
      }
    });
  },
  writeInto(writer: BebopWriter, value: BatchOutcome): void {
    const position = writer.beginLengthPrefixed();
    switch (value.kind) {
      case "success":
        writer.writeByte(1);
        BatchSuccess.writeInto(writer, value.value);
        break;
      case "error":
        writer.writeByte(2);
        RpcError.writeInto(writer, value.value);
        break;
      case "unknown":
        writer.writeByte(value.discriminator);
        writer.writeBytes(value.data);
        break;
    }
    writer.endLengthPrefixed(position);
  },
  encodedSize(value: BatchOutcome): number {
    switch (value.kind) {
      case "success": return 5 + BatchSuccess.encodedSize(value.value);
      case "error": return 5 + RpcError.encodedSize(value.value);
      case "unknown": return 5 + value.data.length;
    }
  },
  reflection: {
    name: "BatchOutcome",
    fqn: "bebop.BatchOutcome",
    kind: "union",
    detail: {
      branches: [
        { discriminator: 1, name: "Success", typeName: "BatchSuccess" },
        { discriminator: 2, name: "Error", typeName: "RpcError" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<BatchOutcome, BatchOutcomeView>;

export type BatchResult = {
  readonly callId: number;
  readonly outcome: BatchOutcome;
};

export class BatchResultView {
  readonly encoded: Uint8Array;
  readonly callId: number;
  readonly outcome: BatchOutcomeView;

  private constructor(encoded: Uint8Array, callIdValue: number, outcomeValue: BatchOutcomeView) {
    this.encoded = encoded;
    this.callId = callIdValue;
    this.outcome = outcomeValue;
  }

  static readFrom(reader: BebopViewReader): BatchResultView {
    const start = reader.position;
    const callIdValue = reader.readInt32();
    const outcomeValue = reader.readNestedView(BatchOutcomeView);
    return new BatchResultView(reader.encodedFrom(start), callIdValue, outcomeValue);
  }

  static skip(reader: BebopViewReader): void {
    reader.skip(4);
    reader.skipNestedView(BatchOutcomeView);
  }

  decoded(options?: BebopReaderOptions): BatchResult {
    return BatchResult.decode(this.encoded, options);
  }
}

export const BatchResult = {
  encode(value: BatchResult): Uint8Array {
    return encode(BatchResult, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): BatchResult {
    return decode(BatchResult, bytes, options);
  },
  view(bytes: Uint8Array, options?: BebopReaderOptions): BatchResultView {
    const reader = new BebopViewReader(bytes, options);
    const view = BatchResultView.readFrom(reader);
    reader.finish();
    return view;
  },
  readView(reader: BebopViewReader): BatchResultView {
    return BatchResultView.readFrom(reader);
  },
  readFrom(reader: BebopReader): BatchResult {
    return {
      callId: reader.readInt32(),
      outcome: reader.readNested(BatchOutcome),
    };
  },
  writeInto(writer: BebopWriter, value: BatchResult): void {
    writer.writeInt32(value.callId);
    BatchOutcome.writeInto(writer, value.outcome);
  },
  encodedSize(value: BatchResult): number {
    let size = 0;
    size += 4;
    size += BatchOutcome.encodedSize(value.outcome);
    return size;
  },
  reflection: {
    name: "BatchResult",
    fqn: "bebop.BatchResult",
    kind: "struct",
    detail: {
      fields: [
        { name: "call_id", index: 0, typeName: "number" },
        { name: "outcome", index: 0, typeName: "BatchOutcome" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<BatchResult, BatchResultView>;

export type BatchResponse = {
  readonly results: readonly BatchResult[];
};

export class BatchResponseView {
  readonly encoded: Uint8Array;
  readonly results: BebopArrayView<BatchResultView>;

  private constructor(encoded: Uint8Array, resultsValue: BebopArrayView<BatchResultView>) {
    this.encoded = encoded;
    this.results = resultsValue;
  }

  static readFrom(reader: BebopViewReader): BatchResponseView {
    const start = reader.position;
    const resultsValue = reader.readArrayView((_r) => _r.readNestedView(BatchResultView), undefined, (_r) => _r.skipNestedView(BatchResultView));
    return new BatchResponseView(reader.encodedFrom(start), resultsValue);
  }

  static skip(reader: BebopViewReader): void {
    reader.skipArray((_r) => _r.skipNestedView(BatchResultView));
  }

  decoded(options?: BebopReaderOptions): BatchResponse {
    return BatchResponse.decode(this.encoded, options);
  }
}

export const BatchResponse = {
  encode(value: BatchResponse): Uint8Array {
    return encode(BatchResponse, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): BatchResponse {
    return decode(BatchResponse, bytes, options);
  },
  view(bytes: Uint8Array, options?: BebopReaderOptions): BatchResponseView {
    const reader = new BebopViewReader(bytes, options);
    const view = BatchResponseView.readFrom(reader);
    reader.finish();
    return view;
  },
  readView(reader: BebopViewReader): BatchResponseView {
    return BatchResponseView.readFrom(reader);
  },
  readFrom(reader: BebopReader): BatchResponse {
    return {
      results: reader.readDynamicArray((_r) => _r.readNested(BatchResult)),
    };
  },
  writeInto(writer: BebopWriter, value: BatchResponse): void {
    writer.writeDynamicArray(value.results, (_w, _v) => {
      BatchResult.writeInto(_w, _v);
    });
  },
  encodedSize(value: BatchResponse): number {
    let size = 0;
    size += 4;
    for (let _i8 = 0; _i8 < value.results.length; _i8++) {
      const _item9 = value.results[_i8]!;
      size += BatchResult.encodedSize(_item9);
    }
    return size;
  },
  reflection: {
    name: "BatchResponse",
    fqn: "bebop.BatchResponse",
    kind: "struct",
    detail: {
      fields: [
        { name: "results", index: 0, typeName: "readonly BatchResult[]" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<BatchResponse, BatchResponseView>;

export type FutureDispatchRequest = {
  readonly methodId?: number | undefined;
  readonly payload?: Uint8Array | undefined;
  readonly idempotencyKey?: BebopUUID | undefined;
  readonly metadata?: ReadonlyMap<string, string> | undefined;
  readonly deadline?: BebopTimestamp | undefined;
  readonly discardResult?: boolean | undefined;
};

export class FutureDispatchRequestView {
  private constructor(private readonly message: BebopMessageView) {}

  get encoded(): Uint8Array { return this.message.encoded; }

  field(tag: number): Uint8Array | undefined {
    return this.message.field(tag);
  }

  get methodId(): number | undefined {
    return readMessageField(this.message, 1, (_r) => _r.readUint32());
  }

  get payload(): BebopArrayView<number> | undefined {
    return readMessageField(this.message, 2, (_r) => _r.readArrayView((_r) => _r.readByte(), 1));
  }

  get idempotencyKey(): BebopUUID | undefined {
    return readMessageField(this.message, 3, (_r) => _r.readUUID());
  }

  get metadata(): BebopMapView<BebopStringView, BebopStringView> | undefined {
    return readMessageField(this.message, 4, (_r) => _r.readMapView((_r) => _r.readStringView(), (_r) => _r.readStringView(), (_r) => _r.skipString(), (_r) => _r.skipString()));
  }

  get deadline(): BebopTimestamp | undefined {
    return readMessageField(this.message, 5, (_r) => _r.readTimestamp());
  }

  get discardResult(): boolean | undefined {
    return readMessageField(this.message, 6, (_r) => _r.readBool());
  }

  static readFrom(reader: BebopViewReader): FutureDispatchRequestView {
    return new FutureDispatchRequestView(reader.readMessage());
  }

  static skip(reader: BebopViewReader): void {
    reader.skipMessage();
  }

  decoded(options?: BebopReaderOptions): FutureDispatchRequest {
    return FutureDispatchRequest.decode(this.encoded, options);
  }
}

export const FutureDispatchRequest = {
  encode(value: FutureDispatchRequest): Uint8Array {
    return encode(FutureDispatchRequest, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): FutureDispatchRequest {
    return decode(FutureDispatchRequest, bytes, options);
  },
  view(bytes: Uint8Array, options?: BebopReaderOptions): FutureDispatchRequestView {
    const reader = new BebopViewReader(bytes, options);
    const view = FutureDispatchRequestView.readFrom(reader);
    reader.finish();
    return view;
  },
  readView(reader: BebopViewReader): FutureDispatchRequestView {
    return FutureDispatchRequestView.readFrom(reader);
  },
  readFrom(reader: BebopReader): FutureDispatchRequest {
    const message = reader.readMessage();
    return {
      methodId: message.read(1, (_r) => _r.readUint32()),
      payload: message.read(2, (_r) => _r.readUint8Array()),
      idempotencyKey: message.read(3, (_r) => BebopUUID.readFrom(_r)),
      metadata: message.read(4, (_r) => _r.readDynamicMap((_r) => _r.readString(), (_r) => _r.readString())),
      deadline: message.read(5, (_r) => _r.readTimestamp()),
      discardResult: message.read(6, (_r) => _r.readBool()),
    };
  },
  writeInto(writer: BebopWriter, value: FutureDispatchRequest): void {
    const message = writer.beginMessage();
    if (value.methodId !== undefined) {
      writer.markMessageField(message, 1);
      writer.writeUint32(value.methodId);
    }
    if (value.payload !== undefined) {
      writer.markMessageField(message, 2);
      writer.writeUint8Array(value.payload);
    }
    if (value.idempotencyKey !== undefined) {
      writer.markMessageField(message, 3);
      BebopUUID.writeInto(writer, value.idempotencyKey);
    }
    if (value.metadata !== undefined) {
      writer.markMessageField(message, 4);
      writer.writeDynamicMap(value.metadata, (_w, _k, _v) => {
        _w.writeString(_k);
        _w.writeString(_v);
      });
    }
    if (value.deadline !== undefined) {
      writer.markMessageField(message, 5);
      writer.writeTimestamp(value.deadline);
    }
    if (value.discardResult !== undefined) {
      writer.markMessageField(message, 6);
      writer.writeBool(value.discardResult);
    }
    writer.endMessage(message);
  },
  encodedSize(value: FutureDispatchRequest): number {
    let size = 0;
    let fieldCount = 0;
    let maxTag = 0;
    let blockMask = 0;
    if (value.methodId !== undefined) {
      fieldCount++;
      maxTag = 1;
      blockMask |= 1;
      size += 4;
    }
    if (value.payload !== undefined) {
      fieldCount++;
      maxTag = 2;
      blockMask |= 1;
      size += 4 + value.payload.length;
    }
    if (value.idempotencyKey !== undefined) {
      fieldCount++;
      maxTag = 3;
      blockMask |= 1;
      size += 16;
    }
    if (value.metadata !== undefined) {
      fieldCount++;
      maxTag = 4;
      blockMask |= 1;
      size += 4;
      for (const [_k, _v] of value.metadata) {
        size += 5 + utf8ByteLength(_k);
        size += 5 + utf8ByteLength(_v);
      }
    }
    if (value.deadline !== undefined) {
      fieldCount++;
      maxTag = 5;
      blockMask |= 1;
      size += 16;
    }
    if (value.discardResult !== undefined) {
      fieldCount++;
      maxTag = 6;
      blockMask |= 1;
      size += 1;
    }
    return messageEncodedSize(size, fieldCount, maxTag, blockMask);
  },
  reflection: {
    name: "FutureDispatchRequest",
    fqn: "bebop.FutureDispatchRequest",
    kind: "message",
    detail: {
      fields: [
        { name: "method_id", index: 1, typeName: "number" },
        { name: "payload", index: 2, typeName: "Uint8Array" },
        { name: "idempotency_key", index: 3, typeName: "BebopUUID" },
        { name: "metadata", index: 4, typeName: "ReadonlyMap<string, string>" },
        { name: "deadline", index: 5, typeName: "BebopTimestamp" },
        { name: "discard_result", index: 6, typeName: "boolean" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<FutureDispatchRequest, FutureDispatchRequestView>;

export type FutureHandle = {
  readonly id: BebopUUID;
};

export class FutureHandleView {
  readonly encoded: Uint8Array;
  readonly id: BebopUUID;

  private constructor(encoded: Uint8Array, idValue: BebopUUID) {
    this.encoded = encoded;
    this.id = idValue;
  }

  static readFrom(reader: BebopViewReader): FutureHandleView {
    const start = reader.position;
    const idValue = reader.readUUID();
    return new FutureHandleView(reader.encodedFrom(start), idValue);
  }

  static skip(reader: BebopViewReader): void {
    reader.skip(16);
  }

  decoded(options?: BebopReaderOptions): FutureHandle {
    return FutureHandle.decode(this.encoded, options);
  }
}

export const FutureHandle = {
  encode(value: FutureHandle): Uint8Array {
    return encode(FutureHandle, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): FutureHandle {
    return decode(FutureHandle, bytes, options);
  },
  view(bytes: Uint8Array, options?: BebopReaderOptions): FutureHandleView {
    const reader = new BebopViewReader(bytes, options);
    const view = FutureHandleView.readFrom(reader);
    reader.finish();
    return view;
  },
  readView(reader: BebopViewReader): FutureHandleView {
    return FutureHandleView.readFrom(reader);
  },
  readFrom(reader: BebopReader): FutureHandle {
    return {
      id: BebopUUID.readFrom(reader),
    };
  },
  writeInto(writer: BebopWriter, value: FutureHandle): void {
    BebopUUID.writeInto(writer, value.id);
  },
  encodedSize(_value: FutureHandle): number {
    let size = 0;
    size += 16;
    return size;
  },
  reflection: {
    name: "FutureHandle",
    fqn: "bebop.FutureHandle",
    kind: "struct",
    detail: {
      fields: [
        { name: "id", index: 0, typeName: "BebopUUID" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<FutureHandle, FutureHandleView>;

export type FutureResolveRequest = {
  readonly ids?: readonly BebopUUID[] | undefined;
};

export class FutureResolveRequestView {
  private constructor(private readonly message: BebopMessageView) {}

  get encoded(): Uint8Array { return this.message.encoded; }

  field(tag: number): Uint8Array | undefined {
    return this.message.field(tag);
  }

  get ids(): BebopArrayView<BebopUUID> | undefined {
    return readMessageField(this.message, 1, (_r) => _r.readArrayView((_r) => _r.readUUID(), 16));
  }

  static readFrom(reader: BebopViewReader): FutureResolveRequestView {
    return new FutureResolveRequestView(reader.readMessage());
  }

  static skip(reader: BebopViewReader): void {
    reader.skipMessage();
  }

  decoded(options?: BebopReaderOptions): FutureResolveRequest {
    return FutureResolveRequest.decode(this.encoded, options);
  }
}

export const FutureResolveRequest = {
  encode(value: FutureResolveRequest): Uint8Array {
    return encode(FutureResolveRequest, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): FutureResolveRequest {
    return decode(FutureResolveRequest, bytes, options);
  },
  view(bytes: Uint8Array, options?: BebopReaderOptions): FutureResolveRequestView {
    const reader = new BebopViewReader(bytes, options);
    const view = FutureResolveRequestView.readFrom(reader);
    reader.finish();
    return view;
  },
  readView(reader: BebopViewReader): FutureResolveRequestView {
    return FutureResolveRequestView.readFrom(reader);
  },
  readFrom(reader: BebopReader): FutureResolveRequest {
    const message = reader.readMessage();
    return {
      ids: message.read(1, (_r) => _r.readDynamicArray((_r) => BebopUUID.readFrom(_r))),
    };
  },
  writeInto(writer: BebopWriter, value: FutureResolveRequest): void {
    const message = writer.beginMessage();
    if (value.ids !== undefined) {
      writer.markMessageField(message, 1);
      writer.writeDynamicArray(value.ids, (_w, _v) => {
        BebopUUID.writeInto(_w, _v);
      });
    }
    writer.endMessage(message);
  },
  encodedSize(value: FutureResolveRequest): number {
    let size = 0;
    let fieldCount = 0;
    let maxTag = 0;
    let blockMask = 0;
    if (value.ids !== undefined) {
      fieldCount++;
      maxTag = 1;
      blockMask |= 1;
      size += 4 + value.ids.length * 16;
    }
    return messageEncodedSize(size, fieldCount, maxTag, blockMask);
  },
  reflection: {
    name: "FutureResolveRequest",
    fqn: "bebop.FutureResolveRequest",
    kind: "message",
    detail: {
      fields: [
        { name: "ids", index: 1, typeName: "readonly BebopUUID[]" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<FutureResolveRequest, FutureResolveRequestView>;

export type FutureSuccess = {
  readonly payload: Uint8Array;
  readonly metadata: ReadonlyMap<string, string>;
};

export class FutureSuccessView {
  readonly encoded: Uint8Array;
  readonly payload: BebopArrayView<number>;
  readonly metadata: BebopMapView<BebopStringView, BebopStringView>;

  private constructor(encoded: Uint8Array, payloadValue: BebopArrayView<number>, metadataValue: BebopMapView<BebopStringView, BebopStringView>) {
    this.encoded = encoded;
    this.payload = payloadValue;
    this.metadata = metadataValue;
  }

  static readFrom(reader: BebopViewReader): FutureSuccessView {
    const start = reader.position;
    const payloadValue = reader.readArrayView((_r) => _r.readByte(), 1);
    const metadataValue = reader.readMapView((_r) => _r.readStringView(), (_r) => _r.readStringView(), (_r) => _r.skipString(), (_r) => _r.skipString());
    return new FutureSuccessView(reader.encodedFrom(start), payloadValue, metadataValue);
  }

  static skip(reader: BebopViewReader): void {
    reader.skipArray((_r) => _r.skip(1), 1);
    reader.skipMap((_r) => _r.skipString(), (_r) => _r.skipString());
  }

  decoded(options?: BebopReaderOptions): FutureSuccess {
    return FutureSuccess.decode(this.encoded, options);
  }
}

export const FutureSuccess = {
  encode(value: FutureSuccess): Uint8Array {
    return encode(FutureSuccess, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): FutureSuccess {
    return decode(FutureSuccess, bytes, options);
  },
  view(bytes: Uint8Array, options?: BebopReaderOptions): FutureSuccessView {
    const reader = new BebopViewReader(bytes, options);
    const view = FutureSuccessView.readFrom(reader);
    reader.finish();
    return view;
  },
  readView(reader: BebopViewReader): FutureSuccessView {
    return FutureSuccessView.readFrom(reader);
  },
  readFrom(reader: BebopReader): FutureSuccess {
    return {
      payload: reader.readUint8Array(),
      metadata: reader.readDynamicMap((_r) => _r.readString(), (_r) => _r.readString()),
    };
  },
  writeInto(writer: BebopWriter, value: FutureSuccess): void {
    writer.writeUint8Array(value.payload);
    writer.writeDynamicMap(value.metadata, (_w, _k, _v) => {
      _w.writeString(_k);
      _w.writeString(_v);
    });
  },
  encodedSize(value: FutureSuccess): number {
    let size = 0;
    size += 4 + value.payload.length;
    size += 4;
    for (const [_k, _v] of value.metadata) {
      size += 5 + utf8ByteLength(_k);
      size += 5 + utf8ByteLength(_v);
    }
    return size;
  },
  reflection: {
    name: "FutureSuccess",
    fqn: "bebop.FutureSuccess",
    kind: "struct",
    detail: {
      fields: [
        { name: "payload", index: 0, typeName: "Uint8Array" },
        { name: "metadata", index: 0, typeName: "ReadonlyMap<string, string>" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<FutureSuccess, FutureSuccessView>;

export type FutureOutcome =
  | { readonly kind: "unknown"; readonly discriminator: number; readonly data: Uint8Array }
  | { readonly kind: "success"; readonly value: FutureSuccess }
  | { readonly kind: "error"; readonly value: RpcError };

export type FutureOutcomeView =
  | {
    readonly encoded: Uint8Array;
    readonly kind: "unknown";
    readonly discriminator: number;
    readonly data: Uint8Array;
    decoded(options?: BebopReaderOptions): FutureOutcome;
  }
  | {
    readonly encoded: Uint8Array;
    readonly kind: "success";
    readonly value: FutureSuccessView;
    decoded(options?: BebopReaderOptions): FutureOutcome;
  }
  | {
    readonly encoded: Uint8Array;
    readonly kind: "error";
    readonly value: RpcErrorView;
    decoded(options?: BebopReaderOptions): FutureOutcome;
  };

export const FutureOutcomeView = {
  readFrom(reader: BebopViewReader): FutureOutcomeView {
    const result = reader.readLengthPrefixedValue((_r) => {
      const discriminator = _r.readByte();
      switch (discriminator) {
        case 1: return { kind: "success" as const, value: _r.readNestedView(FutureSuccessView) };
        case 2: return { kind: "error" as const, value: _r.readNestedView(RpcErrorView) };
        default: return { kind: "unknown" as const, discriminator, data: _r.readView(_r.remaining) };
      }
    });
    return {
      encoded: result.encoded,
      ...result.value,
      decoded(options?: BebopReaderOptions): FutureOutcome {
        return FutureOutcome.decode(this.encoded, options);
      },
    };
  },
  skip(reader: BebopViewReader): void {
    reader.skipLengthPrefixed();
  },
} as const;

export const FutureOutcome = {
  encode(value: FutureOutcome): Uint8Array {
    return encode(FutureOutcome, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): FutureOutcome {
    return decode(FutureOutcome, bytes, options);
  },
  view(bytes: Uint8Array, options?: BebopReaderOptions): FutureOutcomeView {
    const reader = new BebopViewReader(bytes, options);
    const view = FutureOutcomeView.readFrom(reader);
    reader.finish();
    return view;
  },
  readView(reader: BebopViewReader): FutureOutcomeView {
    return FutureOutcomeView.readFrom(reader);
  },
  readFrom(reader: BebopReader): FutureOutcome {
    return reader.readLengthPrefixed((valueReader) => {
      const discriminator = valueReader.readByte();
      switch (discriminator) {
        case 1: return { kind: "success", value: valueReader.readNested(FutureSuccess) };
        case 2: return { kind: "error", value: valueReader.readNested(RpcError) };
        default: return { kind: "unknown", discriminator, data: valueReader.readBytes(valueReader.length - valueReader.index) };
      }
    });
  },
  writeInto(writer: BebopWriter, value: FutureOutcome): void {
    const position = writer.beginLengthPrefixed();
    switch (value.kind) {
      case "success":
        writer.writeByte(1);
        FutureSuccess.writeInto(writer, value.value);
        break;
      case "error":
        writer.writeByte(2);
        RpcError.writeInto(writer, value.value);
        break;
      case "unknown":
        writer.writeByte(value.discriminator);
        writer.writeBytes(value.data);
        break;
    }
    writer.endLengthPrefixed(position);
  },
  encodedSize(value: FutureOutcome): number {
    switch (value.kind) {
      case "success": return 5 + FutureSuccess.encodedSize(value.value);
      case "error": return 5 + RpcError.encodedSize(value.value);
      case "unknown": return 5 + value.data.length;
    }
  },
  reflection: {
    name: "FutureOutcome",
    fqn: "bebop.FutureOutcome",
    kind: "union",
    detail: {
      branches: [
        { discriminator: 1, name: "Success", typeName: "FutureSuccess" },
        { discriminator: 2, name: "Error", typeName: "RpcError" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<FutureOutcome, FutureOutcomeView>;

export type FutureResult = {
  readonly id: BebopUUID;
  readonly outcome: FutureOutcome;
};

export class FutureResultView {
  readonly encoded: Uint8Array;
  readonly id: BebopUUID;
  readonly outcome: FutureOutcomeView;

  private constructor(encoded: Uint8Array, idValue: BebopUUID, outcomeValue: FutureOutcomeView) {
    this.encoded = encoded;
    this.id = idValue;
    this.outcome = outcomeValue;
  }

  static readFrom(reader: BebopViewReader): FutureResultView {
    const start = reader.position;
    const idValue = reader.readUUID();
    const outcomeValue = reader.readNestedView(FutureOutcomeView);
    return new FutureResultView(reader.encodedFrom(start), idValue, outcomeValue);
  }

  static skip(reader: BebopViewReader): void {
    reader.skip(16);
    reader.skipNestedView(FutureOutcomeView);
  }

  decoded(options?: BebopReaderOptions): FutureResult {
    return FutureResult.decode(this.encoded, options);
  }
}

export const FutureResult = {
  encode(value: FutureResult): Uint8Array {
    return encode(FutureResult, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): FutureResult {
    return decode(FutureResult, bytes, options);
  },
  view(bytes: Uint8Array, options?: BebopReaderOptions): FutureResultView {
    const reader = new BebopViewReader(bytes, options);
    const view = FutureResultView.readFrom(reader);
    reader.finish();
    return view;
  },
  readView(reader: BebopViewReader): FutureResultView {
    return FutureResultView.readFrom(reader);
  },
  readFrom(reader: BebopReader): FutureResult {
    return {
      id: BebopUUID.readFrom(reader),
      outcome: reader.readNested(FutureOutcome),
    };
  },
  writeInto(writer: BebopWriter, value: FutureResult): void {
    BebopUUID.writeInto(writer, value.id);
    FutureOutcome.writeInto(writer, value.outcome);
  },
  encodedSize(value: FutureResult): number {
    let size = 0;
    size += 16;
    size += FutureOutcome.encodedSize(value.outcome);
    return size;
  },
  reflection: {
    name: "FutureResult",
    fqn: "bebop.FutureResult",
    kind: "struct",
    detail: {
      fields: [
        { name: "id", index: 0, typeName: "BebopUUID" },
        { name: "outcome", index: 0, typeName: "FutureOutcome" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<FutureResult, FutureResultView>;

export type FutureCancelRequest = {
  readonly id: BebopUUID;
};

export class FutureCancelRequestView {
  readonly encoded: Uint8Array;
  readonly id: BebopUUID;

  private constructor(encoded: Uint8Array, idValue: BebopUUID) {
    this.encoded = encoded;
    this.id = idValue;
  }

  static readFrom(reader: BebopViewReader): FutureCancelRequestView {
    const start = reader.position;
    const idValue = reader.readUUID();
    return new FutureCancelRequestView(reader.encodedFrom(start), idValue);
  }

  static skip(reader: BebopViewReader): void {
    reader.skip(16);
  }

  decoded(options?: BebopReaderOptions): FutureCancelRequest {
    return FutureCancelRequest.decode(this.encoded, options);
  }
}

export const FutureCancelRequest = {
  encode(value: FutureCancelRequest): Uint8Array {
    return encode(FutureCancelRequest, value);
  },
  decode(bytes: Uint8Array, options?: BebopReaderOptions): FutureCancelRequest {
    return decode(FutureCancelRequest, bytes, options);
  },
  view(bytes: Uint8Array, options?: BebopReaderOptions): FutureCancelRequestView {
    const reader = new BebopViewReader(bytes, options);
    const view = FutureCancelRequestView.readFrom(reader);
    reader.finish();
    return view;
  },
  readView(reader: BebopViewReader): FutureCancelRequestView {
    return FutureCancelRequestView.readFrom(reader);
  },
  readFrom(reader: BebopReader): FutureCancelRequest {
    return {
      id: BebopUUID.readFrom(reader),
    };
  },
  writeInto(writer: BebopWriter, value: FutureCancelRequest): void {
    BebopUUID.writeInto(writer, value.id);
  },
  encodedSize(_value: FutureCancelRequest): number {
    let size = 0;
    size += 16;
    return size;
  },
  reflection: {
    name: "FutureCancelRequest",
    fqn: "bebop.FutureCancelRequest",
    kind: "struct",
    detail: {
      fields: [
        { name: "id", index: 0, typeName: "BebopUUID" },
      ],
    },
  },
} satisfies BebopGeneratedCodec<FutureCancelRequest, FutureCancelRequestView>;
