// Code generated by bebopc-gen-typescript. DO NOT EDIT.
// source: bebop/schemas/bebop/descriptor.bop
// bebopc 2026.0.0-alpha.3

import { BebopDefinitionKind, BebopDuration, BebopRuntimeError, BebopTimestamp, BebopUUID } from "@bebop/runtime";
import type { BebopReader, BebopReflectableCodec, BebopWriter } from "@bebop/runtime";


export const TypeKind = {
  UNKNOWN: 0,
  BOOL: 1,
  BYTE: 2,
  INT8: 3,
  INT16: 4,
  UINT16: 5,
  INT32: 6,
  UINT32: 7,
  INT64: 8,
  UINT64: 9,
  INT128: 10,
  UINT128: 11,
  FLOAT16: 12,
  FLOAT32: 13,
  FLOAT64: 14,
  BFLOAT16: 15,
  STRING: 16,
  UUID: 17,
  TIMESTAMP: 18,
  DURATION: 19,
  ARRAY: 20,
  FIXED_ARRAY: 21,
  MAP: 22,
  DEFINED: 23,
} as const;
export type TypeKind = (typeof TypeKind)[keyof typeof TypeKind];

export const DefinitionKind = {
  UNKNOWN: 0,
  ENUM: 1,
  STRUCT: 2,
  MESSAGE: 3,
  UNION: 4,
  SERVICE: 5,
  CONST: 6,
  DECORATOR: 7,
} as const;
export type DefinitionKind = (typeof DefinitionKind)[keyof typeof DefinitionKind];

export const MethodType = {
  UNKNOWN: 0,
  UNARY: 1,
  SERVER_STREAM: 2,
  CLIENT_STREAM: 3,
  DUPLEX_STREAM: 4,
} as const;
export type MethodType = (typeof MethodType)[keyof typeof MethodType];

export const Visibility = {
  DEFAULT: 0,
  EXPORT: 1,
  LOCAL: 2,
} as const;
export type Visibility = (typeof Visibility)[keyof typeof Visibility];

export const LiteralKind = {
  UNKNOWN: 0,
  BOOL: 1,
  INT: 2,
  FLOAT: 3,
  STRING: 4,
  UUID: 5,
  BYTES: 6,
  TIMESTAMP: 7,
  DURATION: 8,
} as const;
export type LiteralKind = (typeof LiteralKind)[keyof typeof LiteralKind];

export const DecoratorTarget = {
  NONE: 0,
  ENUM: 1,
  STRUCT: 2,
  MESSAGE: 4,
  UNION: 8,
  FIELD: 16,
  SERVICE: 32,
  METHOD: 64,
  BRANCH: 128,
  ALL: 255,
} as const;
export type DecoratorTarget = number;

export const Edition = {
  UNKNOWN: 0,
  EDITION_2026: 1000,
  MAX: 2147483647,
} as const;
export type Edition = (typeof Edition)[keyof typeof Edition];

export type TypeDescriptor = {
  readonly kind?: TypeKind | undefined;
  readonly arrayElement?: TypeDescriptor | undefined;
  readonly fixedArrayElement?: TypeDescriptor | undefined;
  readonly fixedArraySize?: number | undefined;
  readonly mapKey?: TypeDescriptor | undefined;
  readonly mapValue?: TypeDescriptor | undefined;
  readonly definedFqn?: string | undefined;
};

export const TypeDescriptor = {
  readFrom(reader: BebopReader): TypeDescriptor {
    const end = reader.readMessageEnd();
    let kindValue: TypeKind | undefined;
    let arrayElementValue: TypeDescriptor | undefined;
    let fixedArrayElementValue: TypeDescriptor | undefined;
    let fixedArraySizeValue: number | undefined;
    let mapKeyValue: TypeDescriptor | undefined;
    let mapValueValue: TypeDescriptor | undefined;
    let definedFqnValue: string | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: kindValue = reader.readByte() as TypeKind; break;
        case 2: arrayElementValue = TypeDescriptor.readFrom(reader); break;
        case 3: fixedArrayElementValue = TypeDescriptor.readFrom(reader); break;
        case 4: fixedArraySizeValue = reader.readUint32(); break;
        case 5: mapKeyValue = TypeDescriptor.readFrom(reader); break;
        case 6: mapValueValue = TypeDescriptor.readFrom(reader); break;
        case 7: definedFqnValue = reader.readString(); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      kind: kindValue,
      arrayElement: arrayElementValue,
      fixedArrayElement: fixedArrayElementValue,
      fixedArraySize: fixedArraySizeValue,
      mapKey: mapKeyValue,
      mapValue: mapValueValue,
      definedFqn: definedFqnValue,
    };
  },
  writeInto(writer: BebopWriter, value: TypeDescriptor): void {
    const pos = writer.reserveMessageLength();
    if (value.kind !== undefined) {
      writer.writeTag(1);
      writer.writeByte(value.kind);
    }
    if (value.arrayElement !== undefined) {
      writer.writeTag(2);
      TypeDescriptor.writeInto(writer, value.arrayElement);
    }
    if (value.fixedArrayElement !== undefined) {
      writer.writeTag(3);
      TypeDescriptor.writeInto(writer, value.fixedArrayElement);
    }
    if (value.fixedArraySize !== undefined) {
      writer.writeTag(4);
      writer.writeUint32(value.fixedArraySize);
    }
    if (value.mapKey !== undefined) {
      writer.writeTag(5);
      TypeDescriptor.writeInto(writer, value.mapKey);
    }
    if (value.mapValue !== undefined) {
      writer.writeTag(6);
      TypeDescriptor.writeInto(writer, value.mapValue);
    }
    if (value.definedFqn !== undefined) {
      writer.writeTag(7);
      writer.writeString(value.definedFqn);
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: TypeDescriptor): number {
    let size = 5;
    if (value.kind !== undefined) {
      size += 1;
      size += 1;
    }
    if (value.arrayElement !== undefined) {
      size += 1;
      size += TypeDescriptor.encodedSize(value.arrayElement);
    }
    if (value.fixedArrayElement !== undefined) {
      size += 1;
      size += TypeDescriptor.encodedSize(value.fixedArrayElement);
    }
    if (value.fixedArraySize !== undefined) {
      size += 1;
      size += 4;
    }
    if (value.mapKey !== undefined) {
      size += 1;
      size += TypeDescriptor.encodedSize(value.mapKey);
    }
    if (value.mapValue !== undefined) {
      size += 1;
      size += TypeDescriptor.encodedSize(value.mapValue);
    }
    if (value.definedFqn !== undefined) {
      size += 1;
      size += 4 + new TextEncoder().encode(value.definedFqn).length + 1;
    }
    return size;
  },
  reflection: {
    name: "TypeDescriptor",
    fqn: "bebop.TypeDescriptor",
    kind: BebopDefinitionKind.message,
    detail: {
      fields: [
        { name: "kind", index: 1, typeName: "TypeKind" },
        { name: "array_element", index: 2, typeName: "TypeDescriptor" },
        { name: "fixed_array_element", index: 3, typeName: "TypeDescriptor" },
        { name: "fixed_array_size", index: 4, typeName: "number" },
        { name: "map_key", index: 5, typeName: "TypeDescriptor" },
        { name: "map_value", index: 6, typeName: "TypeDescriptor" },
        { name: "defined_fqn", index: 7, typeName: "string" },
      ],
    },
  },
} satisfies BebopReflectableCodec<TypeDescriptor>;

export type LiteralValue = {
  readonly kind?: LiteralKind | undefined;
  readonly boolValue?: boolean | undefined;
  readonly intValue?: bigint | undefined;
  readonly floatValue?: number | undefined;
  readonly stringValue?: string | undefined;
  readonly uuidValue?: BebopUUID | undefined;
  readonly rawValue?: string | undefined;
  readonly bytesValue?: Uint8Array | undefined;
  readonly timestampValue?: BebopTimestamp | undefined;
  readonly durationValue?: BebopDuration | undefined;
};

export const LiteralValue = {
  readFrom(reader: BebopReader): LiteralValue {
    const end = reader.readMessageEnd();
    let kindValue: LiteralKind | undefined;
    let boolValueValue: boolean | undefined;
    let intValueValue: bigint | undefined;
    let floatValueValue: number | undefined;
    let stringValueValue: string | undefined;
    let uuidValueValue: BebopUUID | undefined;
    let rawValueValue: string | undefined;
    let bytesValueValue: Uint8Array | undefined;
    let timestampValueValue: BebopTimestamp | undefined;
    let durationValueValue: BebopDuration | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: kindValue = reader.readByte() as LiteralKind; break;
        case 2: boolValueValue = reader.readBool(); break;
        case 3: intValueValue = reader.readInt64(); break;
        case 4: floatValueValue = reader.readFloat64(); break;
        case 5: stringValueValue = reader.readString(); break;
        case 6: uuidValueValue = BebopUUID.readFrom(reader); break;
        case 7: rawValueValue = reader.readString(); break;
        case 8: bytesValueValue = reader.readUint8Array(); break;
        case 9: timestampValueValue = reader.readTimestamp(); break;
        case 10: durationValueValue = reader.readDuration(); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      kind: kindValue,
      boolValue: boolValueValue,
      intValue: intValueValue,
      floatValue: floatValueValue,
      stringValue: stringValueValue,
      uuidValue: uuidValueValue,
      rawValue: rawValueValue,
      bytesValue: bytesValueValue,
      timestampValue: timestampValueValue,
      durationValue: durationValueValue,
    };
  },
  writeInto(writer: BebopWriter, value: LiteralValue): void {
    const pos = writer.reserveMessageLength();
    if (value.kind !== undefined) {
      writer.writeTag(1);
      writer.writeByte(value.kind);
    }
    if (value.boolValue !== undefined) {
      writer.writeTag(2);
      writer.writeBool(value.boolValue);
    }
    if (value.intValue !== undefined) {
      writer.writeTag(3);
      writer.writeInt64(value.intValue);
    }
    if (value.floatValue !== undefined) {
      writer.writeTag(4);
      writer.writeFloat64(value.floatValue);
    }
    if (value.stringValue !== undefined) {
      writer.writeTag(5);
      writer.writeString(value.stringValue);
    }
    if (value.uuidValue !== undefined) {
      writer.writeTag(6);
      BebopUUID.writeInto(writer, value.uuidValue);
    }
    if (value.rawValue !== undefined) {
      writer.writeTag(7);
      writer.writeString(value.rawValue);
    }
    if (value.bytesValue !== undefined) {
      writer.writeTag(8);
      writer.writeUint8Array(value.bytesValue);
    }
    if (value.timestampValue !== undefined) {
      writer.writeTag(9);
      writer.writeTimestamp(value.timestampValue);
    }
    if (value.durationValue !== undefined) {
      writer.writeTag(10);
      writer.writeDuration(value.durationValue);
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: LiteralValue): number {
    let size = 5;
    if (value.kind !== undefined) {
      size += 1;
      size += 1;
    }
    if (value.boolValue !== undefined) {
      size += 1;
      size += 1;
    }
    if (value.intValue !== undefined) {
      size += 1;
      size += 8;
    }
    if (value.floatValue !== undefined) {
      size += 1;
      size += 8;
    }
    if (value.stringValue !== undefined) {
      size += 1;
      size += 4 + new TextEncoder().encode(value.stringValue).length + 1;
    }
    if (value.uuidValue !== undefined) {
      size += 1;
      size += 16;
    }
    if (value.rawValue !== undefined) {
      size += 1;
      size += 4 + new TextEncoder().encode(value.rawValue).length + 1;
    }
    if (value.bytesValue !== undefined) {
      size += 1;
      size += 4 + value.bytesValue.length;
    }
    if (value.timestampValue !== undefined) {
      size += 1;
      size += 16;
    }
    if (value.durationValue !== undefined) {
      size += 1;
      size += 12;
    }
    return size;
  },
  reflection: {
    name: "LiteralValue",
    fqn: "bebop.LiteralValue",
    kind: BebopDefinitionKind.message,
    detail: {
      fields: [
        { name: "kind", index: 1, typeName: "LiteralKind" },
        { name: "bool_value", index: 2, typeName: "boolean" },
        { name: "int_value", index: 3, typeName: "bigint" },
        { name: "float_value", index: 4, typeName: "number" },
        { name: "string_value", index: 5, typeName: "string" },
        { name: "uuid_value", index: 6, typeName: "BebopUUID" },
        { name: "raw_value", index: 7, typeName: "string" },
        { name: "bytes_value", index: 8, typeName: "Uint8Array" },
        { name: "timestamp_value", index: 9, typeName: "BebopTimestamp" },
        { name: "duration_value", index: 10, typeName: "BebopDuration" },
      ],
    },
  },
} satisfies BebopReflectableCodec<LiteralValue>;

export type DecoratorArg = {
  readonly name: string;
  readonly value: LiteralValue;
};

export const DecoratorArg = {
  readFrom(reader: BebopReader): DecoratorArg {
    return {
      name: reader.readString(),
      value: LiteralValue.readFrom(reader),
    };
  },
  writeInto(writer: BebopWriter, value: DecoratorArg): void {
    writer.writeString(value.name);
    LiteralValue.writeInto(writer, value.value);
  },
  encodedSize(value: DecoratorArg): number {
    let size = 0;
    size += 4 + new TextEncoder().encode(value.name).length + 1;
    size += LiteralValue.encodedSize(value.value);
    return size;
  },
  reflection: {
    name: "DecoratorArg",
    fqn: "bebop.DecoratorArg",
    kind: BebopDefinitionKind.struct,
    detail: {
      fields: [
        { name: "name", index: 0, typeName: "string" },
        { name: "value", index: 0, typeName: "LiteralValue" },
      ],
    },
  },
} satisfies BebopReflectableCodec<DecoratorArg>;

export type DecoratorUsage = {
  readonly fqn?: string | undefined;
  readonly args?: readonly DecoratorArg[] | undefined;
  readonly exportData?: ReadonlyMap<string, LiteralValue> | undefined;
};

export const DecoratorUsage = {
  readFrom(reader: BebopReader): DecoratorUsage {
    const end = reader.readMessageEnd();
    let fqnValue: string | undefined;
    let argsValue: readonly DecoratorArg[] | undefined;
    let exportDataValue: ReadonlyMap<string, LiteralValue> | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: fqnValue = reader.readString(); break;
        case 2: argsValue = reader.readDynamicArray((_r) => DecoratorArg.readFrom(_r)); break;
        case 3: exportDataValue = reader.readDynamicMap((_r) => _r.readString(), (_r) => LiteralValue.readFrom(_r)); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      fqn: fqnValue,
      args: argsValue,
      exportData: exportDataValue,
    };
  },
  writeInto(writer: BebopWriter, value: DecoratorUsage): void {
    const pos = writer.reserveMessageLength();
    if (value.fqn !== undefined) {
      writer.writeTag(1);
      writer.writeString(value.fqn);
    }
    if (value.args !== undefined) {
      writer.writeTag(2);
      writer.writeDynamicArray(value.args, (_w, _v) => {
        DecoratorArg.writeInto(_w, _v);
      });
    }
    if (value.exportData !== undefined) {
      writer.writeTag(3);
      writer.writeDynamicMap(value.exportData, (_w, _k, _v) => {
        _w.writeString(_k);
        LiteralValue.writeInto(_w, _v);
      });
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: DecoratorUsage): number {
    let size = 5;
    if (value.fqn !== undefined) {
      size += 1;
      size += 4 + new TextEncoder().encode(value.fqn).length + 1;
    }
    if (value.args !== undefined) {
      size += 1;
      size += 4;
      for (let i = 0; i < value.args.length; i++) {
        const item = value.args[i]!;
        size += DecoratorArg.encodedSize(item);
      }
    }
    if (value.exportData !== undefined) {
      size += 1;
      size += 4;
      value.exportData.forEach((_v, _k) => {
        size += 4 + new TextEncoder().encode(_k).length + 1;
        size += LiteralValue.encodedSize(_v);
      });
    }
    return size;
  },
  reflection: {
    name: "DecoratorUsage",
    fqn: "bebop.DecoratorUsage",
    kind: BebopDefinitionKind.message,
    detail: {
      fields: [
        { name: "fqn", index: 1, typeName: "string" },
        { name: "args", index: 2, typeName: "readonly DecoratorArg[]" },
        { name: "export_data", index: 3, typeName: "ReadonlyMap<string, LiteralValue>" },
      ],
    },
  },
} satisfies BebopReflectableCodec<DecoratorUsage>;

export type FieldDescriptor = {
  readonly name?: string | undefined;
  readonly documentation?: string | undefined;
  readonly type?: TypeDescriptor | undefined;
  readonly index?: number | undefined;
  readonly decorators?: readonly DecoratorUsage[] | undefined;
};

export const FieldDescriptor = {
  readFrom(reader: BebopReader): FieldDescriptor {
    const end = reader.readMessageEnd();
    let nameValue: string | undefined;
    let documentationValue: string | undefined;
    let typeValue: TypeDescriptor | undefined;
    let indexValue: number | undefined;
    let decoratorsValue: readonly DecoratorUsage[] | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: nameValue = reader.readString(); break;
        case 2: documentationValue = reader.readString(); break;
        case 3: typeValue = TypeDescriptor.readFrom(reader); break;
        case 4: indexValue = reader.readUint32(); break;
        case 5: decoratorsValue = reader.readDynamicArray((_r) => DecoratorUsage.readFrom(_r)); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      name: nameValue,
      documentation: documentationValue,
      type: typeValue,
      index: indexValue,
      decorators: decoratorsValue,
    };
  },
  writeInto(writer: BebopWriter, value: FieldDescriptor): void {
    const pos = writer.reserveMessageLength();
    if (value.name !== undefined) {
      writer.writeTag(1);
      writer.writeString(value.name);
    }
    if (value.documentation !== undefined) {
      writer.writeTag(2);
      writer.writeString(value.documentation);
    }
    if (value.type !== undefined) {
      writer.writeTag(3);
      TypeDescriptor.writeInto(writer, value.type);
    }
    if (value.index !== undefined) {
      writer.writeTag(4);
      writer.writeUint32(value.index);
    }
    if (value.decorators !== undefined) {
      writer.writeTag(5);
      writer.writeDynamicArray(value.decorators, (_w, _v) => {
        DecoratorUsage.writeInto(_w, _v);
      });
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: FieldDescriptor): number {
    let size = 5;
    if (value.name !== undefined) {
      size += 1;
      size += 4 + new TextEncoder().encode(value.name).length + 1;
    }
    if (value.documentation !== undefined) {
      size += 1;
      size += 4 + new TextEncoder().encode(value.documentation).length + 1;
    }
    if (value.type !== undefined) {
      size += 1;
      size += TypeDescriptor.encodedSize(value.type);
    }
    if (value.index !== undefined) {
      size += 1;
      size += 4;
    }
    if (value.decorators !== undefined) {
      size += 1;
      size += 4;
      for (let i = 0; i < value.decorators.length; i++) {
        const item = value.decorators[i]!;
        size += DecoratorUsage.encodedSize(item);
      }
    }
    return size;
  },
  reflection: {
    name: "FieldDescriptor",
    fqn: "bebop.FieldDescriptor",
    kind: BebopDefinitionKind.message,
    detail: {
      fields: [
        { name: "name", index: 1, typeName: "string" },
        { name: "documentation", index: 2, typeName: "string" },
        { name: "type", index: 3, typeName: "TypeDescriptor" },
        { name: "index", index: 4, typeName: "number" },
        { name: "decorators", index: 5, typeName: "readonly DecoratorUsage[]" },
      ],
    },
  },
} satisfies BebopReflectableCodec<FieldDescriptor>;

export type EnumMemberDescriptor = {
  readonly name?: string | undefined;
  readonly documentation?: string | undefined;
  readonly value?: bigint | undefined;
  readonly decorators?: readonly DecoratorUsage[] | undefined;
  readonly valueExpr?: string | undefined;
};

export const EnumMemberDescriptor = {
  readFrom(reader: BebopReader): EnumMemberDescriptor {
    const end = reader.readMessageEnd();
    let nameValue: string | undefined;
    let documentationValue: string | undefined;
    let valueValue: bigint | undefined;
    let decoratorsValue: readonly DecoratorUsage[] | undefined;
    let valueExprValue: string | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: nameValue = reader.readString(); break;
        case 2: documentationValue = reader.readString(); break;
        case 3: valueValue = reader.readUint64(); break;
        case 4: decoratorsValue = reader.readDynamicArray((_r) => DecoratorUsage.readFrom(_r)); break;
        case 5: valueExprValue = reader.readString(); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      name: nameValue,
      documentation: documentationValue,
      value: valueValue,
      decorators: decoratorsValue,
      valueExpr: valueExprValue,
    };
  },
  writeInto(writer: BebopWriter, value: EnumMemberDescriptor): void {
    const pos = writer.reserveMessageLength();
    if (value.name !== undefined) {
      writer.writeTag(1);
      writer.writeString(value.name);
    }
    if (value.documentation !== undefined) {
      writer.writeTag(2);
      writer.writeString(value.documentation);
    }
    if (value.value !== undefined) {
      writer.writeTag(3);
      writer.writeUint64(value.value);
    }
    if (value.decorators !== undefined) {
      writer.writeTag(4);
      writer.writeDynamicArray(value.decorators, (_w, _v) => {
        DecoratorUsage.writeInto(_w, _v);
      });
    }
    if (value.valueExpr !== undefined) {
      writer.writeTag(5);
      writer.writeString(value.valueExpr);
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: EnumMemberDescriptor): number {
    let size = 5;
    if (value.name !== undefined) {
      size += 1;
      size += 4 + new TextEncoder().encode(value.name).length + 1;
    }
    if (value.documentation !== undefined) {
      size += 1;
      size += 4 + new TextEncoder().encode(value.documentation).length + 1;
    }
    if (value.value !== undefined) {
      size += 1;
      size += 8;
    }
    if (value.decorators !== undefined) {
      size += 1;
      size += 4;
      for (let i = 0; i < value.decorators.length; i++) {
        const item = value.decorators[i]!;
        size += DecoratorUsage.encodedSize(item);
      }
    }
    if (value.valueExpr !== undefined) {
      size += 1;
      size += 4 + new TextEncoder().encode(value.valueExpr).length + 1;
    }
    return size;
  },
  reflection: {
    name: "EnumMemberDescriptor",
    fqn: "bebop.EnumMemberDescriptor",
    kind: BebopDefinitionKind.message,
    detail: {
      fields: [
        { name: "name", index: 1, typeName: "string" },
        { name: "documentation", index: 2, typeName: "string" },
        { name: "value", index: 3, typeName: "bigint" },
        { name: "decorators", index: 4, typeName: "readonly DecoratorUsage[]" },
        { name: "value_expr", index: 5, typeName: "string" },
      ],
    },
  },
} satisfies BebopReflectableCodec<EnumMemberDescriptor>;

export type UnionBranchDescriptor = {
  readonly discriminator?: number | undefined;
  readonly documentation?: string | undefined;
  readonly inlineFqn?: string | undefined;
  readonly typeRefFqn?: string | undefined;
  readonly name?: string | undefined;
  readonly decorators?: readonly DecoratorUsage[] | undefined;
};

export const UnionBranchDescriptor = {
  readFrom(reader: BebopReader): UnionBranchDescriptor {
    const end = reader.readMessageEnd();
    let discriminatorValue: number | undefined;
    let documentationValue: string | undefined;
    let inlineFqnValue: string | undefined;
    let typeRefFqnValue: string | undefined;
    let nameValue: string | undefined;
    let decoratorsValue: readonly DecoratorUsage[] | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: discriminatorValue = reader.readByte(); break;
        case 2: documentationValue = reader.readString(); break;
        case 3: inlineFqnValue = reader.readString(); break;
        case 4: typeRefFqnValue = reader.readString(); break;
        case 5: nameValue = reader.readString(); break;
        case 6: decoratorsValue = reader.readDynamicArray((_r) => DecoratorUsage.readFrom(_r)); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      discriminator: discriminatorValue,
      documentation: documentationValue,
      inlineFqn: inlineFqnValue,
      typeRefFqn: typeRefFqnValue,
      name: nameValue,
      decorators: decoratorsValue,
    };
  },
  writeInto(writer: BebopWriter, value: UnionBranchDescriptor): void {
    const pos = writer.reserveMessageLength();
    if (value.discriminator !== undefined) {
      writer.writeTag(1);
      writer.writeByte(value.discriminator);
    }
    if (value.documentation !== undefined) {
      writer.writeTag(2);
      writer.writeString(value.documentation);
    }
    if (value.inlineFqn !== undefined) {
      writer.writeTag(3);
      writer.writeString(value.inlineFqn);
    }
    if (value.typeRefFqn !== undefined) {
      writer.writeTag(4);
      writer.writeString(value.typeRefFqn);
    }
    if (value.name !== undefined) {
      writer.writeTag(5);
      writer.writeString(value.name);
    }
    if (value.decorators !== undefined) {
      writer.writeTag(6);
      writer.writeDynamicArray(value.decorators, (_w, _v) => {
        DecoratorUsage.writeInto(_w, _v);
      });
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: UnionBranchDescriptor): number {
    let size = 5;
    if (value.discriminator !== undefined) {
      size += 1;
      size += 1;
    }
    if (value.documentation !== undefined) {
      size += 1;
      size += 4 + new TextEncoder().encode(value.documentation).length + 1;
    }
    if (value.inlineFqn !== undefined) {
      size += 1;
      size += 4 + new TextEncoder().encode(value.inlineFqn).length + 1;
    }
    if (value.typeRefFqn !== undefined) {
      size += 1;
      size += 4 + new TextEncoder().encode(value.typeRefFqn).length + 1;
    }
    if (value.name !== undefined) {
      size += 1;
      size += 4 + new TextEncoder().encode(value.name).length + 1;
    }
    if (value.decorators !== undefined) {
      size += 1;
      size += 4;
      for (let i = 0; i < value.decorators.length; i++) {
        const item = value.decorators[i]!;
        size += DecoratorUsage.encodedSize(item);
      }
    }
    return size;
  },
  reflection: {
    name: "UnionBranchDescriptor",
    fqn: "bebop.UnionBranchDescriptor",
    kind: BebopDefinitionKind.message,
    detail: {
      fields: [
        { name: "discriminator", index: 1, typeName: "number" },
        { name: "documentation", index: 2, typeName: "string" },
        { name: "inline_fqn", index: 3, typeName: "string" },
        { name: "type_ref_fqn", index: 4, typeName: "string" },
        { name: "name", index: 5, typeName: "string" },
        { name: "decorators", index: 6, typeName: "readonly DecoratorUsage[]" },
      ],
    },
  },
} satisfies BebopReflectableCodec<UnionBranchDescriptor>;

export type MethodDescriptor = {
  readonly name?: string | undefined;
  readonly documentation?: string | undefined;
  readonly requestType?: TypeDescriptor | undefined;
  readonly responseType?: TypeDescriptor | undefined;
  readonly methodType?: MethodType | undefined;
  readonly id?: number | undefined;
  readonly decorators?: readonly DecoratorUsage[] | undefined;
};

export const MethodDescriptor = {
  readFrom(reader: BebopReader): MethodDescriptor {
    const end = reader.readMessageEnd();
    let nameValue: string | undefined;
    let documentationValue: string | undefined;
    let requestTypeValue: TypeDescriptor | undefined;
    let responseTypeValue: TypeDescriptor | undefined;
    let methodTypeValue: MethodType | undefined;
    let idValue: number | undefined;
    let decoratorsValue: readonly DecoratorUsage[] | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: nameValue = reader.readString(); break;
        case 2: documentationValue = reader.readString(); break;
        case 3: requestTypeValue = TypeDescriptor.readFrom(reader); break;
        case 4: responseTypeValue = TypeDescriptor.readFrom(reader); break;
        case 5: methodTypeValue = reader.readByte() as MethodType; break;
        case 6: idValue = reader.readUint32(); break;
        case 7: decoratorsValue = reader.readDynamicArray((_r) => DecoratorUsage.readFrom(_r)); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      name: nameValue,
      documentation: documentationValue,
      requestType: requestTypeValue,
      responseType: responseTypeValue,
      methodType: methodTypeValue,
      id: idValue,
      decorators: decoratorsValue,
    };
  },
  writeInto(writer: BebopWriter, value: MethodDescriptor): void {
    const pos = writer.reserveMessageLength();
    if (value.name !== undefined) {
      writer.writeTag(1);
      writer.writeString(value.name);
    }
    if (value.documentation !== undefined) {
      writer.writeTag(2);
      writer.writeString(value.documentation);
    }
    if (value.requestType !== undefined) {
      writer.writeTag(3);
      TypeDescriptor.writeInto(writer, value.requestType);
    }
    if (value.responseType !== undefined) {
      writer.writeTag(4);
      TypeDescriptor.writeInto(writer, value.responseType);
    }
    if (value.methodType !== undefined) {
      writer.writeTag(5);
      writer.writeByte(value.methodType);
    }
    if (value.id !== undefined) {
      writer.writeTag(6);
      writer.writeUint32(value.id);
    }
    if (value.decorators !== undefined) {
      writer.writeTag(7);
      writer.writeDynamicArray(value.decorators, (_w, _v) => {
        DecoratorUsage.writeInto(_w, _v);
      });
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: MethodDescriptor): number {
    let size = 5;
    if (value.name !== undefined) {
      size += 1;
      size += 4 + new TextEncoder().encode(value.name).length + 1;
    }
    if (value.documentation !== undefined) {
      size += 1;
      size += 4 + new TextEncoder().encode(value.documentation).length + 1;
    }
    if (value.requestType !== undefined) {
      size += 1;
      size += TypeDescriptor.encodedSize(value.requestType);
    }
    if (value.responseType !== undefined) {
      size += 1;
      size += TypeDescriptor.encodedSize(value.responseType);
    }
    if (value.methodType !== undefined) {
      size += 1;
      size += 1;
    }
    if (value.id !== undefined) {
      size += 1;
      size += 4;
    }
    if (value.decorators !== undefined) {
      size += 1;
      size += 4;
      for (let i = 0; i < value.decorators.length; i++) {
        const item = value.decorators[i]!;
        size += DecoratorUsage.encodedSize(item);
      }
    }
    return size;
  },
  reflection: {
    name: "MethodDescriptor",
    fqn: "bebop.MethodDescriptor",
    kind: BebopDefinitionKind.message,
    detail: {
      fields: [
        { name: "name", index: 1, typeName: "string" },
        { name: "documentation", index: 2, typeName: "string" },
        { name: "request_type", index: 3, typeName: "TypeDescriptor" },
        { name: "response_type", index: 4, typeName: "TypeDescriptor" },
        { name: "method_type", index: 5, typeName: "MethodType" },
        { name: "id", index: 6, typeName: "number" },
        { name: "decorators", index: 7, typeName: "readonly DecoratorUsage[]" },
      ],
    },
  },
} satisfies BebopReflectableCodec<MethodDescriptor>;

export type EnumDef = {
  readonly baseType?: TypeKind | undefined;
  readonly members?: readonly EnumMemberDescriptor[] | undefined;
  readonly isFlags?: boolean | undefined;
};

export const EnumDef = {
  readFrom(reader: BebopReader): EnumDef {
    const end = reader.readMessageEnd();
    let baseTypeValue: TypeKind | undefined;
    let membersValue: readonly EnumMemberDescriptor[] | undefined;
    let isFlagsValue: boolean | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: baseTypeValue = reader.readByte() as TypeKind; break;
        case 2: membersValue = reader.readDynamicArray((_r) => EnumMemberDescriptor.readFrom(_r)); break;
        case 3: isFlagsValue = reader.readBool(); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      baseType: baseTypeValue,
      members: membersValue,
      isFlags: isFlagsValue,
    };
  },
  writeInto(writer: BebopWriter, value: EnumDef): void {
    const pos = writer.reserveMessageLength();
    if (value.baseType !== undefined) {
      writer.writeTag(1);
      writer.writeByte(value.baseType);
    }
    if (value.members !== undefined) {
      writer.writeTag(2);
      writer.writeDynamicArray(value.members, (_w, _v) => {
        EnumMemberDescriptor.writeInto(_w, _v);
      });
    }
    if (value.isFlags !== undefined) {
      writer.writeTag(3);
      writer.writeBool(value.isFlags);
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: EnumDef): number {
    let size = 5;
    if (value.baseType !== undefined) {
      size += 1;
      size += 1;
    }
    if (value.members !== undefined) {
      size += 1;
      size += 4;
      for (let i = 0; i < value.members.length; i++) {
        const item = value.members[i]!;
        size += EnumMemberDescriptor.encodedSize(item);
      }
    }
    if (value.isFlags !== undefined) {
      size += 1;
      size += 1;
    }
    return size;
  },
  reflection: {
    name: "EnumDef",
    fqn: "bebop.EnumDef",
    kind: BebopDefinitionKind.message,
    detail: {
      fields: [
        { name: "base_type", index: 1, typeName: "TypeKind" },
        { name: "members", index: 2, typeName: "readonly EnumMemberDescriptor[]" },
        { name: "is_flags", index: 3, typeName: "boolean" },
      ],
    },
  },
} satisfies BebopReflectableCodec<EnumDef>;

export type StructDef = {
  readonly fields?: readonly FieldDescriptor[] | undefined;
  readonly isMutable?: boolean | undefined;
  readonly fixedSize?: number | undefined;
};

export const StructDef = {
  readFrom(reader: BebopReader): StructDef {
    const end = reader.readMessageEnd();
    let fieldsValue: readonly FieldDescriptor[] | undefined;
    let isMutableValue: boolean | undefined;
    let fixedSizeValue: number | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: fieldsValue = reader.readDynamicArray((_r) => FieldDescriptor.readFrom(_r)); break;
        case 2: isMutableValue = reader.readBool(); break;
        case 3: fixedSizeValue = reader.readUint32(); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      fields: fieldsValue,
      isMutable: isMutableValue,
      fixedSize: fixedSizeValue,
    };
  },
  writeInto(writer: BebopWriter, value: StructDef): void {
    const pos = writer.reserveMessageLength();
    if (value.fields !== undefined) {
      writer.writeTag(1);
      writer.writeDynamicArray(value.fields, (_w, _v) => {
        FieldDescriptor.writeInto(_w, _v);
      });
    }
    if (value.isMutable !== undefined) {
      writer.writeTag(2);
      writer.writeBool(value.isMutable);
    }
    if (value.fixedSize !== undefined) {
      writer.writeTag(3);
      writer.writeUint32(value.fixedSize);
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: StructDef): number {
    let size = 5;
    if (value.fields !== undefined) {
      size += 1;
      size += 4;
      for (let i = 0; i < value.fields.length; i++) {
        const item = value.fields[i]!;
        size += FieldDescriptor.encodedSize(item);
      }
    }
    if (value.isMutable !== undefined) {
      size += 1;
      size += 1;
    }
    if (value.fixedSize !== undefined) {
      size += 1;
      size += 4;
    }
    return size;
  },
  reflection: {
    name: "StructDef",
    fqn: "bebop.StructDef",
    kind: BebopDefinitionKind.message,
    detail: {
      fields: [
        { name: "fields", index: 1, typeName: "readonly FieldDescriptor[]" },
        { name: "is_mutable", index: 2, typeName: "boolean" },
        { name: "fixed_size", index: 3, typeName: "number" },
      ],
    },
  },
} satisfies BebopReflectableCodec<StructDef>;

export type MessageDef = {
  readonly fields?: readonly FieldDescriptor[] | undefined;
};

export const MessageDef = {
  readFrom(reader: BebopReader): MessageDef {
    const end = reader.readMessageEnd();
    let fieldsValue: readonly FieldDescriptor[] | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: fieldsValue = reader.readDynamicArray((_r) => FieldDescriptor.readFrom(_r)); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      fields: fieldsValue,
    };
  },
  writeInto(writer: BebopWriter, value: MessageDef): void {
    const pos = writer.reserveMessageLength();
    if (value.fields !== undefined) {
      writer.writeTag(1);
      writer.writeDynamicArray(value.fields, (_w, _v) => {
        FieldDescriptor.writeInto(_w, _v);
      });
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: MessageDef): number {
    let size = 5;
    if (value.fields !== undefined) {
      size += 1;
      size += 4;
      for (let i = 0; i < value.fields.length; i++) {
        const item = value.fields[i]!;
        size += FieldDescriptor.encodedSize(item);
      }
    }
    return size;
  },
  reflection: {
    name: "MessageDef",
    fqn: "bebop.MessageDef",
    kind: BebopDefinitionKind.message,
    detail: {
      fields: [
        { name: "fields", index: 1, typeName: "readonly FieldDescriptor[]" },
      ],
    },
  },
} satisfies BebopReflectableCodec<MessageDef>;

export type UnionDef = {
  readonly branches?: readonly UnionBranchDescriptor[] | undefined;
};

export const UnionDef = {
  readFrom(reader: BebopReader): UnionDef {
    const end = reader.readMessageEnd();
    let branchesValue: readonly UnionBranchDescriptor[] | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: branchesValue = reader.readDynamicArray((_r) => UnionBranchDescriptor.readFrom(_r)); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      branches: branchesValue,
    };
  },
  writeInto(writer: BebopWriter, value: UnionDef): void {
    const pos = writer.reserveMessageLength();
    if (value.branches !== undefined) {
      writer.writeTag(1);
      writer.writeDynamicArray(value.branches, (_w, _v) => {
        UnionBranchDescriptor.writeInto(_w, _v);
      });
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: UnionDef): number {
    let size = 5;
    if (value.branches !== undefined) {
      size += 1;
      size += 4;
      for (let i = 0; i < value.branches.length; i++) {
        const item = value.branches[i]!;
        size += UnionBranchDescriptor.encodedSize(item);
      }
    }
    return size;
  },
  reflection: {
    name: "UnionDef",
    fqn: "bebop.UnionDef",
    kind: BebopDefinitionKind.message,
    detail: {
      fields: [
        { name: "branches", index: 1, typeName: "readonly UnionBranchDescriptor[]" },
      ],
    },
  },
} satisfies BebopReflectableCodec<UnionDef>;

export type ServiceDef = {
  readonly methods?: readonly MethodDescriptor[] | undefined;
};

export const ServiceDef = {
  readFrom(reader: BebopReader): ServiceDef {
    const end = reader.readMessageEnd();
    let methodsValue: readonly MethodDescriptor[] | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: methodsValue = reader.readDynamicArray((_r) => MethodDescriptor.readFrom(_r)); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      methods: methodsValue,
    };
  },
  writeInto(writer: BebopWriter, value: ServiceDef): void {
    const pos = writer.reserveMessageLength();
    if (value.methods !== undefined) {
      writer.writeTag(1);
      writer.writeDynamicArray(value.methods, (_w, _v) => {
        MethodDescriptor.writeInto(_w, _v);
      });
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: ServiceDef): number {
    let size = 5;
    if (value.methods !== undefined) {
      size += 1;
      size += 4;
      for (let i = 0; i < value.methods.length; i++) {
        const item = value.methods[i]!;
        size += MethodDescriptor.encodedSize(item);
      }
    }
    return size;
  },
  reflection: {
    name: "ServiceDef",
    fqn: "bebop.ServiceDef",
    kind: BebopDefinitionKind.message,
    detail: {
      fields: [
        { name: "methods", index: 1, typeName: "readonly MethodDescriptor[]" },
      ],
    },
  },
} satisfies BebopReflectableCodec<ServiceDef>;

export type ConstDef = {
  readonly type?: TypeDescriptor | undefined;
  readonly value?: LiteralValue | undefined;
};

export const ConstDef = {
  readFrom(reader: BebopReader): ConstDef {
    const end = reader.readMessageEnd();
    let typeValue: TypeDescriptor | undefined;
    let valueValue: LiteralValue | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: typeValue = TypeDescriptor.readFrom(reader); break;
        case 2: valueValue = LiteralValue.readFrom(reader); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      type: typeValue,
      value: valueValue,
    };
  },
  writeInto(writer: BebopWriter, value: ConstDef): void {
    const pos = writer.reserveMessageLength();
    if (value.type !== undefined) {
      writer.writeTag(1);
      TypeDescriptor.writeInto(writer, value.type);
    }
    if (value.value !== undefined) {
      writer.writeTag(2);
      LiteralValue.writeInto(writer, value.value);
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: ConstDef): number {
    let size = 5;
    if (value.type !== undefined) {
      size += 1;
      size += TypeDescriptor.encodedSize(value.type);
    }
    if (value.value !== undefined) {
      size += 1;
      size += LiteralValue.encodedSize(value.value);
    }
    return size;
  },
  reflection: {
    name: "ConstDef",
    fqn: "bebop.ConstDef",
    kind: BebopDefinitionKind.message,
    detail: {
      fields: [
        { name: "type", index: 1, typeName: "TypeDescriptor" },
        { name: "value", index: 2, typeName: "LiteralValue" },
      ],
    },
  },
} satisfies BebopReflectableCodec<ConstDef>;

export type DecoratorParamDef = {
  readonly name?: string | undefined;
  readonly description?: string | undefined;
  readonly type?: TypeKind | undefined;
  readonly required?: boolean | undefined;
  readonly defaultValue?: LiteralValue | undefined;
  readonly allowedValues?: readonly LiteralValue[] | undefined;
};

export const DecoratorParamDef = {
  readFrom(reader: BebopReader): DecoratorParamDef {
    const end = reader.readMessageEnd();
    let nameValue: string | undefined;
    let descriptionValue: string | undefined;
    let typeValue: TypeKind | undefined;
    let requiredValue: boolean | undefined;
    let defaultValueValue: LiteralValue | undefined;
    let allowedValuesValue: readonly LiteralValue[] | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: nameValue = reader.readString(); break;
        case 2: descriptionValue = reader.readString(); break;
        case 3: typeValue = reader.readByte() as TypeKind; break;
        case 4: requiredValue = reader.readBool(); break;
        case 5: defaultValueValue = LiteralValue.readFrom(reader); break;
        case 6: allowedValuesValue = reader.readDynamicArray((_r) => LiteralValue.readFrom(_r)); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      name: nameValue,
      description: descriptionValue,
      type: typeValue,
      required: requiredValue,
      defaultValue: defaultValueValue,
      allowedValues: allowedValuesValue,
    };
  },
  writeInto(writer: BebopWriter, value: DecoratorParamDef): void {
    const pos = writer.reserveMessageLength();
    if (value.name !== undefined) {
      writer.writeTag(1);
      writer.writeString(value.name);
    }
    if (value.description !== undefined) {
      writer.writeTag(2);
      writer.writeString(value.description);
    }
    if (value.type !== undefined) {
      writer.writeTag(3);
      writer.writeByte(value.type);
    }
    if (value.required !== undefined) {
      writer.writeTag(4);
      writer.writeBool(value.required);
    }
    if (value.defaultValue !== undefined) {
      writer.writeTag(5);
      LiteralValue.writeInto(writer, value.defaultValue);
    }
    if (value.allowedValues !== undefined) {
      writer.writeTag(6);
      writer.writeDynamicArray(value.allowedValues, (_w, _v) => {
        LiteralValue.writeInto(_w, _v);
      });
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: DecoratorParamDef): number {
    let size = 5;
    if (value.name !== undefined) {
      size += 1;
      size += 4 + new TextEncoder().encode(value.name).length + 1;
    }
    if (value.description !== undefined) {
      size += 1;
      size += 4 + new TextEncoder().encode(value.description).length + 1;
    }
    if (value.type !== undefined) {
      size += 1;
      size += 1;
    }
    if (value.required !== undefined) {
      size += 1;
      size += 1;
    }
    if (value.defaultValue !== undefined) {
      size += 1;
      size += LiteralValue.encodedSize(value.defaultValue);
    }
    if (value.allowedValues !== undefined) {
      size += 1;
      size += 4;
      for (let i = 0; i < value.allowedValues.length; i++) {
        const item = value.allowedValues[i]!;
        size += LiteralValue.encodedSize(item);
      }
    }
    return size;
  },
  reflection: {
    name: "DecoratorParamDef",
    fqn: "bebop.DecoratorParamDef",
    kind: BebopDefinitionKind.message,
    detail: {
      fields: [
        { name: "name", index: 1, typeName: "string" },
        { name: "description", index: 2, typeName: "string" },
        { name: "type", index: 3, typeName: "TypeKind" },
        { name: "required", index: 4, typeName: "boolean" },
        { name: "default_value", index: 5, typeName: "LiteralValue" },
        { name: "allowed_values", index: 6, typeName: "readonly LiteralValue[]" },
      ],
    },
  },
} satisfies BebopReflectableCodec<DecoratorParamDef>;

export type DecoratorDef = {
  readonly targets?: DecoratorTarget | undefined;
  readonly allowMultiple?: boolean | undefined;
  readonly params?: readonly DecoratorParamDef[] | undefined;
  readonly validateSource?: string | undefined;
  readonly exportSource?: string | undefined;
};

export const DecoratorDef = {
  readFrom(reader: BebopReader): DecoratorDef {
    const end = reader.readMessageEnd();
    let targetsValue: DecoratorTarget | undefined;
    let allowMultipleValue: boolean | undefined;
    let paramsValue: readonly DecoratorParamDef[] | undefined;
    let validateSourceValue: string | undefined;
    let exportSourceValue: string | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: targetsValue = reader.readByte() as DecoratorTarget; break;
        case 2: allowMultipleValue = reader.readBool(); break;
        case 3: paramsValue = reader.readDynamicArray((_r) => DecoratorParamDef.readFrom(_r)); break;
        case 4: validateSourceValue = reader.readString(); break;
        case 5: exportSourceValue = reader.readString(); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      targets: targetsValue,
      allowMultiple: allowMultipleValue,
      params: paramsValue,
      validateSource: validateSourceValue,
      exportSource: exportSourceValue,
    };
  },
  writeInto(writer: BebopWriter, value: DecoratorDef): void {
    const pos = writer.reserveMessageLength();
    if (value.targets !== undefined) {
      writer.writeTag(1);
      writer.writeByte(value.targets);
    }
    if (value.allowMultiple !== undefined) {
      writer.writeTag(2);
      writer.writeBool(value.allowMultiple);
    }
    if (value.params !== undefined) {
      writer.writeTag(3);
      writer.writeDynamicArray(value.params, (_w, _v) => {
        DecoratorParamDef.writeInto(_w, _v);
      });
    }
    if (value.validateSource !== undefined) {
      writer.writeTag(4);
      writer.writeString(value.validateSource);
    }
    if (value.exportSource !== undefined) {
      writer.writeTag(5);
      writer.writeString(value.exportSource);
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: DecoratorDef): number {
    let size = 5;
    if (value.targets !== undefined) {
      size += 1;
      size += 1;
    }
    if (value.allowMultiple !== undefined) {
      size += 1;
      size += 1;
    }
    if (value.params !== undefined) {
      size += 1;
      size += 4;
      for (let i = 0; i < value.params.length; i++) {
        const item = value.params[i]!;
        size += DecoratorParamDef.encodedSize(item);
      }
    }
    if (value.validateSource !== undefined) {
      size += 1;
      size += 4 + new TextEncoder().encode(value.validateSource).length + 1;
    }
    if (value.exportSource !== undefined) {
      size += 1;
      size += 4 + new TextEncoder().encode(value.exportSource).length + 1;
    }
    return size;
  },
  reflection: {
    name: "DecoratorDef",
    fqn: "bebop.DecoratorDef",
    kind: BebopDefinitionKind.message,
    detail: {
      fields: [
        { name: "targets", index: 1, typeName: "DecoratorTarget" },
        { name: "allow_multiple", index: 2, typeName: "boolean" },
        { name: "params", index: 3, typeName: "readonly DecoratorParamDef[]" },
        { name: "validate_source", index: 4, typeName: "string" },
        { name: "export_source", index: 5, typeName: "string" },
      ],
    },
  },
} satisfies BebopReflectableCodec<DecoratorDef>;

export type DefinitionDescriptor = {
  readonly kind?: DefinitionKind | undefined;
  readonly name?: string | undefined;
  readonly fqn?: string | undefined;
  readonly documentation?: string | undefined;
  readonly visibility?: Visibility | undefined;
  readonly decorators?: readonly DecoratorUsage[] | undefined;
  readonly nested?: readonly DefinitionDescriptor[] | undefined;
  readonly enumDef?: EnumDef | undefined;
  readonly structDef?: StructDef | undefined;
  readonly messageDef?: MessageDef | undefined;
  readonly unionDef?: UnionDef | undefined;
  readonly serviceDef?: ServiceDef | undefined;
  readonly constDef?: ConstDef | undefined;
  readonly decoratorDef?: DecoratorDef | undefined;
};

export const DefinitionDescriptor = {
  readFrom(reader: BebopReader): DefinitionDescriptor {
    const end = reader.readMessageEnd();
    let kindValue: DefinitionKind | undefined;
    let nameValue: string | undefined;
    let fqnValue: string | undefined;
    let documentationValue: string | undefined;
    let visibilityValue: Visibility | undefined;
    let decoratorsValue: readonly DecoratorUsage[] | undefined;
    let nestedValue: readonly DefinitionDescriptor[] | undefined;
    let enumDefValue: EnumDef | undefined;
    let structDefValue: StructDef | undefined;
    let messageDefValue: MessageDef | undefined;
    let unionDefValue: UnionDef | undefined;
    let serviceDefValue: ServiceDef | undefined;
    let constDefValue: ConstDef | undefined;
    let decoratorDefValue: DecoratorDef | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: kindValue = reader.readByte() as DefinitionKind; break;
        case 2: nameValue = reader.readString(); break;
        case 3: fqnValue = reader.readString(); break;
        case 4: documentationValue = reader.readString(); break;
        case 5: visibilityValue = reader.readByte() as Visibility; break;
        case 6: decoratorsValue = reader.readDynamicArray((_r) => DecoratorUsage.readFrom(_r)); break;
        case 7: nestedValue = reader.readDynamicArray((_r) => DefinitionDescriptor.readFrom(_r)); break;
        case 8: enumDefValue = EnumDef.readFrom(reader); break;
        case 9: structDefValue = StructDef.readFrom(reader); break;
        case 10: messageDefValue = MessageDef.readFrom(reader); break;
        case 11: unionDefValue = UnionDef.readFrom(reader); break;
        case 12: serviceDefValue = ServiceDef.readFrom(reader); break;
        case 13: constDefValue = ConstDef.readFrom(reader); break;
        case 14: decoratorDefValue = DecoratorDef.readFrom(reader); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      kind: kindValue,
      name: nameValue,
      fqn: fqnValue,
      documentation: documentationValue,
      visibility: visibilityValue,
      decorators: decoratorsValue,
      nested: nestedValue,
      enumDef: enumDefValue,
      structDef: structDefValue,
      messageDef: messageDefValue,
      unionDef: unionDefValue,
      serviceDef: serviceDefValue,
      constDef: constDefValue,
      decoratorDef: decoratorDefValue,
    };
  },
  writeInto(writer: BebopWriter, value: DefinitionDescriptor): void {
    const pos = writer.reserveMessageLength();
    if (value.kind !== undefined) {
      writer.writeTag(1);
      writer.writeByte(value.kind);
    }
    if (value.name !== undefined) {
      writer.writeTag(2);
      writer.writeString(value.name);
    }
    if (value.fqn !== undefined) {
      writer.writeTag(3);
      writer.writeString(value.fqn);
    }
    if (value.documentation !== undefined) {
      writer.writeTag(4);
      writer.writeString(value.documentation);
    }
    if (value.visibility !== undefined) {
      writer.writeTag(5);
      writer.writeByte(value.visibility);
    }
    if (value.decorators !== undefined) {
      writer.writeTag(6);
      writer.writeDynamicArray(value.decorators, (_w, _v) => {
        DecoratorUsage.writeInto(_w, _v);
      });
    }
    if (value.nested !== undefined) {
      writer.writeTag(7);
      writer.writeDynamicArray(value.nested, (_w, _v) => {
        DefinitionDescriptor.writeInto(_w, _v);
      });
    }
    if (value.enumDef !== undefined) {
      writer.writeTag(8);
      EnumDef.writeInto(writer, value.enumDef);
    }
    if (value.structDef !== undefined) {
      writer.writeTag(9);
      StructDef.writeInto(writer, value.structDef);
    }
    if (value.messageDef !== undefined) {
      writer.writeTag(10);
      MessageDef.writeInto(writer, value.messageDef);
    }
    if (value.unionDef !== undefined) {
      writer.writeTag(11);
      UnionDef.writeInto(writer, value.unionDef);
    }
    if (value.serviceDef !== undefined) {
      writer.writeTag(12);
      ServiceDef.writeInto(writer, value.serviceDef);
    }
    if (value.constDef !== undefined) {
      writer.writeTag(13);
      ConstDef.writeInto(writer, value.constDef);
    }
    if (value.decoratorDef !== undefined) {
      writer.writeTag(14);
      DecoratorDef.writeInto(writer, value.decoratorDef);
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: DefinitionDescriptor): number {
    let size = 5;
    if (value.kind !== undefined) {
      size += 1;
      size += 1;
    }
    if (value.name !== undefined) {
      size += 1;
      size += 4 + new TextEncoder().encode(value.name).length + 1;
    }
    if (value.fqn !== undefined) {
      size += 1;
      size += 4 + new TextEncoder().encode(value.fqn).length + 1;
    }
    if (value.documentation !== undefined) {
      size += 1;
      size += 4 + new TextEncoder().encode(value.documentation).length + 1;
    }
    if (value.visibility !== undefined) {
      size += 1;
      size += 1;
    }
    if (value.decorators !== undefined) {
      size += 1;
      size += 4;
      for (let i = 0; i < value.decorators.length; i++) {
        const item = value.decorators[i]!;
        size += DecoratorUsage.encodedSize(item);
      }
    }
    if (value.nested !== undefined) {
      size += 1;
      size += 4;
      for (let i = 0; i < value.nested.length; i++) {
        const item = value.nested[i]!;
        size += DefinitionDescriptor.encodedSize(item);
      }
    }
    if (value.enumDef !== undefined) {
      size += 1;
      size += EnumDef.encodedSize(value.enumDef);
    }
    if (value.structDef !== undefined) {
      size += 1;
      size += StructDef.encodedSize(value.structDef);
    }
    if (value.messageDef !== undefined) {
      size += 1;
      size += MessageDef.encodedSize(value.messageDef);
    }
    if (value.unionDef !== undefined) {
      size += 1;
      size += UnionDef.encodedSize(value.unionDef);
    }
    if (value.serviceDef !== undefined) {
      size += 1;
      size += ServiceDef.encodedSize(value.serviceDef);
    }
    if (value.constDef !== undefined) {
      size += 1;
      size += ConstDef.encodedSize(value.constDef);
    }
    if (value.decoratorDef !== undefined) {
      size += 1;
      size += DecoratorDef.encodedSize(value.decoratorDef);
    }
    return size;
  },
  reflection: {
    name: "DefinitionDescriptor",
    fqn: "bebop.DefinitionDescriptor",
    kind: BebopDefinitionKind.message,
    detail: {
      fields: [
        { name: "kind", index: 1, typeName: "DefinitionKind" },
        { name: "name", index: 2, typeName: "string" },
        { name: "fqn", index: 3, typeName: "string" },
        { name: "documentation", index: 4, typeName: "string" },
        { name: "visibility", index: 5, typeName: "Visibility" },
        { name: "decorators", index: 6, typeName: "readonly DecoratorUsage[]" },
        { name: "nested", index: 7, typeName: "readonly DefinitionDescriptor[]" },
        { name: "enum_def", index: 8, typeName: "EnumDef" },
        { name: "struct_def", index: 9, typeName: "StructDef" },
        { name: "message_def", index: 10, typeName: "MessageDef" },
        { name: "union_def", index: 11, typeName: "UnionDef" },
        { name: "service_def", index: 12, typeName: "ServiceDef" },
        { name: "const_def", index: 13, typeName: "ConstDef" },
        { name: "decorator_def", index: 14, typeName: "DecoratorDef" },
      ],
    },
  },
} satisfies BebopReflectableCodec<DefinitionDescriptor>;

export type Location = {
  readonly path?: Int32Array | undefined;
  readonly span?: Int32Array | undefined;
  readonly leadingComments?: string | undefined;
  readonly trailingComments?: string | undefined;
  readonly detachedComments?: readonly string[] | undefined;
};

export const Location = {
  readFrom(reader: BebopReader): Location {
    const end = reader.readMessageEnd();
    let pathValue: Int32Array | undefined;
    let spanValue: Int32Array | undefined;
    let leadingCommentsValue: string | undefined;
    let trailingCommentsValue: string | undefined;
    let detachedCommentsValue: readonly string[] | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: pathValue = reader.readInt32Array(); break;
        case 2: spanValue = reader.readInt32Array(4); break;
        case 3: leadingCommentsValue = reader.readString(); break;
        case 4: trailingCommentsValue = reader.readString(); break;
        case 5: detachedCommentsValue = reader.readDynamicArray((_r) => _r.readString()); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      path: pathValue,
      span: spanValue,
      leadingComments: leadingCommentsValue,
      trailingComments: trailingCommentsValue,
      detachedComments: detachedCommentsValue,
    };
  },
  writeInto(writer: BebopWriter, value: Location): void {
    const pos = writer.reserveMessageLength();
    if (value.path !== undefined) {
      writer.writeTag(1);
      writer.writeInt32Array(value.path);
    }
    if (value.span !== undefined) {
      writer.writeTag(2);
      writer.writeInt32Array(value.span, 4);
    }
    if (value.leadingComments !== undefined) {
      writer.writeTag(3);
      writer.writeString(value.leadingComments);
    }
    if (value.trailingComments !== undefined) {
      writer.writeTag(4);
      writer.writeString(value.trailingComments);
    }
    if (value.detachedComments !== undefined) {
      writer.writeTag(5);
      writer.writeDynamicArray(value.detachedComments, (_w, _v) => {
        _w.writeString(_v);
      });
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: Location): number {
    let size = 5;
    if (value.path !== undefined) {
      size += 1;
      size += 4 + value.path.length * 4;
    }
    if (value.span !== undefined) {
      size += 1;
      if (value.span.length !== 4) throw new BebopRuntimeError(`expected fixed length 4, got ${value.span.length}`);
      size += 16;
    }
    if (value.leadingComments !== undefined) {
      size += 1;
      size += 4 + new TextEncoder().encode(value.leadingComments).length + 1;
    }
    if (value.trailingComments !== undefined) {
      size += 1;
      size += 4 + new TextEncoder().encode(value.trailingComments).length + 1;
    }
    if (value.detachedComments !== undefined) {
      size += 1;
      size += 4;
      for (let i = 0; i < value.detachedComments.length; i++) {
        const item = value.detachedComments[i]!;
        size += 4 + new TextEncoder().encode(item).length + 1;
      }
    }
    return size;
  },
  reflection: {
    name: "Location",
    fqn: "bebop.Location",
    kind: BebopDefinitionKind.message,
    detail: {
      fields: [
        { name: "path", index: 1, typeName: "Int32Array" },
        { name: "span", index: 2, typeName: "Int32Array" },
        { name: "leading_comments", index: 3, typeName: "string" },
        { name: "trailing_comments", index: 4, typeName: "string" },
        { name: "detached_comments", index: 5, typeName: "readonly string[]" },
      ],
    },
  },
} satisfies BebopReflectableCodec<Location>;

export type SourceCodeInfo = {
  readonly locations?: readonly Location[] | undefined;
};

export const SourceCodeInfo = {
  readFrom(reader: BebopReader): SourceCodeInfo {
    const end = reader.readMessageEnd();
    let locationsValue: readonly Location[] | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: locationsValue = reader.readDynamicArray((_r) => Location.readFrom(_r)); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      locations: locationsValue,
    };
  },
  writeInto(writer: BebopWriter, value: SourceCodeInfo): void {
    const pos = writer.reserveMessageLength();
    if (value.locations !== undefined) {
      writer.writeTag(1);
      writer.writeDynamicArray(value.locations, (_w, _v) => {
        Location.writeInto(_w, _v);
      });
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: SourceCodeInfo): number {
    let size = 5;
    if (value.locations !== undefined) {
      size += 1;
      size += 4;
      for (let i = 0; i < value.locations.length; i++) {
        const item = value.locations[i]!;
        size += Location.encodedSize(item);
      }
    }
    return size;
  },
  reflection: {
    name: "SourceCodeInfo",
    fqn: "bebop.SourceCodeInfo",
    kind: BebopDefinitionKind.message,
    detail: {
      fields: [
        { name: "locations", index: 1, typeName: "readonly Location[]" },
      ],
    },
  },
} satisfies BebopReflectableCodec<SourceCodeInfo>;

export type SchemaDescriptor = {
  readonly path?: string | undefined;
  readonly "package"?: string | undefined;
  readonly edition?: Edition | undefined;
  readonly imports?: readonly string[] | undefined;
  readonly definitions?: readonly DefinitionDescriptor[] | undefined;
  readonly sourceCodeInfo?: SourceCodeInfo | undefined;
};

export const SchemaDescriptor = {
  readFrom(reader: BebopReader): SchemaDescriptor {
    const end = reader.readMessageEnd();
    let pathValue: string | undefined;
    let package_Value: string | undefined;
    let editionValue: Edition | undefined;
    let importsValue: readonly string[] | undefined;
    let definitionsValue: readonly DefinitionDescriptor[] | undefined;
    let sourceCodeInfoValue: SourceCodeInfo | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: pathValue = reader.readString(); break;
        case 2: package_Value = reader.readString(); break;
        case 3: editionValue = reader.readInt32() as Edition; break;
        case 4: importsValue = reader.readDynamicArray((_r) => _r.readString()); break;
        case 5: definitionsValue = reader.readDynamicArray((_r) => DefinitionDescriptor.readFrom(_r)); break;
        case 6: sourceCodeInfoValue = SourceCodeInfo.readFrom(reader); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      path: pathValue,
      "package": package_Value,
      edition: editionValue,
      imports: importsValue,
      definitions: definitionsValue,
      sourceCodeInfo: sourceCodeInfoValue,
    };
  },
  writeInto(writer: BebopWriter, value: SchemaDescriptor): void {
    const pos = writer.reserveMessageLength();
    if (value.path !== undefined) {
      writer.writeTag(1);
      writer.writeString(value.path);
    }
    if (value.package !== undefined) {
      writer.writeTag(2);
      writer.writeString(value.package);
    }
    if (value.edition !== undefined) {
      writer.writeTag(3);
      writer.writeInt32(value.edition);
    }
    if (value.imports !== undefined) {
      writer.writeTag(4);
      writer.writeDynamicArray(value.imports, (_w, _v) => {
        _w.writeString(_v);
      });
    }
    if (value.definitions !== undefined) {
      writer.writeTag(5);
      writer.writeDynamicArray(value.definitions, (_w, _v) => {
        DefinitionDescriptor.writeInto(_w, _v);
      });
    }
    if (value.sourceCodeInfo !== undefined) {
      writer.writeTag(6);
      SourceCodeInfo.writeInto(writer, value.sourceCodeInfo);
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: SchemaDescriptor): number {
    let size = 5;
    if (value.path !== undefined) {
      size += 1;
      size += 4 + new TextEncoder().encode(value.path).length + 1;
    }
    if (value.package !== undefined) {
      size += 1;
      size += 4 + new TextEncoder().encode(value.package).length + 1;
    }
    if (value.edition !== undefined) {
      size += 1;
      size += 4;
    }
    if (value.imports !== undefined) {
      size += 1;
      size += 4;
      for (let i = 0; i < value.imports.length; i++) {
        const item = value.imports[i]!;
        size += 4 + new TextEncoder().encode(item).length + 1;
      }
    }
    if (value.definitions !== undefined) {
      size += 1;
      size += 4;
      for (let i = 0; i < value.definitions.length; i++) {
        const item = value.definitions[i]!;
        size += DefinitionDescriptor.encodedSize(item);
      }
    }
    if (value.sourceCodeInfo !== undefined) {
      size += 1;
      size += SourceCodeInfo.encodedSize(value.sourceCodeInfo);
    }
    return size;
  },
  reflection: {
    name: "SchemaDescriptor",
    fqn: "bebop.SchemaDescriptor",
    kind: BebopDefinitionKind.message,
    detail: {
      fields: [
        { name: "path", index: 1, typeName: "string" },
        { name: "package", index: 2, typeName: "string" },
        { name: "edition", index: 3, typeName: "Edition" },
        { name: "imports", index: 4, typeName: "readonly string[]" },
        { name: "definitions", index: 5, typeName: "readonly DefinitionDescriptor[]" },
        { name: "source_code_info", index: 6, typeName: "SourceCodeInfo" },
      ],
    },
  },
} satisfies BebopReflectableCodec<SchemaDescriptor>;

export type DescriptorSet = {
  readonly schemas?: readonly SchemaDescriptor[] | undefined;
};

export const DescriptorSet = {
  readFrom(reader: BebopReader): DescriptorSet {
    const end = reader.readMessageEnd();
    let schemasValue: readonly SchemaDescriptor[] | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: schemasValue = reader.readDynamicArray((_r) => SchemaDescriptor.readFrom(_r)); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      schemas: schemasValue,
    };
  },
  writeInto(writer: BebopWriter, value: DescriptorSet): void {
    const pos = writer.reserveMessageLength();
    if (value.schemas !== undefined) {
      writer.writeTag(1);
      writer.writeDynamicArray(value.schemas, (_w, _v) => {
        SchemaDescriptor.writeInto(_w, _v);
      });
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: DescriptorSet): number {
    let size = 5;
    if (value.schemas !== undefined) {
      size += 1;
      size += 4;
      for (let i = 0; i < value.schemas.length; i++) {
        const item = value.schemas[i]!;
        size += SchemaDescriptor.encodedSize(item);
      }
    }
    return size;
  },
  reflection: {
    name: "DescriptorSet",
    fqn: "bebop.DescriptorSet",
    kind: BebopDefinitionKind.message,
    detail: {
      fields: [
        { name: "schemas", index: 1, typeName: "readonly SchemaDescriptor[]" },
      ],
    },
  },
} satisfies BebopReflectableCodec<DescriptorSet>;

