// Code generated by bebopc-gen-typescript. DO NOT EDIT.
// source: /Users/andrew/projects/bebop-vnext/bebop/schemas/bebop/plugin.bop
// bebopc 2026.0.0-alpha.4

import { BebopRuntimeError } from "@bebop/runtime/error";
import type { BebopReflectableCodec } from "@bebop/runtime/reflection";
import { utf8ByteLength, type BebopReader, type BebopWriter } from "@bebop/runtime/wire";
import { SchemaDescriptor, SourceCodeInfo } from "./descriptor.bb.js";


export type Version = {
  readonly major: number;
  readonly minor: number;
  readonly patch: number;
  readonly suffix: string;
};

export const Version = {
  readFrom(reader: BebopReader): Version {
    return {
      major: reader.readInt32(),
      minor: reader.readInt32(),
      patch: reader.readInt32(),
      suffix: reader.readString(),
    };
  },
  writeInto(writer: BebopWriter, value: Version): void {
    writer.writeInt32(value.major);
    writer.writeInt32(value.minor);
    writer.writeInt32(value.patch);
    writer.writeString(value.suffix);
  },
  encodedSize(value: Version): number {
    let size = 0;
    size += 4;
    size += 4;
    size += 4;
    size += 5 + utf8ByteLength(value.suffix);
    return size;
  },
  reflection: {
    name: "Version",
    fqn: "bebop.Version",
    kind: "struct",
    detail: {
      fields: [
        { name: "major", index: 0, typeName: "number" },
        { name: "minor", index: 0, typeName: "number" },
        { name: "patch", index: 0, typeName: "number" },
        { name: "suffix", index: 0, typeName: "string" },
      ],
    },
  },
} satisfies BebopReflectableCodec<Version>;

export type CodeGeneratorRequest = {
  readonly filesToGenerate?: readonly string[] | undefined;
  readonly parameter?: string | undefined;
  readonly compilerVersion?: Version | undefined;
  readonly schemas?: readonly SchemaDescriptor[] | undefined;
  readonly hostOptions?: ReadonlyMap<string, string> | undefined;
};

export const CodeGeneratorRequest = {
  readFrom(reader: BebopReader): CodeGeneratorRequest {
    const end = reader.readMessageEnd();
    let filesToGenerateValue: readonly string[] | undefined;
    let parameterValue: string | undefined;
    let compilerVersionValue: Version | undefined;
    let schemasValue: readonly SchemaDescriptor[] | undefined;
    let hostOptionsValue: ReadonlyMap<string, string> | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: filesToGenerateValue = reader.readDynamicArray((_r) => _r.readString()); break;
        case 2: parameterValue = reader.readString(); break;
        case 3: compilerVersionValue = Version.readFrom(reader); break;
        case 4: schemasValue = reader.readDynamicArray((_r) => SchemaDescriptor.readFrom(_r)); break;
        case 5: hostOptionsValue = reader.readDynamicMap((_r) => _r.readString(), (_r) => _r.readString()); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      filesToGenerate: filesToGenerateValue,
      parameter: parameterValue,
      compilerVersion: compilerVersionValue,
      schemas: schemasValue,
      hostOptions: hostOptionsValue,
    };
  },
  writeInto(writer: BebopWriter, value: CodeGeneratorRequest): void {
    const pos = writer.reserveMessageLength();
    if (value.filesToGenerate !== undefined) {
      writer.writeTag(1);
      writer.writeDynamicArray(value.filesToGenerate, (_w, _v) => {
        _w.writeString(_v);
      });
    }
    if (value.parameter !== undefined) {
      writer.writeTag(2);
      writer.writeString(value.parameter);
    }
    if (value.compilerVersion !== undefined) {
      writer.writeTag(3);
      Version.writeInto(writer, value.compilerVersion);
    }
    if (value.schemas !== undefined) {
      writer.writeTag(4);
      writer.writeDynamicArray(value.schemas, (_w, _v) => {
        SchemaDescriptor.writeInto(_w, _v);
      });
    }
    if (value.hostOptions !== undefined) {
      writer.writeTag(5);
      writer.writeDynamicMap(value.hostOptions, (_w, _k, _v) => {
        _w.writeString(_k);
        _w.writeString(_v);
      });
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: CodeGeneratorRequest): number {
    let size = 5;
    if (value.filesToGenerate !== undefined) {
      size += 1;
      size += 4;
      for (let _i0 = 0; _i0 < value.filesToGenerate.length; _i0++) {
        const _item1 = value.filesToGenerate[_i0]!;
        size += 5 + utf8ByteLength(_item1);
      }
    }
    if (value.parameter !== undefined) {
      size += 1;
      size += 5 + utf8ByteLength(value.parameter);
    }
    if (value.compilerVersion !== undefined) {
      size += 1;
      size += Version.encodedSize(value.compilerVersion);
    }
    if (value.schemas !== undefined) {
      size += 1;
      size += 4;
      for (let _i2 = 0; _i2 < value.schemas.length; _i2++) {
        const _item3 = value.schemas[_i2]!;
        size += SchemaDescriptor.encodedSize(_item3);
      }
    }
    if (value.hostOptions !== undefined) {
      size += 1;
      size += 4;
      for (const [_k, _v] of value.hostOptions) {
        size += 5 + utf8ByteLength(_k);
        size += 5 + utf8ByteLength(_v);
      }
    }
    return size;
  },
  reflection: {
    name: "CodeGeneratorRequest",
    fqn: "bebop.CodeGeneratorRequest",
    kind: "message",
    detail: {
      fields: [
        { name: "files_to_generate", index: 1, typeName: "readonly string[]" },
        { name: "parameter", index: 2, typeName: "string" },
        { name: "compiler_version", index: 3, typeName: "Version" },
        { name: "schemas", index: 4, typeName: "readonly SchemaDescriptor[]" },
        { name: "host_options", index: 5, typeName: "ReadonlyMap<string, string>" },
      ],
    },
  },
} satisfies BebopReflectableCodec<CodeGeneratorRequest>;

export const DiagnosticSeverity = {
  ERROR: 0,
  WARNING: 1,
  INFO: 2,
  HINT: 3,
} as const;
export type DiagnosticSeverity = (typeof DiagnosticSeverity)[keyof typeof DiagnosticSeverity];

export type Diagnostic = {
  readonly severity?: DiagnosticSeverity | undefined;
  readonly text?: string | undefined;
  readonly hint?: string | undefined;
  readonly file?: string | undefined;
  readonly span?: Int32Array | undefined;
};

export const Diagnostic = {
  readFrom(reader: BebopReader): Diagnostic {
    const end = reader.readMessageEnd();
    let severityValue: DiagnosticSeverity | undefined;
    let textValue: string | undefined;
    let hintValue: string | undefined;
    let fileValue: string | undefined;
    let spanValue: Int32Array | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: severityValue = reader.readByte() as DiagnosticSeverity; break;
        case 2: textValue = reader.readString(); break;
        case 3: hintValue = reader.readString(); break;
        case 4: fileValue = reader.readString(); break;
        case 5: spanValue = reader.readInt32Array(4); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      severity: severityValue,
      text: textValue,
      hint: hintValue,
      file: fileValue,
      span: spanValue,
    };
  },
  writeInto(writer: BebopWriter, value: Diagnostic): void {
    const pos = writer.reserveMessageLength();
    if (value.severity !== undefined) {
      writer.writeTag(1);
      writer.writeByte(value.severity);
    }
    if (value.text !== undefined) {
      writer.writeTag(2);
      writer.writeString(value.text);
    }
    if (value.hint !== undefined) {
      writer.writeTag(3);
      writer.writeString(value.hint);
    }
    if (value.file !== undefined) {
      writer.writeTag(4);
      writer.writeString(value.file);
    }
    if (value.span !== undefined) {
      writer.writeTag(5);
      writer.writeInt32Array(value.span, 4);
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: Diagnostic): number {
    let size = 5;
    if (value.severity !== undefined) {
      size += 1;
      size += 1;
    }
    if (value.text !== undefined) {
      size += 1;
      size += 5 + utf8ByteLength(value.text);
    }
    if (value.hint !== undefined) {
      size += 1;
      size += 5 + utf8ByteLength(value.hint);
    }
    if (value.file !== undefined) {
      size += 1;
      size += 5 + utf8ByteLength(value.file);
    }
    if (value.span !== undefined) {
      size += 1;
      if (value.span.length !== 4) throw new BebopRuntimeError(`expected fixed length 4, got ${value.span.length}`);
      size += 16;
    }
    return size;
  },
  reflection: {
    name: "Diagnostic",
    fqn: "bebop.Diagnostic",
    kind: "message",
    detail: {
      fields: [
        { name: "severity", index: 1, typeName: "DiagnosticSeverity" },
        { name: "text", index: 2, typeName: "string" },
        { name: "hint", index: 3, typeName: "string" },
        { name: "file", index: 4, typeName: "string" },
        { name: "span", index: 5, typeName: "Int32Array" },
      ],
    },
  },
} satisfies BebopReflectableCodec<Diagnostic>;

export type GeneratedFile = {
  readonly name?: string | undefined;
  readonly insertionPoint?: string | undefined;
  readonly content?: string | undefined;
  readonly generatedCodeInfo?: SourceCodeInfo | undefined;
};

export const GeneratedFile = {
  readFrom(reader: BebopReader): GeneratedFile {
    const end = reader.readMessageEnd();
    let nameValue: string | undefined;
    let insertionPointValue: string | undefined;
    let contentValue: string | undefined;
    let generatedCodeInfoValue: SourceCodeInfo | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: nameValue = reader.readString(); break;
        case 2: insertionPointValue = reader.readString(); break;
        case 3: contentValue = reader.readString(); break;
        case 4: generatedCodeInfoValue = SourceCodeInfo.readFrom(reader); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      name: nameValue,
      insertionPoint: insertionPointValue,
      content: contentValue,
      generatedCodeInfo: generatedCodeInfoValue,
    };
  },
  writeInto(writer: BebopWriter, value: GeneratedFile): void {
    const pos = writer.reserveMessageLength();
    if (value.name !== undefined) {
      writer.writeTag(1);
      writer.writeString(value.name);
    }
    if (value.insertionPoint !== undefined) {
      writer.writeTag(2);
      writer.writeString(value.insertionPoint);
    }
    if (value.content !== undefined) {
      writer.writeTag(3);
      writer.writeString(value.content);
    }
    if (value.generatedCodeInfo !== undefined) {
      writer.writeTag(4);
      SourceCodeInfo.writeInto(writer, value.generatedCodeInfo);
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: GeneratedFile): number {
    let size = 5;
    if (value.name !== undefined) {
      size += 1;
      size += 5 + utf8ByteLength(value.name);
    }
    if (value.insertionPoint !== undefined) {
      size += 1;
      size += 5 + utf8ByteLength(value.insertionPoint);
    }
    if (value.content !== undefined) {
      size += 1;
      size += 5 + utf8ByteLength(value.content);
    }
    if (value.generatedCodeInfo !== undefined) {
      size += 1;
      size += SourceCodeInfo.encodedSize(value.generatedCodeInfo);
    }
    return size;
  },
  reflection: {
    name: "GeneratedFile",
    fqn: "bebop.GeneratedFile",
    kind: "message",
    detail: {
      fields: [
        { name: "name", index: 1, typeName: "string" },
        { name: "insertion_point", index: 2, typeName: "string" },
        { name: "content", index: 3, typeName: "string" },
        { name: "generated_code_info", index: 4, typeName: "SourceCodeInfo" },
      ],
    },
  },
} satisfies BebopReflectableCodec<GeneratedFile>;

export type CodeGeneratorResponse = {
  readonly error?: string | undefined;
  readonly files?: readonly GeneratedFile[] | undefined;
  readonly diagnostics?: readonly Diagnostic[] | undefined;
};

export const CodeGeneratorResponse = {
  readFrom(reader: BebopReader): CodeGeneratorResponse {
    const end = reader.readMessageEnd();
    let errorValue: string | undefined;
    let filesValue: readonly GeneratedFile[] | undefined;
    let diagnosticsValue: readonly Diagnostic[] | undefined;
    while (reader.index < end) {
      const tag = reader.readTag();
      if (tag === 0) break;
      switch (tag) {
        case 1: errorValue = reader.readString(); break;
        case 2: filesValue = reader.readDynamicArray((_r) => GeneratedFile.readFrom(_r)); break;
        case 3: diagnosticsValue = reader.readDynamicArray((_r) => Diagnostic.readFrom(_r)); break;
        default: reader.skip(end - reader.index);
      }
    }
    return {
      error: errorValue,
      files: filesValue,
      diagnostics: diagnosticsValue,
    };
  },
  writeInto(writer: BebopWriter, value: CodeGeneratorResponse): void {
    const pos = writer.reserveMessageLength();
    if (value.error !== undefined) {
      writer.writeTag(1);
      writer.writeString(value.error);
    }
    if (value.files !== undefined) {
      writer.writeTag(2);
      writer.writeDynamicArray(value.files, (_w, _v) => {
        GeneratedFile.writeInto(_w, _v);
      });
    }
    if (value.diagnostics !== undefined) {
      writer.writeTag(3);
      writer.writeDynamicArray(value.diagnostics, (_w, _v) => {
        Diagnostic.writeInto(_w, _v);
      });
    }
    writer.writeEndMarker();
    writer.fillMessageLength(pos);
  },
  encodedSize(value: CodeGeneratorResponse): number {
    let size = 5;
    if (value.error !== undefined) {
      size += 1;
      size += 5 + utf8ByteLength(value.error);
    }
    if (value.files !== undefined) {
      size += 1;
      size += 4;
      for (let _i4 = 0; _i4 < value.files.length; _i4++) {
        const _item5 = value.files[_i4]!;
        size += GeneratedFile.encodedSize(_item5);
      }
    }
    if (value.diagnostics !== undefined) {
      size += 1;
      size += 4;
      for (let _i6 = 0; _i6 < value.diagnostics.length; _i6++) {
        const _item7 = value.diagnostics[_i6]!;
        size += Diagnostic.encodedSize(_item7);
      }
    }
    return size;
  },
  reflection: {
    name: "CodeGeneratorResponse",
    fqn: "bebop.CodeGeneratorResponse",
    kind: "message",
    detail: {
      fields: [
        { name: "error", index: 1, typeName: "string" },
        { name: "files", index: 2, typeName: "readonly GeneratedFile[]" },
        { name: "diagnostics", index: 3, typeName: "readonly Diagnostic[]" },
      ],
    },
  },
} satisfies BebopReflectableCodec<CodeGeneratorResponse>;
